// Generated by `npm run manifest` from src/content/paths. Don't edit by hand.
import type { PathMeta } from "./types";

export const manifest: PathMeta[] = [
  {
    "id": "heuristics",
    "title": "Nielsen's 10 usability heuristics",
    "description": "Ten rules of thumb for spotting usability problems in any screen: clear feedback, familiar words, undo, consistency, preventing errors and more.",
    "status": "live",
    "lessons": [
      {
        "id": "h1",
        "code": "H1",
        "title": "Visibility of system status",
        "subtitle": "Keep people informed, right away",
        "minutes": 5,
        "skills": [
          "feedback"
        ],
        "exercises": [
          {
            "id": "h1-upload-progress",
            "type": "compare"
          },
          {
            "id": "h1-save-feedback",
            "type": "choice"
          },
          {
            "id": "h1-spot-silent-upload",
            "type": "spot"
          },
          {
            "id": "h1-sort-wait",
            "type": "sort"
          }
        ]
      },
      {
        "id": "h2",
        "code": "H2",
        "title": "Match between the system and the real world",
        "subtitle": "Speak the user's language",
        "minutes": 5,
        "skills": [
          "language"
        ],
        "exercises": [
          {
            "id": "h2-date-field",
            "type": "compare"
          },
          {
            "id": "h2-field-label",
            "type": "choice"
          },
          {
            "id": "h2-spot-system-units",
            "type": "spot"
          },
          {
            "id": "h2-sort-words",
            "type": "sort"
          }
        ]
      },
      {
        "id": "h3",
        "code": "H3",
        "title": "User control and freedom",
        "subtitle": "Clear exits and easy undo",
        "minutes": 5,
        "skills": [
          "control"
        ],
        "exercises": [
          {
            "id": "h3-undo-vs-confirm",
            "type": "compare"
          },
          {
            "id": "h3-wizard-back",
            "type": "choice"
          },
          {
            "id": "h3-spot-no-way-back",
            "type": "spot"
          },
          {
            "id": "h3-sort-exits",
            "type": "sort"
          }
        ]
      },
      {
        "id": "h4",
        "code": "H4",
        "title": "Consistency and standards",
        "subtitle": "Same thing, same look, same place",
        "minutes": 5,
        "skills": [
          "conventions"
        ],
        "exercises": [
          {
            "id": "h4-dialog-conventions",
            "type": "compare"
          },
          {
            "id": "h4-logo-home",
            "type": "choice"
          },
          {
            "id": "h4-spot-odd-actions",
            "type": "spot"
          },
          {
            "id": "h4-sort-conventions",
            "type": "sort"
          }
        ]
      },
      {
        "id": "h5",
        "code": "H5",
        "title": "Error prevention",
        "subtitle": "Design so mistakes are hard to make",
        "minutes": 5,
        "skills": [
          "errors"
        ],
        "exercises": [
          {
            "id": "h5-danger-zone",
            "type": "compare"
          },
          {
            "id": "h5-forgiving-input",
            "type": "choice"
          },
          {
            "id": "h5-spot-delete",
            "type": "spot"
          },
          {
            "id": "h5-sort-prevent",
            "type": "sort"
          }
        ]
      },
      {
        "id": "h6",
        "code": "H6",
        "title": "Recognition rather than recall",
        "subtitle": "Show options instead of testing memory",
        "minutes": 5,
        "skills": [
          "effort"
        ],
        "exercises": [
          {
            "id": "h6-recent-items",
            "type": "compare"
          },
          {
            "id": "h6-checkout-summary",
            "type": "choice"
          },
          {
            "id": "h6-spot-remember-code",
            "type": "spot"
          },
          {
            "id": "h6-sort-recognition",
            "type": "sort"
          }
        ]
      },
      {
        "id": "h7",
        "code": "H7",
        "title": "Flexibility and efficiency of use",
        "subtitle": "Shortcuts for experts, simple paths for novices",
        "minutes": 5,
        "skills": [
          "control"
        ],
        "exercises": [
          {
            "id": "h7-bulk-grid",
            "type": "compare"
          },
          {
            "id": "h7-visible-shortcuts",
            "type": "choice"
          },
          {
            "id": "h7-spot-one-at-a-time",
            "type": "spot"
          },
          {
            "id": "h7-sort-accelerators",
            "type": "sort"
          }
        ]
      },
      {
        "id": "h8",
        "code": "H8",
        "title": "Aesthetic and minimalist design",
        "subtitle": "Every element competes for attention",
        "minutes": 5,
        "skills": [
          "effort",
          "layout"
        ],
        "exercises": [
          {
            "id": "h8-focused-card",
            "type": "compare"
          },
          {
            "id": "h8-minimalist-meaning",
            "type": "choice"
          },
          {
            "id": "h8-spot-promo-clutter",
            "type": "spot"
          },
          {
            "id": "h8-sort-noise",
            "type": "sort"
          }
        ]
      },
      {
        "id": "h9",
        "code": "H9",
        "title": "Help users recognize, diagnose, and recover from errors",
        "subtitle": "Plain language, precise problem, a way forward",
        "minutes": 5,
        "skills": [
          "feedback"
        ],
        "exercises": [
          {
            "id": "h9-existing-account",
            "type": "compare"
          },
          {
            "id": "h9-error-placement",
            "type": "choice"
          },
          {
            "id": "h9-spot-error-code",
            "type": "spot"
          },
          {
            "id": "h9-sort-recover",
            "type": "sort"
          }
        ]
      },
      {
        "id": "h10",
        "code": "H10",
        "title": "Help and documentation",
        "subtitle": "Help that is easy to find and act on",
        "minutes": 5,
        "skills": [
          "language"
        ],
        "exercises": [
          {
            "id": "h10-contextual-help",
            "type": "compare"
          },
          {
            "id": "h10-task-titles",
            "type": "choice"
          },
          {
            "id": "h10-spot-manual-link",
            "type": "spot"
          },
          {
            "id": "h10-sort-help",
            "type": "sort"
          }
        ]
      }
    ]
  },
  {
    "id": "accessibility",
    "title": "Accessibility basics",
    "description": "Who accessibility serves, contrast, keyboard access, structure and forms. Built from W3C WAI material.",
    "status": "live",
    "lessons": [
      {
        "id": "a1",
        "code": "A1",
        "title": "Who accessibility is for",
        "subtitle": "More people than you think, and the standard behind it",
        "minutes": 5,
        "skills": [
          "accessibility"
        ],
        "exercises": [
          {
            "id": "a1-video-captions",
            "type": "compare"
          },
          {
            "id": "a1-who-benefits",
            "type": "choice"
          },
          {
            "id": "a1-spot-no-captions",
            "type": "spot"
          },
          {
            "id": "a1-sort-who",
            "type": "sort"
          }
        ]
      },
      {
        "id": "a2",
        "code": "A2",
        "title": "Text alternatives",
        "subtitle": "Describe images by their purpose",
        "minutes": 5,
        "skills": [
          "accessibility",
          "language"
        ],
        "exercises": [
          {
            "id": "a2-icon-button",
            "type": "compare"
          },
          {
            "id": "a2-decorative",
            "type": "choice"
          },
          {
            "id": "a2-spot-logo-filename",
            "type": "spot"
          },
          {
            "id": "a2-sort-alt",
            "type": "sort"
          }
        ]
      },
      {
        "id": "a3",
        "code": "A3",
        "title": "Color contrast",
        "subtitle": "Text people can actually read",
        "minutes": 5,
        "skills": [
          "accessibility",
          "layout"
        ],
        "exercises": [
          {
            "id": "a3-helper-text",
            "type": "compare"
          },
          {
            "id": "a3-ratio",
            "type": "choice"
          },
          {
            "id": "a3-spot-contrast-ratios",
            "type": "spot"
          },
          {
            "id": "a3-sort-ratio",
            "type": "sort"
          }
        ]
      },
      {
        "id": "a4",
        "code": "A4",
        "title": "Don't rely on color alone",
        "subtitle": "Always add a second cue",
        "minutes": 4,
        "skills": [
          "accessibility",
          "layout"
        ],
        "exercises": [
          {
            "id": "a4-status-dots",
            "type": "compare"
          },
          {
            "id": "a4-required-fields",
            "type": "choice"
          },
          {
            "id": "a4-spot-red-border-only",
            "type": "spot"
          },
          {
            "id": "a4-sort-color",
            "type": "sort"
          }
        ]
      },
      {
        "id": "a5",
        "code": "A5",
        "title": "Keyboard access and visible focus",
        "subtitle": "Everything works without a mouse",
        "minutes": 5,
        "skills": [
          "accessibility",
          "control"
        ],
        "exercises": [
          {
            "id": "a5-focus-visible",
            "type": "compare"
          },
          {
            "id": "a5-div-button",
            "type": "choice"
          },
          {
            "id": "a5-spot-keyboard-trap",
            "type": "spot"
          },
          {
            "id": "a5-sort-keyboard",
            "type": "sort"
          }
        ]
      },
      {
        "id": "a6",
        "code": "A6",
        "title": "Headings and page structure",
        "subtitle": "Let people skim with a screen reader",
        "minutes": 5,
        "skills": [
          "accessibility",
          "layout"
        ],
        "exercises": [
          {
            "id": "a6-heading-outline",
            "type": "compare"
          },
          {
            "id": "a6-heading-level",
            "type": "choice"
          },
          {
            "id": "a6-spot-skipped-level",
            "type": "spot"
          },
          {
            "id": "a6-sort-headings",
            "type": "sort"
          }
        ]
      },
      {
        "id": "a7",
        "code": "A7",
        "title": "Accessible forms",
        "subtitle": "Labels, hints and errors everyone gets",
        "minutes": 5,
        "skills": [
          "accessibility",
          "forms"
        ],
        "exercises": [
          {
            "id": "a7-placeholder-label",
            "type": "compare"
          },
          {
            "id": "a7-error-message",
            "type": "choice"
          },
          {
            "id": "a7-spot-placeholder",
            "type": "spot"
          },
          {
            "id": "a7-sort-forms",
            "type": "sort"
          }
        ]
      },
      {
        "id": "a8",
        "code": "A8",
        "title": "Links, buttons and targets",
        "subtitle": "Clear names and room to tap",
        "minutes": 5,
        "skills": [
          "accessibility",
          "language"
        ],
        "exercises": [
          {
            "id": "a8-link-text",
            "type": "compare"
          },
          {
            "id": "a8-target-size",
            "type": "choice"
          },
          {
            "id": "a8-spot-click-here",
            "type": "spot"
          },
          {
            "id": "a8-sort-link-button",
            "type": "sort"
          }
        ]
      }
    ]
  },
  {
    "id": "forms",
    "title": "Form design",
    "description": "Asking the right questions, labels, dates, choices and errors, drawing on GOV.UK and USWDS research.",
    "status": "live",
    "lessons": [
      {
        "id": "f1",
        "code": "F1",
        "title": "Ask only what you need",
        "subtitle": "The easiest question is the one you remove",
        "minutes": 4,
        "skills": [
          "forms",
          "language"
        ],
        "exercises": [
          {
            "id": "f1-signup-fields",
            "type": "compare"
          },
          {
            "id": "f1-question-protocol",
            "type": "choice"
          },
          {
            "id": "f1-spot-unneeded-question",
            "type": "spot"
          },
          {
            "id": "f1-sort-needed",
            "type": "sort"
          }
        ]
      },
      {
        "id": "f2",
        "code": "F2",
        "title": "One thing per page",
        "subtitle": "Small steps, then a chance to check",
        "minutes": 5,
        "skills": [
          "forms",
          "effort"
        ],
        "exercises": [
          {
            "id": "f2-check-answers",
            "type": "compare"
          },
          {
            "id": "f2-one-thing",
            "type": "choice"
          },
          {
            "id": "f2-spot-no-change-link",
            "type": "spot"
          },
          {
            "id": "f2-sort-together",
            "type": "sort"
          }
        ]
      },
      {
        "id": "f3",
        "code": "F3",
        "title": "Labels, hints and field sizes",
        "subtitle": "Tell people what to enter and how",
        "minutes": 4,
        "skills": [
          "forms",
          "language",
          "errors"
        ],
        "exercises": [
          {
            "id": "f3-field-width",
            "type": "compare"
          },
          {
            "id": "f3-hint-placement",
            "type": "choice"
          },
          {
            "id": "f3-spot-wide-code",
            "type": "spot"
          },
          {
            "id": "f3-sort-width",
            "type": "sort"
          }
        ]
      },
      {
        "id": "f4",
        "code": "F4",
        "title": "Names and personal details",
        "subtitle": "Fit the person, not the database",
        "minutes": 5,
        "skills": [
          "forms",
          "language"
        ],
        "exercises": [
          {
            "id": "f4-name-error",
            "type": "compare"
          },
          {
            "id": "f4-autocomplete",
            "type": "choice"
          },
          {
            "id": "f4-spot-name-rules",
            "type": "spot"
          },
          {
            "id": "f4-sort-names",
            "type": "sort"
          }
        ]
      },
      {
        "id": "f5",
        "code": "F5",
        "title": "Dates",
        "subtitle": "Ask for them the way people know them",
        "minutes": 4,
        "skills": [
          "forms",
          "errors"
        ],
        "exercises": [
          {
            "id": "f5-dob",
            "type": "compare"
          },
          {
            "id": "f5-picker-when",
            "type": "choice"
          },
          {
            "id": "f5-spot-dob-calendar",
            "type": "spot"
          },
          {
            "id": "f5-sort-date-input",
            "type": "sort"
          }
        ]
      },
      {
        "id": "f6",
        "code": "F6",
        "title": "Radios, checkboxes and selects",
        "subtitle": "Pick the control that shows the choice",
        "minutes": 4,
        "skills": [
          "forms",
          "conventions"
        ],
        "exercises": [
          {
            "id": "f6-radios-vs-select",
            "type": "compare"
          },
          {
            "id": "f6-control-choice",
            "type": "choice"
          },
          {
            "id": "f6-spot-two-option-select",
            "type": "spot"
          },
          {
            "id": "f6-sort-control",
            "type": "sort"
          }
        ]
      },
      {
        "id": "f7",
        "code": "F7",
        "title": "Required and optional fields",
        "subtitle": "Say it in words",
        "minutes": 4,
        "skills": [
          "forms"
        ],
        "exercises": [
          {
            "id": "f7-required-markers",
            "type": "compare"
          },
          {
            "id": "f7-optional",
            "type": "choice"
          },
          {
            "id": "f7-spot-lone-asterisk",
            "type": "spot"
          },
          {
            "id": "f7-sort-marking",
            "type": "sort"
          }
        ]
      },
      {
        "id": "f8",
        "code": "F8",
        "title": "Errors and validation",
        "subtitle": "What went wrong, where, and how to fix it",
        "minutes": 5,
        "skills": [
          "forms",
          "feedback"
        ],
        "exercises": [
          {
            "id": "f8-error-summary",
            "type": "compare"
          },
          {
            "id": "f8-timing",
            "type": "choice"
          },
          {
            "id": "f8-spot-vague-error",
            "type": "spot"
          },
          {
            "id": "f8-sort-errors",
            "type": "sort"
          }
        ]
      }
    ]
  },
  {
    "id": "laws-of-ux",
    "title": "Laws of UX",
    "description": "Jakob's, Fitts's, Hick's and Miller's laws, Gestalt grouping and other psychology principles.",
    "status": "live",
    "lessons": [
      {
        "id": "l1",
        "code": "L1",
        "title": "Jakob's Law",
        "subtitle": "People expect your product to work like the ones they already use",
        "minutes": 4,
        "skills": [
          "conventions"
        ],
        "exercises": [
          {
            "id": "l1-cart-location",
            "type": "compare"
          },
          {
            "id": "l1-new-pattern",
            "type": "choice"
          },
          {
            "id": "l1-spot-hidden-cart",
            "type": "spot"
          },
          {
            "id": "l1-sort-placement",
            "type": "sort"
          }
        ]
      },
      {
        "id": "l2",
        "code": "L2",
        "title": "Fitts's Law",
        "subtitle": "Big and close is easy to hit",
        "minutes": 4,
        "skills": [
          "control",
          "errors"
        ],
        "exercises": [
          {
            "id": "l2-row-target",
            "type": "compare"
          },
          {
            "id": "l2-destructive",
            "type": "choice"
          },
          {
            "id": "l2-spot-tiny-continue",
            "type": "spot"
          },
          {
            "id": "l2-sort-targets",
            "type": "sort"
          }
        ]
      },
      {
        "id": "l3",
        "code": "L3",
        "title": "Hick's Law",
        "subtitle": "More choices, slower decisions",
        "minutes": 4,
        "skills": [
          "effort"
        ],
        "exercises": [
          {
            "id": "l3-plan-picker",
            "type": "compare"
          },
          {
            "id": "l3-export-settings",
            "type": "choice"
          },
          {
            "id": "l3-spot-too-many-options",
            "type": "spot"
          },
          {
            "id": "l3-sort-choices",
            "type": "sort"
          }
        ]
      },
      {
        "id": "l4",
        "code": "L4",
        "title": "Miller's Law and chunking",
        "subtitle": "Memory is small, so group things",
        "minutes": 5,
        "skills": [
          "effort"
        ],
        "exercises": [
          {
            "id": "l4-reference-code",
            "type": "compare"
          },
          {
            "id": "l4-menu-myth",
            "type": "choice"
          },
          {
            "id": "l4-spot-long-code",
            "type": "spot"
          },
          {
            "id": "l4-sort-chunks",
            "type": "sort"
          }
        ]
      },
      {
        "id": "l5",
        "code": "L5",
        "title": "Proximity and common region",
        "subtitle": "Grouping without words",
        "minutes": 4,
        "skills": [
          "layout"
        ],
        "exercises": [
          {
            "id": "l5-label-spacing",
            "type": "compare"
          },
          {
            "id": "l5-save-placement",
            "type": "choice"
          },
          {
            "id": "l5-spot-floating-save",
            "type": "spot"
          },
          {
            "id": "l5-sort-grouping",
            "type": "sort"
          }
        ]
      },
      {
        "id": "l6",
        "code": "L6",
        "title": "The Von Restorff effect",
        "subtitle": "What stands out gets noticed",
        "minutes": 4,
        "skills": [
          "layout"
        ],
        "exercises": [
          {
            "id": "l6-primary-action",
            "type": "compare"
          },
          {
            "id": "l6-too-many-highlights",
            "type": "choice"
          },
          {
            "id": "l6-spot-everything-bold",
            "type": "spot"
          },
          {
            "id": "l6-sort-standout",
            "type": "sort"
          }
        ]
      },
      {
        "id": "l7",
        "code": "L7",
        "title": "The peak-end rule",
        "subtitle": "People remember the high points and the ending",
        "minutes": 4,
        "skills": [
          "feedback"
        ],
        "exercises": [
          {
            "id": "l7-confirmation",
            "type": "compare"
          },
          {
            "id": "l7-fix-the-low",
            "type": "choice"
          },
          {
            "id": "l7-spot-flat-ending",
            "type": "spot"
          },
          {
            "id": "l7-sort-endings",
            "type": "sort"
          }
        ]
      },
      {
        "id": "l8",
        "code": "L8",
        "title": "Tesler's Law",
        "subtitle": "Complexity has to live somewhere",
        "minutes": 4,
        "skills": [
          "effort"
        ],
        "exercises": [
          {
            "id": "l8-currency",
            "type": "compare"
          },
          {
            "id": "l8-hidden-fees",
            "type": "choice"
          },
          {
            "id": "l8-spot-utc-offset",
            "type": "spot"
          },
          {
            "id": "l8-sort-complexity",
            "type": "sort"
          }
        ]
      }
    ]
  },
  {
    "id": "research",
    "title": "UX research methods",
    "description": "Choosing methods, planning, recruiting, interviews, usability testing, surveys, analysis and research ethics.",
    "status": "live",
    "lessons": [
      {
        "id": "r1",
        "code": "R1",
        "title": "Choosing a research method",
        "subtitle": "Match the method to the question",
        "minutes": 5,
        "skills": [
          "research"
        ],
        "exercises": [
          {
            "id": "r1-say-vs-do",
            "type": "compare"
          },
          {
            "id": "r1-why-not-how-many",
            "type": "choice"
          },
          {
            "id": "r1-spot-wrong-method",
            "type": "spot"
          },
          {
            "id": "r1-sort-say-do",
            "type": "sort"
          }
        ]
      },
      {
        "id": "r2",
        "code": "R2",
        "title": "Planning research",
        "subtitle": "Start with what you need to learn",
        "minutes": 5,
        "skills": [
          "research"
        ],
        "exercises": [
          {
            "id": "r2-research-question",
            "type": "compare"
          },
          {
            "id": "r2-first-step",
            "type": "choice"
          },
          {
            "id": "r2-spot-plan",
            "type": "spot"
          },
          {
            "id": "r2-sort-questions",
            "type": "sort"
          }
        ]
      },
      {
        "id": "r3",
        "code": "R3",
        "title": "Recruiting participants",
        "subtitle": "The right people, and enough of them",
        "minutes": 5,
        "skills": [
          "research"
        ],
        "exercises": [
          {
            "id": "r3-screener",
            "type": "compare"
          },
          {
            "id": "r3-how-many",
            "type": "choice"
          },
          {
            "id": "r3-spot-brief",
            "type": "spot"
          },
          {
            "id": "r3-sort-screener",
            "type": "sort"
          }
        ]
      },
      {
        "id": "r4",
        "code": "R4",
        "title": "User interviews",
        "subtitle": "Ask about real experiences, not opinions",
        "minutes": 5,
        "skills": [
          "research",
          "language"
        ],
        "exercises": [
          {
            "id": "r4-past-not-future",
            "type": "compare"
          },
          {
            "id": "r4-leading",
            "type": "choice"
          },
          {
            "id": "r4-spot-guide",
            "type": "spot"
          },
          {
            "id": "r4-sort-interview",
            "type": "sort"
          }
        ]
      },
      {
        "id": "r5",
        "code": "R5",
        "title": "Usability testing",
        "subtitle": "Watch people try, and don't help",
        "minutes": 5,
        "skills": [
          "research"
        ],
        "exercises": [
          {
            "id": "r5-task-wording",
            "type": "compare"
          },
          {
            "id": "r5-when-stuck",
            "type": "choice"
          },
          {
            "id": "r5-spot-script",
            "type": "spot"
          },
          {
            "id": "r5-sort-facilitation",
            "type": "sort"
          }
        ]
      },
      {
        "id": "r6",
        "code": "R6",
        "title": "Surveys",
        "subtitle": "Good for counting, with good questions",
        "minutes": 5,
        "skills": [
          "research",
          "forms",
          "language"
        ],
        "exercises": [
          {
            "id": "r6-balanced-scale",
            "type": "compare"
          },
          {
            "id": "r6-double-barreled",
            "type": "choice"
          },
          {
            "id": "r6-spot-question",
            "type": "spot"
          },
          {
            "id": "r6-sort-survey",
            "type": "sort"
          }
        ]
      },
      {
        "id": "r7",
        "code": "R7",
        "title": "Making sense of findings",
        "subtitle": "From observations to decisions",
        "minutes": 5,
        "skills": [
          "research"
        ],
        "exercises": [
          {
            "id": "r7-observation-note",
            "type": "compare"
          },
          {
            "id": "r7-sharing",
            "type": "choice"
          },
          {
            "id": "r7-spot-finding",
            "type": "spot"
          },
          {
            "id": "r7-sort-observation",
            "type": "sort"
          }
        ]
      },
      {
        "id": "r8",
        "code": "R8",
        "title": "Research ethics and consent",
        "subtitle": "Respect the people who help you",
        "minutes": 5,
        "skills": [
          "research",
          "accessibility"
        ],
        "exercises": [
          {
            "id": "r8-consent",
            "type": "compare"
          },
          {
            "id": "r8-sharing-clips",
            "type": "choice"
          },
          {
            "id": "r8-spot-notes",
            "type": "spot"
          },
          {
            "id": "r8-sort-ethics",
            "type": "sort"
          }
        ]
      }
    ]
  },
  {
    "id": "visual-design",
    "title": "Visual design basics",
    "description": "Hierarchy, typography, spacing, color, layout, icons, buttons and design systems.",
    "status": "live",
    "lessons": [
      {
        "id": "v1",
        "code": "V1",
        "title": "Visual hierarchy",
        "subtitle": "Show what matters first",
        "minutes": 5,
        "skills": [
          "layout"
        ],
        "exercises": [
          {
            "id": "v1-balance-first",
            "type": "compare"
          },
          {
            "id": "v1-everything-bold",
            "type": "choice"
          },
          {
            "id": "v1-spot-competing",
            "type": "spot"
          },
          {
            "id": "v1-sort-prominence",
            "type": "sort"
          }
        ]
      },
      {
        "id": "v2",
        "code": "V2",
        "title": "Typography for interfaces",
        "subtitle": "Text that's easy to read",
        "minutes": 5,
        "skills": [
          "layout",
          "accessibility"
        ],
        "exercises": [
          {
            "id": "v2-readable-text",
            "type": "compare"
          },
          {
            "id": "v2-line-height",
            "type": "choice"
          },
          {
            "id": "v2-spot-legal",
            "type": "spot"
          },
          {
            "id": "v2-sort-readability",
            "type": "sort"
          }
        ]
      },
      {
        "id": "v3",
        "code": "V3",
        "title": "Spacing and alignment",
        "subtitle": "Space is information",
        "minutes": 4,
        "skills": [
          "layout"
        ],
        "exercises": [
          {
            "id": "v3-one-edge",
            "type": "compare"
          },
          {
            "id": "v3-scale",
            "type": "choice"
          },
          {
            "id": "v3-spot-misaligned",
            "type": "spot"
          },
          {
            "id": "v3-sort-scanning",
            "type": "sort"
          }
        ]
      },
      {
        "id": "v4",
        "code": "V4",
        "title": "Color with a purpose",
        "subtitle": "Fewer colors, clearer meaning",
        "minutes": 5,
        "skills": [
          "layout",
          "accessibility"
        ],
        "exercises": [
          {
            "id": "v4-color-signals",
            "type": "compare"
          },
          {
            "id": "v4-red-badges",
            "type": "choice"
          },
          {
            "id": "v4-spot-color-job",
            "type": "spot"
          },
          {
            "id": "v4-sort-color",
            "type": "sort"
          }
        ]
      },
      {
        "id": "v5",
        "code": "V5",
        "title": "Layout and grids",
        "subtitle": "Structure that adapts",
        "minutes": 5,
        "skills": [
          "layout"
        ],
        "exercises": [
          {
            "id": "v5-mobile-order",
            "type": "compare"
          },
          {
            "id": "v5-grid-benefit",
            "type": "choice"
          },
          {
            "id": "v5-spot-buried-words",
            "type": "spot"
          },
          {
            "id": "v5-sort-mobile",
            "type": "sort"
          }
        ]
      },
      {
        "id": "v6",
        "code": "V6",
        "title": "Icons and imagery",
        "subtitle": "Pictures that help, not puzzle",
        "minutes": 4,
        "skills": [
          "layout",
          "language"
        ],
        "exercises": [
          {
            "id": "v6-labelled-icons",
            "type": "compare"
          },
          {
            "id": "v6-stock-photo",
            "type": "choice"
          },
          {
            "id": "v6-spot-odd-icon",
            "type": "spot"
          },
          {
            "id": "v6-sort-icons",
            "type": "sort"
          }
        ]
      },
      {
        "id": "v7",
        "code": "V7",
        "title": "Buttons that look clickable",
        "subtitle": "Make actions obvious",
        "minutes": 5,
        "skills": [
          "control",
          "conventions"
        ],
        "exercises": [
          {
            "id": "v7-looks-clickable",
            "type": "compare"
          },
          {
            "id": "v7-labels",
            "type": "choice"
          },
          {
            "id": "v7-spot-hidden-link",
            "type": "spot"
          },
          {
            "id": "v7-sort-clickable",
            "type": "sort"
          }
        ]
      },
      {
        "id": "v8",
        "code": "V8",
        "title": "Visual consistency and design systems",
        "subtitle": "Decide once, reuse everywhere",
        "minutes": 5,
        "skills": [
          "conventions",
          "layout"
        ],
        "exercises": [
          {
            "id": "v8-token-names",
            "type": "compare"
          },
          {
            "id": "v8-reuse",
            "type": "choice"
          },
          {
            "id": "v8-spot-off-system",
            "type": "spot"
          },
          {
            "id": "v8-sort-system",
            "type": "sort"
          }
        ]
      }
    ]
  },
  {
    "id": "ux-writing",
    "title": "UX writing and microcopy",
    "description": "Plain words, button labels, error messages, empty states, confirmations, success messages, tone and scannable text.",
    "status": "live",
    "lessons": [
      {
        "id": "w1",
        "code": "W1",
        "title": "Plain, familiar words",
        "subtitle": "Say it the way your users would",
        "minutes": 5,
        "skills": [
          "language"
        ],
        "exercises": [
          {
            "id": "w1-refund-status",
            "type": "compare"
          },
          {
            "id": "w1-experts",
            "type": "choice"
          },
          {
            "id": "w1-spot-internal-term",
            "type": "spot"
          },
          {
            "id": "w1-sort-plain",
            "type": "sort"
          }
        ]
      },
      {
        "id": "w2",
        "code": "W2",
        "title": "Buttons and links that say what they do",
        "subtitle": "Label the action, not the click",
        "minutes": 5,
        "skills": [
          "language",
          "conventions"
        ],
        "exercises": [
          {
            "id": "w2-submit-label",
            "type": "compare"
          },
          {
            "id": "w2-link-text",
            "type": "choice"
          },
          {
            "id": "w2-spot-vague",
            "type": "spot"
          },
          {
            "id": "w2-sort-labels",
            "type": "sort"
          }
        ]
      },
      {
        "id": "w3",
        "code": "W3",
        "title": "Error messages that help people recover",
        "subtitle": "Explain the problem and the way out",
        "minutes": 5,
        "skills": [
          "language",
          "errors"
        ],
        "exercises": [
          {
            "id": "w3-date-error",
            "type": "compare"
          },
          {
            "id": "w3-server-error",
            "type": "choice"
          },
          {
            "id": "w3-spot-blame",
            "type": "spot"
          },
          {
            "id": "w3-sort-whose",
            "type": "sort"
          }
        ]
      },
      {
        "id": "w4",
        "code": "W4",
        "title": "Empty states",
        "subtitle": "Turn nothing into a next step",
        "minutes": 4,
        "skills": [
          "feedback",
          "language"
        ],
        "exercises": [
          {
            "id": "w4-first-project",
            "type": "compare"
          },
          {
            "id": "w4-no-results",
            "type": "choice"
          },
          {
            "id": "w4-spot-dead-end",
            "type": "spot"
          },
          {
            "id": "w4-sort-empty",
            "type": "sort"
          }
        ]
      },
      {
        "id": "w5",
        "code": "W5",
        "title": "Confirmation dialogs",
        "subtitle": "Ask a real question, name the real answers",
        "minutes": 5,
        "skills": [
          "errors",
          "language"
        ],
        "exercises": [
          {
            "id": "w5-yes-no",
            "type": "compare"
          },
          {
            "id": "w5-when",
            "type": "choice"
          },
          {
            "id": "w5-spot-cancel",
            "type": "spot"
          },
          {
            "id": "w5-sort-confirm-undo",
            "type": "sort"
          }
        ]
      },
      {
        "id": "w6",
        "code": "W6",
        "title": "Success and status messages",
        "subtitle": "Confirm what happened and what's next",
        "minutes": 5,
        "skills": [
          "feedback"
        ],
        "exercises": [
          {
            "id": "w6-payment-done",
            "type": "compare"
          },
          {
            "id": "w6-rename",
            "type": "choice"
          },
          {
            "id": "w6-spot-generic",
            "type": "spot"
          },
          {
            "id": "w6-sort-weight",
            "type": "sort"
          }
        ]
      },
      {
        "id": "w7",
        "code": "W7",
        "title": "Voice and tone",
        "subtitle": "One personality, adjusted to the moment",
        "minutes": 5,
        "skills": [
          "language"
        ],
        "exercises": [
          {
            "id": "w7-locked-account",
            "type": "compare"
          },
          {
            "id": "w7-voice-vs-tone",
            "type": "choice"
          },
          {
            "id": "w7-spot-tone",
            "type": "spot"
          },
          {
            "id": "w7-sort-tone",
            "type": "sort"
          }
        ]
      },
      {
        "id": "w8",
        "code": "W8",
        "title": "Writing for scanning",
        "subtitle": "Headings, labels and front-loaded text",
        "minutes": 5,
        "skills": [
          "language",
          "conventions"
        ],
        "exercises": [
          {
            "id": "w8-export-heading",
            "type": "compare"
          },
          {
            "id": "w8-one-name",
            "type": "choice"
          },
          {
            "id": "w8-spot-buried",
            "type": "spot"
          },
          {
            "id": "w8-sort-frontload",
            "type": "sort"
          }
        ]
      }
    ]
  },
  {
    "id": "interaction-design",
    "title": "Interaction design",
    "description": "Signifiers, component states, response times, navigation, progressive disclosure, modals, motion, and touch and keyboard input.",
    "status": "live",
    "lessons": [
      {
        "id": "i1",
        "code": "I1",
        "title": "Affordances and signifiers",
        "subtitle": "Show what can be done",
        "minutes": 5,
        "skills": [
          "conventions",
          "layout"
        ],
        "exercises": [
          {
            "id": "i1-open-report",
            "type": "compare"
          },
          {
            "id": "i1-false-signifier",
            "type": "choice"
          },
          {
            "id": "i1-spot-false-link",
            "type": "spot"
          },
          {
            "id": "i1-sort-signifiers",
            "type": "sort"
          }
        ]
      },
      {
        "id": "i2",
        "code": "I2",
        "title": "Component states",
        "subtitle": "Design every state, not just the default",
        "minutes": 5,
        "skills": [
          "feedback",
          "accessibility"
        ],
        "exercises": [
          {
            "id": "i2-double-pay",
            "type": "compare"
          },
          {
            "id": "i2-disabled",
            "type": "choice"
          },
          {
            "id": "i2-spot-color-only",
            "type": "spot"
          },
          {
            "id": "i2-sort-states",
            "type": "sort"
          }
        ]
      },
      {
        "id": "i3",
        "code": "I3",
        "title": "Response time and loading",
        "subtitle": "What to show while people wait",
        "minutes": 5,
        "skills": [
          "feedback"
        ],
        "exercises": [
          {
            "id": "i3-skeleton",
            "type": "compare"
          },
          {
            "id": "i3-long-task",
            "type": "choice"
          },
          {
            "id": "i3-spot-silent",
            "type": "spot"
          },
          {
            "id": "i3-sort-indicator",
            "type": "sort"
          }
        ]
      },
      {
        "id": "i4",
        "code": "I4",
        "title": "Navigation patterns",
        "subtitle": "Tabs, menus, breadcrumbs and when to use each",
        "minutes": 5,
        "skills": [
          "conventions",
          "layout"
        ],
        "exercises": [
          {
            "id": "i4-current-location",
            "type": "compare"
          },
          {
            "id": "i4-tabs-for-steps",
            "type": "choice"
          },
          {
            "id": "i4-spot-hidden-nav",
            "type": "spot"
          },
          {
            "id": "i4-sort-pattern",
            "type": "sort"
          }
        ]
      },
      {
        "id": "i5",
        "code": "I5",
        "title": "Progressive disclosure",
        "subtitle": "Show the basics, reveal the rest",
        "minutes": 5,
        "skills": [
          "effort",
          "layout"
        ],
        "exercises": [
          {
            "id": "i5-filters",
            "type": "compare"
          },
          {
            "id": "i5-hidden-fee",
            "type": "choice"
          },
          {
            "id": "i5-spot-vague-reveal",
            "type": "spot"
          },
          {
            "id": "i5-sort-compose",
            "type": "sort"
          }
        ]
      },
      {
        "id": "i6",
        "code": "I6",
        "title": "Modals, panels and inline",
        "subtitle": "Interrupt only when you must",
        "minutes": 5,
        "skills": [
          "control",
          "effort"
        ],
        "exercises": [
          {
            "id": "i6-rename",
            "type": "compare"
          },
          {
            "id": "i6-when-modal",
            "type": "choice"
          },
          {
            "id": "i6-spot-trap",
            "type": "spot"
          },
          {
            "id": "i6-sort-pattern",
            "type": "sort"
          }
        ]
      },
      {
        "id": "i7",
        "code": "I7",
        "title": "Motion with a purpose",
        "subtitle": "Animation that explains, not decorates",
        "minutes": 5,
        "skills": [
          "feedback",
          "accessibility"
        ],
        "exercises": [
          {
            "id": "i7-panel-speed",
            "type": "compare"
          },
          {
            "id": "i7-reduce-motion",
            "type": "choice"
          },
          {
            "id": "i7-spot-endless",
            "type": "spot"
          },
          {
            "id": "i7-sort-purpose",
            "type": "sort"
          }
        ]
      },
      {
        "id": "i8",
        "code": "I8",
        "title": "Touch, pointer and keyboard",
        "subtitle": "Design for fingers, mice and keyboards",
        "minutes": 5,
        "skills": [
          "control",
          "accessibility"
        ],
        "exercises": [
          {
            "id": "i8-swipe-delete",
            "type": "compare"
          },
          {
            "id": "i8-hover-actions",
            "type": "choice"
          },
          {
            "id": "i8-spot-tiny",
            "type": "spot"
          },
          {
            "id": "i8-sort-input",
            "type": "sort"
          }
        ]
      }
    ]
  }
];
