import { describe, expect, it } from "vitest";
import { manifest } from "./manifest";
import { paths } from "./paths";
import type { PathMeta } from "./types";

/** The catalog as it should be, built from the full path files. */
const expected: PathMeta[] = paths.map((p) => ({
  id: p.id,
  title: p.title,
  description: p.description,
  status: p.status,
  lessons: p.lessons.map((l) => ({
    id: l.id,
    code: l.code,
    title: l.title,
    subtitle: l.subtitle,
    minutes: l.minutes,
    skills: l.skills,
    exercises: l.exercises.map((e) => ({ id: e.id, type: e.type })),
  })),
}));

describe("content catalog (manifest.ts)", () => {
  // `npm run manifest` runs this file in "manifest" mode, which rewrites manifest.ts.
  if (import.meta.env.MODE === "manifest") {
    it("is regenerated", async () => {
      // Node's fs, loaded by name so the browser app's types don't need Node's.
      const fsModule: string = "node:fs";
      const { writeFileSync } = await import(/* @vite-ignore */ fsModule);
      const body = `// Generated by \`npm run manifest\` from src/content/paths. Don't edit by hand.\nimport type { PathMeta } from "./types";\n\nexport const manifest: PathMeta[] = ${JSON.stringify(expected, null, 2)};\n`;
      writeFileSync(new URL("./manifest.ts", import.meta.url), body);
    });
    return;
  }

  it("matches the lesson files (run `npm run manifest` after changing lessons)", () => {
    expect(manifest).toEqual(expected);
  });
});

describe("lesson loading", () => {
  it("can load every path in the catalog", async () => {
    const { loadablePathIds, loadPath } = await import("./load");
    expect(loadablePathIds).toEqual(paths.map((p) => p.id));
    for (const p of paths) expect((await loadPath(p.id)).lessons.map((l) => l.id)).toEqual(p.lessons.map((l) => l.id));
  });

  it("keeps full lessons out of the main download (app code never imports content/paths)", () => {
    const files = import.meta.glob(["../**/*.{ts,tsx}", "!../**/*.test.{ts,tsx}", "!./paths/**", "!./load.ts"], { query: "?raw", import: "default", eager: true }) as Record<string, string>;
    expect(Object.keys(files).length, "files scanned").toBeGreaterThan(30);
    const offenders = Object.entries(files)
      .filter(([, source]) => /from\s+["'](?:\.\.?\/)*(?:content\/)?paths["'/]/.test(source))
      .map(([file]) => file);
    expect(offenders).toEqual([]);
  });
});
