import type { Lesson, LearningPath } from "../types";

// Lessons summarize W3C WAI material in our own words and link to it (summarize-and-link only; no W3C text adapted).
const understanding = (slug: string, title: string) => ({
  title: `WCAG 2.2 Understanding: ${title}`,
  url: `https://www.w3.org/WAI/WCAG22/Understanding/${slug}.html`,
});

const lessons: Lesson[] = [
  {
    id: "a1",
    code: "A1",
    title: "Who accessibility is for",
    subtitle: "More people than you think, and the standard behind it",
    minutes: 5,
    skills: ["accessibility"],
    body: [
      "An accessible product works for people with disabilities: someone who is blind and uses a screen reader, someone who can't use a mouse, someone who zooms text to read it, relies on captions, or needs plain language to follow a task. About 1 in 6 people worldwide live with a significant disability, and most people gain one as they age.",
      "The same fixes help far more people: captions in a noisy office, strong contrast in bright sun, keyboard shortcuts for power users, a big tap target for a parent holding a phone in one hand. The international standard is WCAG, which groups its requirements under four principles: content must be perceivable, operable, understandable and robust. Many laws and public-sector rules, such as Section 508 in the US and EN 301 549 in Europe, are based on WCAG level AA.",
    ],
    practice: [
      "Treat accessibility as a design requirement from the first sketch, not a fix before launch.",
      "Aim for WCAG 2.2 level AA. Level A is the floor; AA is what most organizations and laws expect.",
      "Include disabled people in research. Checklists find many problems, but not whether a task actually works for someone.",
      "Learn the quick checks: keyboard only, zoom to 200%, and a contrast checker. They find a lot in a few minutes.",
    ],
    fieldExercise:
      "Put your mouse aside and try to finish one core task in your product with only the keyboard. Note every point where you got stuck or lost track of where you were.",
    sources: [
      { title: "W3C WAI: Introduction to Web Accessibility", url: "https://www.w3.org/WAI/fundamentals/accessibility-intro/" },
      { title: "W3C WAI: Diverse Abilities and Barriers", url: "https://www.w3.org/WAI/people-use-web/abilities-barriers/" },
      { title: "W3C WAI: WCAG 2 Overview", url: "https://www.w3.org/WAI/standards-guidelines/wcag/" },
    ],
    exercises: [
      {
        id: "a1-video-captions",
        type: "compare",
        question: "A company posts a safety training video for its warehouse staff. Which player serves them better?",
        a: `<div class="mk"><div class="mk-media">Video · 4:12</div><div class="mk-row"><span class="mk-btn sec">▶ Play</span><span class="mk-btn sec">CC Captions on</span><span class="mk-link">Read the transcript</span></div></div>`,
        b: `<div class="mk"><div class="mk-media">Video · 4:12</div><div class="mk-row"><span class="mk-btn sec">▶ Play</span><span class="mk-btn sec">CC Auto-captions: off</span></div></div>`,
        describe: {
          a: "A 4 minute 12 second video with a Play button, a Captions on button, and a Read the transcript link.",
          b: "A 4 minute 12 second video with a Play button and a button reading “CC Auto-captions: off”. There's no transcript.",
        },
        correct: "a",
        why: "A turns captions on and adds a transcript, so Deaf and hard-of-hearing staff, and anyone on a loud warehouse floor, can follow along or read at their own pace. B has captions, but they're generated automatically and off by default: they may get safety terms wrong, people have to find them first, and there's no transcript to search or reread.",
      },
      {
        id: "a1-who-benefits",
        type: "choice",
        question: "A stakeholder says, “Only a few of our users have disabilities, so accessibility can wait.” What's the strongest response?",
        options: [
          "Agree, and plan a separate accessible version of the site for a later release",
          "Say it's mainly a legal risk, since accessibility lawsuits have become common",
          "Explain that disability is common, often invisible, and the fixes help everyone",
          "Suggest an accessibility toolbar widget that lets visitors change colors and text size",
        ],
        correct: 2,
        why: "Disability is more common than teams assume, many people never disclose it, and the fixes also help someone with a broken wrist, an old phone or glare on the screen. A separate accessible version tends to fall behind the main site, and overlay widgets don't fix the underlying code. Legal risk is real, but leading with it frames accessibility as compliance rather than as serving users.",
      },
      {
        id: "a1-spot-no-captions",
        type: "spot",
        question: "This onboarding video is for every new employee. Which part leaves some of them out?",
        title: "Your first week",
        parts: [
          {
            id: "video",
            label: "Video player: Welcome to the team, 6 minutes 40 seconds",
            html: `<div class="mk-media">Video · Welcome to the team · 6:40</div>`,
          },
          {
            id: "controls",
            label: "Video controls: Play, Volume and Full screen buttons",
            html: `<div class="mk-row"><span class="mk-btn sec">▶ Play</span><span class="mk-btn sec">Volume</span><span class="mk-btn sec">Full screen</span></div>`,
          },
          {
            id: "questions",
            label: "Text: Questions? Ask your manager.",
            html: `<div class="mk-muted">Questions? Ask your manager.</div>`,
          },
        ],
        correct: "controls",
        why: "There's no captions button and no transcript, so Deaf and hard-of-hearing employees miss the content, as does anyone watching in a noisy office or without sound. Captions and a transcript fix that. The video itself and the note about questions are fine.",
      },
      {
        id: "a1-sort-who",
        type: "sort",
        question: "Accessibility helps people with permanent disabilities and many others. Which of these situations are permanent, and which are temporary or situational?",
        groups: ["Permanent", "Temporary or situational"],
        items: [
          { id: "blind", text: "A blind person who uses a screen reader", group: 0 },
          { id: "deaf", text: "A Deaf person who watches videos with captions", group: 0 },
          { id: "arm", text: "Someone born with one arm", group: 0 },
          { id: "cast", text: "Someone with a broken wrist in a cast", group: 1 },
          { id: "baby", text: "A parent holding a baby in one arm", group: 1 },
          { id: "sun", text: "Someone reading their phone in bright sunlight", group: 1 },
        ],
        why: "The same design choices serve all of these people: good contrast helps someone with low vision and someone squinting in the sun, and one-handed use helps someone with one arm, a cast or a baby on their hip. That's why accessibility isn't an edge case: at some point, almost everyone benefits from it.",
      },
    ],
  },
  {
    id: "a2",
    code: "A2",
    title: "Text alternatives",
    subtitle: "Describe images by their purpose",
    minutes: 5,
    skills: ["accessibility", "language"],
    body: [
      "Screen readers can't see images. They read the image's alt text instead, and when there is none they often read the file name. Good alt text gives the same information or function the image gives a sighted person, in a short phrase.",
      "What to write depends on why the image is there. A photo that only adds mood gets empty alt text (alt=\"\") so screen readers skip it. An icon that works as a button needs a name for the action, not a description of the drawing. A chart needs its main point in the text alternative, with the full data available nearby.",
    ],
    practice: [
      "Ask yourself what you'd say about the image if you were reading the page aloud over the phone, and write that.",
      "Don't start with “Image of” or “Picture of”. Screen readers already announce that it's an image.",
      "Name the function of linked images and icon buttons: “Search”, not “Magnifying glass”.",
      "Give decorative images empty alt text, and don't put important text inside images.",
    ],
    fieldExercise:
      "Turn on your computer's screen reader (VoiceOver on Mac, Narrator on Windows) and move through one page of your product. Write down every image or icon announced as a file name, as “unlabeled”, or not at all when it carries meaning.",
    sources: [
      { title: "W3C WAI: Images Tutorial", url: "https://www.w3.org/WAI/tutorials/images/" },
      { title: "W3C WAI: An alt Decision Tree", url: "https://www.w3.org/WAI/tutorials/images/decision-tree/" },
    ],
    exercises: [
      {
        id: "a2-icon-button",
        type: "compare",
        question: "An icon-only button deletes an invoice. The box shows what a screen reader announces when the button gets focus. Which is better?",
        a: `<div class="mk"><div class="mk-row"><span>INV-2041 · Northwind Supply · $1,200</span><span class="mk-btn sec">🗑</span></div><div class="mk-say"><b>Screen reader</b>“Delete, button”</div></div>`,
        b: `<div class="mk"><div class="mk-row"><span>INV-2041 · Northwind Supply · $1,200</span><span class="mk-btn sec">🗑</span></div><div class="mk-say"><b>Screen reader</b>“Delete invoice INV-2041, button”</div></div>`,
        describe: {
          a: "An invoice row, INV-2041, Northwind Supply, $1,200, with a trash can icon button. A screen reader announces: Delete, button.",
          b: "An invoice row, INV-2041, Northwind Supply, $1,200, with a trash can icon button. A screen reader announces: Delete invoice INV-2041, button.",
        },
        correct: "b",
        why: "Both name the action, but B also says which invoice. In a table of invoices, every row's button in A is announced as just “Delete”, so someone moving from button to button can't tell which one deletes INV-2041 without going back to read the row.",
      },
      {
        id: "a2-decorative",
        type: "choice",
        question: "A sign-in page has a large stock photo of colleagues smiling at a laptop. It sets a mood but carries no information. What alt text should it have?",
        options: [
          "“Image of three colleagues smiling at a laptop in a bright office”",
          "Empty alt text (alt=\"\"), so screen readers skip it",
          "No alt attribute at all",
          "“Sign in to your account”",
        ],
        correct: 1,
        why: "Empty alt text tells screen readers the image is decorative, so people reach the sign-in form sooner. A description makes everyone listen to something that adds nothing. Leaving out the attribute is worse: many screen readers then read the file name. Repeating the page title duplicates the heading.",
      },
      {
        id: "a2-spot-logo-filename",
        type: "spot",
        question: "A screen reader user is shopping. The boxes show what their screen reader announces. Which part fails them?",
        title: "Ceramic mug",
        parts: [
          {
            id: "logo",
            label: "Logo image. Screen reader says: logo_final_v2.png, link",
            html: `<div class="mk-say"><b>Screen reader</b>“logo_final_v2.png, link”</div>`,
          },
          {
            id: "photo",
            label: "Product photo. Screen reader says: Blue ceramic mug with a curved handle, 350 ml",
            html: `<div class="mk-say"><b>Screen reader</b>“Blue ceramic mug with a curved handle, 350 ml”</div>`,
          },
          {
            id: "price",
            label: "Price: $18",
            html: `<div class="mk-big">$18</div>`,
          },
          {
            id: "add",
            label: "Button: Add to cart",
            html: `<span class="mk-btn">Add to cart</span>`,
          },
        ],
        correct: "logo",
        why: "The logo is a link to the home page, so its text alternative should name the company or say “Home”, not read out a file name. The product photo's alt text is a good example: it describes what a sighted shopper would learn from the picture.",
      },
      {
        id: "a2-sort-alt",
        type: "sort",
        question: "Which images need alt text, and which are decorative and should have empty alt text?",
        groups: ["Needs alt text", "Decorative"],
        items: [
          { id: "product", text: "A product photo in an online store", group: 0 },
          { id: "chart", text: "A chart showing sales over the year", group: 0 },
          { id: "logo", text: "A logo that links to the home page", group: 0 },
          { id: "swirl", text: "A decorative swirl behind a heading", group: 1 },
          { id: "icon", text: "A gear icon next to the word “Settings” in a button", group: 1 },
          { id: "stock", text: "A stock photo of smiling people that adds no information", group: 1 },
        ],
        why: "Images that carry information or act as links need text that gives that information or says where the link goes, like the product, the chart's trend, or “Home”. Decorative images should have empty alt text so screen readers skip them. The gear icon is the tricky one: the button already says “Settings”, so describing the icon too would just repeat it.",
      },
    ],
  },
  {
    id: "a3",
    code: "A3",
    title: "Color contrast",
    subtitle: "Text people can actually read",
    minutes: 5,
    skills: ["accessibility", "layout"],
    body: [
      "Low-contrast text is the most common accessibility problem found on websites, and it affects far more than people with low vision. Pale gray text on white is hard to read on a cheap monitor, outdoors, or late in the day with tired eyes.",
      "WCAG measures contrast as a ratio between text and its background, from 1:1 (no contrast) to 21:1 (black on white). Level AA asks for at least 4.5:1 for normal text and 3:1 for large text (about 24px, or about 19px bold). Icons, input borders and focus indicators that people need in order to use the interface need 3:1 against what's around them.",
    ],
    practice: [
      "Check every text and background pair with a contrast checker, including text on brand colors and on images.",
      "Watch light gray helper text, placeholder text and text over photos. They fail most often.",
      "Build passing pairs into your design tokens, so every team gets readable text by default.",
      "Check light and dark themes separately. A pair that passes in one often fails in the other.",
    ],
    fieldExercise:
      "Put the text colors from your product's main screen into a contrast checker, such as WebAIM's, and list every pair below 4.5:1.",
    sources: [
      understanding("contrast-minimum", "Contrast (Minimum)"),
      understanding("non-text-contrast", "Non-text Contrast"),
      { title: "WebAIM: Contrast Checker", url: "https://webaim.org/resources/contrastchecker/" },
    ],
    exercises: [
      {
        id: "a3-helper-text",
        type: "compare",
        question: "Which form hint will more people be able to read?",
        a: `<div class="mk"><div class="mk-label">Employee ID</div><div class="mk-in">&nbsp;</div><div class="mk-faint">Printed under the photo on your badge, for example E-10442</div></div>`,
        b: `<div class="mk"><div class="mk-label">Employee ID</div><div class="mk-in">&nbsp;</div><div class="mk-muted">Printed under the photo on your badge, for example E-10442</div></div>`,
        describe: {
          a: "An Employee ID field. The hint below it, “Printed under the photo on your badge, for example E-10442”, is very pale gray text on white.",
          b: "An Employee ID field. The hint below it, “Printed under the photo on your badge, for example E-10442”, is medium-dark gray text on white.",
        },
        correct: "b",
        why: "B's gray is dark enough to pass the 4.5:1 minimum. A's pale gray falls well below it, so people with low vision, screen glare or an older display may not be able to read the one line that tells them where to find their ID.",
      },
      {
        id: "a3-ratio",
        type: "choice",
        question: "Body text in your app is 16px regular weight. What's the minimum contrast ratio against its background for WCAG level AA?",
        options: ["3:1", "7:1", "4.5:1", "There is no minimum if the typeface is legible"],
        correct: 2,
        why: "Normal-size text needs 4.5:1 at level AA. 3:1 applies only to large text (about 24px, or 19px bold) and to interface parts such as icons and borders. 7:1 is the stricter AAA level. A legible typeface doesn't change the requirement.",
      },
      {
        id: "a3-spot-contrast-ratios",
        type: "spot",
        question: "Each part shows its measured contrast ratio. Which one fails WCAG level AA?",
        title: "Monthly report",
        parts: [
          {
            id: "heading",
            label: "Large bold heading: Monthly report. Contrast 12.6:1",
            html: `<div class="mk-row"><span class="mk-title">Monthly report</span><span class="mk-pill">12.6:1</span></div>`,
          },
          {
            id: "total",
            label: "Large bold number, about 32 pixels: $84,200. Contrast 3.6:1",
            html: `<div class="mk-row"><span class="mk-big">$84,200</span><span class="mk-pill">3.6:1 · large text</span></div>`,
          },
          {
            id: "body",
            label: "Body text, 16 pixels: Revenue grew 8% in September. Contrast 9.1:1",
            html: `<div class="mk-row"><span>Revenue grew 8% in September.</span><span class="mk-pill">9.1:1</span></div>`,
          },
          {
            id: "note",
            label: "Body text, 16 pixels: Figures exclude refunds. Contrast 3.2:1",
            html: `<div class="mk-row"><span>Figures exclude refunds.</span><span class="mk-pill">3.2:1 · 16px</span></div>`,
          },
        ],
        correct: "note",
        why: "Normal-size text needs at least 4.5:1, and this note has 3.2:1. The large $84,200 only needs 3:1 because it's large text, so its 3.6:1 passes. The heading and body text pass easily.",
      },
      {
        id: "a3-sort-ratio",
        type: "sort",
        question: "Under WCAG, which elements need a contrast ratio of at least 4.5:1, and which need at least 3:1?",
        groups: ["At least 4.5:1", "At least 3:1"],
        items: [
          { id: "body", text: "16px body text", group: 0 },
          { id: "caption", text: "A 12px caption under a photo", group: 0 },
          { id: "placeholder", text: "Hint text under a form field", group: 0 },
          { id: "heading", text: "A 32px page heading", group: 1 },
          { id: "icon", text: "The icon in an icon-only button", group: 1 },
          { id: "border", text: "The border that shows where a text field is", group: 1 },
        ],
        why: "Normal-size text needs 4.5:1, because small letters are harder to make out. Large text, about 24px, or 19px bold, and up, needs 3:1, as do the parts of controls and graphics people need to see, like icons and input borders. Hint text is the one teams most often make too pale: it's normal-size text, so it needs 4.5:1 too.",
      },
    ],
  },
  {
    id: "a4",
    code: "A4",
    title: "Don't rely on color alone",
    subtitle: "Always add a second cue",
    minutes: 4,
    skills: ["accessibility", "layout"],
    body: [
      "About 1 in 12 men and 1 in 200 women have some form of color vision deficiency, most often trouble telling red from green. Screen reader users get no color at all. If color is the only thing that separates two states, some people can't tell them apart.",
      "Color is still useful. The rule is to pair it with something else, such as text, an icon, a pattern, position or an underline. Then color speeds things up for people who can see it, and nobody depends on it.",
    ],
    practice: [
      "Give every status a word or icon as well as a color: “Failed”, not only a red dot.",
      "Underline links in body text, or set them apart in some way besides color.",
      "Show form errors with a message and an icon, not only a red border.",
      "Label chart lines directly or use different line styles instead of a color-only legend.",
    ],
    fieldExercise:
      "Take a screenshot of a dashboard or status page in your product and convert it to grayscale. Check that every status, chart series and error is still clear.",
    sources: [understanding("use-of-color", "Use of Color")],
    exercises: [
      {
        id: "a4-status-dots",
        type: "compare",
        question: "A dashboard shows the state of each server. Which version works for everyone?",
        a: `<div class="mk"><div class="mk-title">Servers</div><div class="mk-row"><span class="mk-dot good"></span><span>api-01</span><span class="mk-muted">Running</span></div><div class="mk-row"><span class="mk-dot bad"></span><span>api-02</span><span class="mk-muted">Down since 09:14</span></div><div class="mk-row"><span class="mk-dot warn"></span><span>db-01</span><span class="mk-muted">Slow responses</span></div></div>`,
        b: `<div class="mk"><div class="mk-title">Servers</div><div class="mk-row"><span class="mk-dot good"></span><span class="mk-muted">Running</span><span class="mk-dot bad"></span><span class="mk-muted">Down</span><span class="mk-dot warn"></span><span class="mk-muted">Slow</span></div><div class="mk-row"><span class="mk-dot good"></span><span>api-01</span></div><div class="mk-row"><span class="mk-dot bad"></span><span>api-02</span></div><div class="mk-row"><span class="mk-dot warn"></span><span>db-01</span></div></div>`,
        describe: {
          a: "A Servers list. api-01: green dot, Running. api-02: red dot, Down since 09:14. db-01: amber dot, Slow responses.",
          b: "A Servers list with a key at the top: green dot, Running; red dot, Down; amber dot, Slow. Below: api-01 with a green dot, api-02 with a red dot and db-01 with an amber dot.",
        },
        correct: "a",
        why: "A writes each server's state next to its dot. B adds a key, which helps, but people still have to tell red, green and amber apart to match each dot to it, which many color-blind people can't do, and a screen reader announces nothing for the dots in the list.",
      },
      {
        id: "a4-required-fields",
        type: "choice",
        question: "A form shows required field labels in red, with a note at the top: “Fields in red are required.” What's the best fix?",
        options: [
          "Use a brighter red so the required labels stand out more against the page",
          "Explain the red labels in a tooltip next to the form title",
          "Switch the required color to green, which is easier to tell apart from black text",
          "Add “(required)” to those labels, or “(optional)” to the others",
        ],
        correct: 3,
        why: "Words in the label work for everyone, including screen reader users, who hear them with the field name. A brighter red or a different color still relies on color alone, and a tooltip hides the explanation where few people will find it.",
      },
      {
        id: "a4-spot-red-border-only",
        type: "spot",
        question: "This form was submitted with problems. Which part relies on color alone?",
        title: "Create an account",
        parts: [
          {
            id: "name",
            label: "Field labeled Name, with a green border and the text Looks good",
            html: `<div class="mk-label">Name</div><div class="mk-in" style="border-color:var(--good)">Priya Shah</div><div class="mk-up">✓ Looks good</div>`,
          },
          {
            id: "email",
            label: "Field labeled Email, with a red border and no message",
            html: `<div class="mk-label">Email</div><div class="mk-in err">priya.shah@</div>`,
          },
          {
            id: "password",
            label: "Field labeled Password, with a red border and the message Use at least 12 characters",
            html: `<div class="mk-label">Password</div><div class="mk-err">⚠ Use at least 12 characters</div><div class="mk-in err">••••••</div>`,
          },
          {
            id: "submit",
            label: "Button: Create account",
            html: `<span class="mk-btn">Create account</span>`,
          },
        ],
        correct: "email",
        why: "The email field signals its error only with a red border, which many color-blind people can't see and screen readers don't announce. It needs a message in words, like the password field has: an icon and text that say what's wrong and how to fix it.",
      },
      {
        id: "a4-sort-color",
        type: "sort",
        question: "Which designs rely on color alone, and which also use text or shape?",
        groups: ["Color alone", "Also text or shape"],
        items: [
          { id: "dots", text: "Server status shown as red and green dots, with no labels", group: 0 },
          { id: "required", text: "Required fields shown only by red label text", group: 0 },
          { id: "links", text: "Links in a paragraph shown only in blue, without underlines", group: 0 },
          { id: "error", text: "A field with a red border and the message “Enter your email address”", group: 1 },
          { id: "chart", text: "Chart lines in different colors, each with a different dash pattern and a label", group: 1 },
          { id: "badge", text: "An “Overdue” badge in red with the word Overdue on it", group: 1 },
        ],
        why: "The first three only work if you can tell the colors apart, which many color-blind people can't, and they say nothing to screen readers. The others repeat the meaning in words or patterns, so color is a helpful extra rather than the only signal. Links are the easiest to miss: in body text they need an underline or another visible cue as well as color.",
      },
    ],
  },
  {
    id: "a5",
    code: "A5",
    title: "Keyboard access and visible focus",
    subtitle: "Everything works without a mouse",
    minutes: 5,
    skills: ["accessibility", "control"],
    body: [
      "Many people don't use a mouse: people with tremors or limited hand movement, blind people using screen readers, people using switch devices or voice control, and power users who prefer shortcuts. They all rely on the keyboard or on tools that act like one. Every link, button, field and menu must be reachable and usable with Tab, Shift+Tab, Enter, Space and the arrow keys.",
      "Keyboard users also need to see where they are. The focus indicator, usually an outline, does the job of their mouse pointer. Removing it with CSS (outline: none) and not replacing it leaves people guessing which control will respond when they press Enter.",
    ],
    practice: [
      "Use real button and link elements. A clickable div can't be reached with Tab or triggered with Enter unless you rebuild all of that by hand.",
      "Keep the focus order the same as the visual reading order.",
      "Design the focus style on purpose: a thick outline with strong contrast, checked in every theme.",
      "Make sure people can leave every dialog, menu and widget with the keyboard. Esc should close overlays.",
    ],
    fieldExercise:
      "Tab through your product's sign-up or checkout flow. Count every time you lose sight of the focus or can't reach or operate a control.",
    sources: [
      understanding("keyboard", "Keyboard"),
      understanding("focus-visible", "Focus Visible"),
      { title: "W3C WAI: Keyboard Compatibility (video)", url: "https://www.w3.org/WAI/perspective-videos/keyboard/" },
    ],
    exercises: [
      {
        id: "a5-focus-visible",
        type: "compare",
        question: "Someone is tabbing through a report page, and keyboard focus is on the Export button. Which design lets them see that?",
        a: `<div class="mk"><div class="mk-title">Q3 headcount report</div><div class="mk-row"><span class="mk-btn sec">Filter</span><span class="mk-btn sec" style="color:var(--accent)">Export</span><span class="mk-btn sec">Share</span></div><div class="mk-muted">Keyboard focus: Export</div></div>`,
        b: `<div class="mk"><div class="mk-title">Q3 headcount report</div><div class="mk-row"><span class="mk-btn sec">Filter</span><span class="mk-btn sec mk-focus">Export</span><span class="mk-btn sec">Share</span></div><div class="mk-muted">Keyboard focus: Export</div></div>`,
        describe: {
          a: "A report page with Filter, Export and Share buttons. Keyboard focus is on Export, shown only by its text turning blue, with no outline.",
          b: "A report page with Filter, Export and Share buttons. Keyboard focus is on Export, which has a thick colored outline around it.",
        },
        correct: "b",
        why: "B draws a thick outline around the focused button, so it's easy to spot at a glance. In A, focus is shown only by a change in text color, which is easy to miss, especially for people with low vision or who can't tell the colors apart, so they lose track of where they are.",
      },
      {
        id: "a5-div-button",
        type: "choice",
        question: "A developer built a custom “Approve” control from a styled div with a click handler. Mouse users like it. What's the most likely problem?",
        options: [
          "Keyboard and screen reader users can't reach or use it as a button",
          "It looks slightly different from the other buttons in the app, which breaks consistency",
          "It loads more slowly than a native button because of the extra script it needs",
          "Nothing, as long as it has a clear hover state and a pointer cursor",
        ],
        correct: 0,
        why: "A native button comes with keyboard focus, Enter and Space activation, and the button role for free. A div has none of these, so each must be added by hand, and teams often miss one. Switching to a button element is the simpler fix. A hover state only helps mouse users. Looking slightly different or loading a little more script are minor next to people who can't use the control at all.",
      },
      {
        id: "a5-spot-keyboard-trap",
        type: "spot",
        question: "These are the results of testing a form with only the keyboard. Which part fails keyboard users?",
        title: "New task",
        parts: [
          {
            id: "title",
            label: "Text field: Title. Keyboard test: reached with Tab, typing works",
            html: `<div class="mk-label">Title</div><div class="mk-in">&nbsp;</div><div class="mk-muted">Tab ✓ · typing ✓</div>`,
          },
          {
            id: "priority",
            label: "Custom dropdown: Priority. Keyboard test: skipped by Tab, Enter does nothing",
            html: `<div class="mk-label">Priority</div><div class="mk-in">Normal ▾</div><div class="mk-muted">Tab ✗ skipped · Enter ✗</div>`,
          },
          {
            id: "details",
            label: "Link: View details. Keyboard test: reached with Tab, Enter opens it",
            html: `<span class="mk-link">View details</span><div class="mk-muted">Tab ✓ · Enter ✓</div>`,
          },
          {
            id: "save",
            label: "Button: Save. Keyboard test: reached with Tab, Enter and Space work",
            html: `<span class="mk-btn">Save</span><div class="mk-muted">Tab ✓ · Enter ✓ · Space ✓</div>`,
          },
        ],
        correct: "priority",
        why: "Keyboard users can't reach the Priority dropdown or open it, so they can't set a priority at all. Custom controls need focus and key handling, or better, a native select element that comes with both. The other controls pass the test.",
      },
      {
        id: "a5-sort-keyboard",
        type: "sort",
        question: "Which controls work with a keyboard as built, and which only work with a mouse?",
        groups: ["Works with keyboard", "Mouse only"],
        items: [
          { id: "button", text: "A standard button element", group: 0 },
          { id: "link", text: "A link with a real destination", group: 0 },
          { id: "select", text: "A standard select dropdown", group: 0 },
          { id: "div", text: "A div with a click handler and nothing else", group: 1 },
          { id: "hover", text: "A menu that only opens when you hover over it", group: 1 },
          { id: "drag", text: "Reordering a list only by dragging", group: 1 },
        ],
        why: "Native buttons, links and selects can be reached with Tab and used with Enter, Space or the arrow keys out of the box. A clickable div isn't focusable or announced as a control, a hover-only menu never opens without a mouse, and drag-only reordering needs another way, such as Move up and Move down buttons. Using native elements is the cheapest way to get keyboard access right.",
      },
    ],
  },
  {
    id: "a6",
    code: "A6",
    title: "Headings and page structure",
    subtitle: "Let people skim with a screen reader",
    minutes: 5,
    skills: ["accessibility", "layout"],
    body: [
      "Sighted people skim a page by its layout: big bold headings, a sidebar, a footer. Screen reader users skim too, by jumping from heading to heading or from region to region. That only works when the structure is in the code: real heading elements in a sensible order, and landmark regions such as header, nav, main and footer.",
      "Text that only looks like a heading, such as a bold paragraph styled large, is invisible to that kind of navigation. Headings that skip levels or are picked for their size make the outline confusing, like a table of contents with random numbering.",
    ],
    practice: [
      "Give each page one h1 that says what the page is, then use h2 for main sections and h3 inside them.",
      "Choose heading levels for structure, and set their size with CSS.",
      "Wrap the main regions of the page in header, nav, main and footer elements.",
      "On pages with long navigation, make a “Skip to main content” link the first thing keyboard users reach.",
    ],
    fieldExercise:
      "Use a heading outline browser extension (HeadingsMap is one) on a page of your product. Check that the outline reads like a sensible table of contents, with no skipped levels or missing sections.",
    sources: [
      { title: "W3C WAI: Page Structure Tutorial", url: "https://www.w3.org/WAI/tutorials/page-structure/" },
      understanding("info-and-relationships", "Info and Relationships"),
    ],
    exercises: [
      {
        id: "a6-heading-outline",
        type: "compare",
        question: "Two builds of the same settings page look identical. The box shows what a screen reader user gets when they ask for a list of headings. Which is better?",
        a: `<div class="mk"><div class="mk-big">Account settings</div><div class="mk-title">Profile</div><div class="mk-title">Notifications</div><div class="mk-title">Billing</div><div class="mk-say"><b>Headings list</b>H1 Account settings<br>H4 Profile<br>H4 Notifications<br>H4 Billing</div></div>`,
        b: `<div class="mk"><div class="mk-big">Account settings</div><div class="mk-title">Profile</div><div class="mk-title">Notifications</div><div class="mk-title">Billing</div><div class="mk-say"><b>Headings list</b>H1 Account settings<br>H2 Profile<br>H2 Notifications<br>H2 Billing</div></div>`,
        describe: {
          a: "A settings page with big bold text, Account settings, then Profile, Notifications and Billing. A screen reader's headings list shows: level 1, Account settings; level 4, Profile, Notifications and Billing.",
          b: "A settings page with big bold text, Account settings, then Profile, Notifications and Billing. A screen reader's headings list shows: level 1, Account settings; level 2, Profile, Notifications and Billing.",
        },
        correct: "b",
        why: "Both builds use real headings, so screen reader users can jump to Billing in either. But A goes straight from level 1 to level 4, likely because the team wanted a smaller default size, so the outline suggests sections are missing in between. B uses level 2 for the sections, which matches the page, and sets the size with CSS.",
      },
      {
        id: "a6-heading-level",
        type: "choice",
        question: "A designer wants a small sidebar heading and asks for an h5, because h5 is the right size. The page has one h1 and no other headings yet. What's the better approach?",
        options: [
          "Use h5, since its default size is the closest visual match to the design",
          "Use a bold paragraph instead, so it doesn't affect the page outline at all",
          "Use the level that fits the structure (h2) and resize it with CSS",
          "Use a second h1 so screen reader users find this section first",
        ],
        correct: 2,
        why: "Heading levels describe the outline, and CSS controls their size. An h5 straight after the h1 tells screen reader users that sections are missing. A bold paragraph removes the heading from navigation entirely, and a second h1 blurs what the page is about.",
      },
      {
        id: "a6-spot-skipped-level",
        type: "spot",
        question: "This is the heading outline of a billing page. Which heading breaks the structure?",
        title: "Billing",
        parts: [
          {
            id: "h1",
            label: "Heading level 1: Billing",
            html: `<div class="mk-row"><span class="mk-pill">H1</span><span class="mk-title">Billing</span></div>`,
          },
          {
            id: "h2a",
            label: "Heading level 2: Payment method",
            html: `<div class="mk-row"><span class="mk-pill">H2</span><span>Payment method</span></div>`,
          },
          {
            id: "h4",
            label: "Heading level 4: Card details",
            html: `<div class="mk-row" style="padding-left:24px"><span class="mk-pill">H4</span><span>Card details</span></div>`,
          },
          {
            id: "h2b",
            label: "Heading level 2: Invoices",
            html: `<div class="mk-row"><span class="mk-pill">H2</span><span>Invoices</span></div>`,
          },
        ],
        correct: "h4",
        why: "Card details jumps from level 2 straight to level 4, so screen reader users hear that a level is missing and wonder what they skipped. It should be an h3 under Payment method, styled smaller with CSS if needed. The rest of the outline is in order.",
      },
      {
        id: "a6-sort-headings",
        type: "sort",
        question: "On an account settings page, which text should be marked up as a heading, and which shouldn't?",
        groups: ["A heading", "Not a heading"],
        items: [
          { id: "title", text: "The page title, Account settings", group: 0 },
          { id: "billing", text: "The section title Billing", group: 0 },
          { id: "notifications", text: "The section title Notifications", group: 0 },
          { id: "bold", text: "A bold sentence for emphasis inside a paragraph", group: 1 },
          { id: "label", text: "The label above the Email field", group: 1 },
          { id: "quote", text: "A large pull quote from a customer", group: 1 },
        ],
        why: "Headings mark the start of sections, so screen reader users can list them and jump straight to the part they need. Emphasis, form labels and decorative quotes aren't the start of a section. Marking them as headings would clutter that list and make the page harder to navigate. Size or boldness alone doesn't make something a heading.",
      },
    ],
  },
  {
    id: "a7",
    code: "A7",
    title: "Accessible forms",
    subtitle: "Labels, hints and errors everyone gets",
    minutes: 5,
    skills: ["accessibility", "forms"],
    body: [
      "Every field needs a visible label that stays in place, connected to the field in code so screen readers announce it when the field gets focus. Placeholder text is not a label: it disappears as soon as someone types, it's usually too pale to read, and not every screen reader announces it.",
      "When something goes wrong, say what the problem is and how to fix it, in text next to the field. Then make sure screen reader users find out, by moving focus to an error summary or announcing the error. A red border on its own, or a single message at the top of a long page, is easy to miss.",
    ],
    practice: [
      "Put the label above the field and connect the two in code, with matching for and id attributes or by wrapping the field in its label.",
      "Show format hints, like “MM/YY”, as visible text linked to the field rather than as placeholder text.",
      "Write errors that name the field and the fix: “Enter an expiry date in the future”, not “Invalid input”.",
      "Group related radio buttons and checkboxes with a fieldset and legend, so the question is read with each option.",
    ],
    fieldExercise:
      "Click each label in one of your product's forms. If clicking a label doesn't put the cursor in its field, the label probably isn't connected in code.",
    sources: [
      { title: "W3C WAI: Forms Tutorial", url: "https://www.w3.org/WAI/tutorials/forms/" },
      understanding("error-identification", "Error Identification"),
    ],
    exercises: [
      {
        id: "a7-placeholder-label",
        type: "compare",
        question: "Someone has started typing a card number. Which design still tells them what each field is for?",
        a: `<div class="mk"><div class="mk-label">Card number</div><div class="mk-in">4111 1111</div><div class="mk-label">Expiry date</div><div class="mk-muted">For example, 04/29</div><div class="mk-in">&nbsp;</div></div>`,
        b: `<div class="mk"><div class="mk-in">4111 1111</div><div class="mk-in"><span class="mk-faint">Expiry date (MM/YY)</span></div></div>`,
        describe: {
          a: "A field labeled Card number containing 4111 1111. Then an empty field labeled Expiry date, with the hint “For example, 04/29” above it.",
          b: "Two fields with no labels above them. The first contains 4111 1111. The second is empty except for pale placeholder text inside it: Expiry date (MM/YY).",
        },
        correct: "a",
        why: "A's labels and hint stay visible while people type and when they come back to check their answers. In B the first placeholder vanished once typing began, so people must delete their input to see what was asked, and the pale placeholder in the second field is hard to read.",
      },
      {
        id: "a7-error-message",
        type: "choice",
        question: "A date of birth field fails validation because the date is in the future. Which error is best?",
        options: [
          "“Error: the value in this field is not valid”",
          "“Invalid input in field 3. Please check and try again”",
          "A red border around the field, with no message at all",
          "“Date of birth must be in the past, like 14 03 1990”",
        ],
        correct: 3,
        why: "It names the field, says what's wrong and shows how to fix it, in text a screen reader can announce. “Error” and “field 3” leave people hunting for the problem, and a red border alone is invisible to screen reader users and hard to see for people with color blindness.",
      },
      {
        id: "a7-spot-placeholder",
        type: "spot",
        question: "Which field will people struggle with once they start typing?",
        title: "Create your account",
        parts: [
          {
            id: "name",
            label: "Field labeled Full name, with Ana Silva typed in",
            html: `<div class="mk-label">Full name</div><div class="mk-in">Ana Silva</div>`,
          },
          {
            id: "email",
            label: "Field with no label above it. Gray text inside reads Email address",
            html: `<div class="mk-in"><span class="mk-muted">Email address</span></div>`,
          },
          {
            id: "password",
            label: "Field labeled Password, with the hint At least 12 characters",
            html: `<div class="mk-label">Password</div><div class="mk-muted">At least 12 characters</div><div class="mk-in">&nbsp;</div>`,
          },
          {
            id: "submit",
            label: "Button: Create account",
            html: `<span class="mk-btn">Create account</span>`,
          },
        ],
        correct: "email",
        why: "The email field has no label, only placeholder text inside it. As soon as someone types, the only clue to what the field is for disappears, and some screen readers don't announce placeholders at all. The other fields keep a visible label above the input.",
      },
      {
        id: "a7-sort-forms",
        type: "sort",
        question: "Which form design choices help everyone, and which create a barrier?",
        groups: ["Helps everyone", "Creates a barrier"],
        items: [
          { id: "label", text: "A visible label above each field", group: 0 },
          { id: "hint", text: "Hints that stay visible while people type", group: 0 },
          { id: "fieldset", text: "Day, month and year fields grouped under the question “Date of birth”", group: 0 },
          { id: "placeholder", text: "Placeholder text as the only label", group: 1 },
          { id: "captcha", text: "A puzzle that asks you to pick the images with traffic lights, with no other option", group: 1 },
          { id: "timer", text: "A form that times out after 2 minutes with no warning", group: 1 },
        ],
        why: "Visible labels and hints, and grouping related fields under one question, make forms clear for screen reader users and everyone else. Placeholder-only labels vanish while typing, an image puzzle with no alternative blocks blind users, and a short timeout without warning shuts out anyone who types slowly or uses assistive technology. The timeout is easy to forget because it's invisible until it happens.",
      },
    ],
  },
  {
    id: "a8",
    code: "A8",
    title: "Links, buttons and targets",
    subtitle: "Clear names and room to tap",
    minutes: 5,
    skills: ["accessibility", "language"],
    body: [
      "Screen reader users often bring up a list of every link or button on a page. In that list, ten links called “Read more” are useless. Each link and button should make sense on its own, or at least together with its sentence or table row.",
      "Controls also need to be big enough to hit. People with tremors, people on a bumpy train and anyone using a phone with one thumb all miss small targets. WCAG 2.2 level AA asks for targets of at least 24 by 24 CSS pixels, or enough space around smaller ones. Apple and Google recommend about 44 to 48 for touch.",
    ],
    practice: [
      "Write link text that says where it goes: “Download the 2026 benefits guide (PDF, 2 MB)”, not “Click here”.",
      "Use links to go somewhere and buttons to do something. Screen readers announce them differently, and people expect different behavior.",
      "Make sure a control's visible text is part of its accessible name, so voice control users can say what they see.",
      "Give small icons a larger tap area with padding, and keep destructive actions away from frequent ones.",
    ],
    fieldExercise:
      "On your phone, try to complete a task in your product using only the thumb of your non-dominant hand. Note every target you miss or hit by accident.",
    sources: [
      understanding("link-purpose-in-context", "Link Purpose (In Context)"),
      understanding("target-size-minimum", "Target Size (Minimum)"),
      understanding("label-in-name", "Label in Name"),
    ],
    exercises: [
      {
        id: "a8-link-text",
        type: "compare",
        question: "An intranet home page lists news stories. The box shows a screen reader's list of links. Which works better?",
        a: `<div class="mk"><div class="mk-title">News</div><div class="mk-link">Office closed on Monday, October 12</div><div class="mk-link">New travel expense policy</div><div class="mk-link">Parking garage repairs schedule</div><div class="mk-say"><b>Links list</b>Office closed on Monday, October 12<br>New travel expense policy<br>Parking garage repairs schedule</div></div>`,
        b: `<div class="mk"><div class="mk-title">News</div><div>Office closed on Monday, October 12 <span class="mk-link">Read more</span></div><div>New travel expense policy <span class="mk-link">Read more</span></div><div>Parking garage repairs schedule <span class="mk-link">Read more</span></div><div class="mk-say"><b>Links list</b>Read more<br>Read more<br>Read more</div></div>`,
        describe: {
          a: "A news list where each headline is itself a link. A screen reader's links list reads: Office closed on Monday, October 12; New travel expense policy; Parking garage repairs schedule.",
          b: "A news list of three headlines, each followed by a Read more link. A screen reader's links list reads: Read more, Read more, Read more.",
        },
        correct: "a",
        why: "A's links name their destinations, so someone scanning the links list can pick the story they want. In B every link is announced as “Read more”, so people have to leave the list and read around each link to learn where it goes.",
      },
      {
        id: "a8-target-size",
        type: "choice",
        question: "A data table puts Edit and Delete icons 2px apart, each 14px square. People on tablets keep deleting the wrong row. What's the best fix?",
        options: [
          "Add a confirmation dialog to Delete, so a mis-tap doesn't delete anything",
          "Make targets at least 24px, ideally about 44, or move Delete into a menu",
          "Make the Delete icon red so people notice it before they tap",
          "Add tooltips to both icons that explain what each one does",
        ],
        correct: 1,
        why: "Bigger, well-spaced targets prevent the mis-taps, and moving a destructive action away from a frequent one adds a safety margin. A confirmation only catches the mistake after it happens and slows down every intended delete. Color and tooltips don't make the targets any easier to hit.",
      },
      {
        id: "a8-spot-click-here",
        type: "spot",
        question: "A screen reader user pulls up a list of every link on this HR page. Which part gives them a useless link?",
        title: "Benefits",
        parts: [
          {
            id: "intro",
            label: "Paragraph: Open enrollment runs from 1 to 15 November.",
            html: `<div>Open enrollment runs from 1 to 15 November.</div>`,
          },
          {
            id: "guide",
            label: "Link: Download the 2026 benefits guide (PDF, 2 MB)",
            html: `<span class="mk-link">Download the 2026 benefits guide (PDF, 2 MB)</span>`,
          },
          {
            id: "address",
            label: "Sentence with a link: To update your home address, click here.",
            html: `<div>To update your home address, <span class="mk-link">click here</span>.</div>`,
          },
          {
            id: "contact",
            label: "Link: Contact the HR team",
            html: `<span class="mk-link">Contact the HR team</span>`,
          },
        ],
        correct: "address",
        why: "In a list of links, “click here” says nothing about where it goes, so screen reader users have to leave the list and read around it to find out. Link the words that describe the destination instead: “Update your home address”. The other links make sense on their own.",
      },
      {
        id: "a8-sort-link-button",
        type: "sort",
        question: "Which should be built as a link, and which as a button?",
        groups: ["Link", "Button"],
        items: [
          { id: "invoice", text: "View invoice, which opens the invoice page", group: 0 },
          { id: "privacy", text: "Privacy policy", group: 0 },
          { id: "checkout", text: "Go to checkout", group: 0 },
          { id: "save", text: "Save changes", group: 1 },
          { id: "delete", text: "Delete file", group: 1 },
          { id: "filters", text: "Show filters, which opens a panel on the same page", group: 1 },
        ],
        why: "Links take people somewhere: another page or another place. Buttons do something: save, delete, open or close a panel. Screen readers announce them differently, and they respond to different keys, so using the right one sets the right expectation. “Show filters” is the one teams often build as a link, but it changes the current page rather than going anywhere.",
      },
    ],
  },
];

export const accessibilityPath: LearningPath = {
  id: "accessibility",
  title: "Accessibility basics",
  description: "Who accessibility serves, contrast, keyboard access, structure and forms. Built from W3C WAI material.",
  status: "live",
  lessons,
};
