import type { Lesson, LearningPath } from "../types";

const NNG = "https://www.nngroup.com/articles/ten-usability-heuristics/";
const nng = { title: "NN/g: 10 Usability Heuristics", url: NNG };

const lessons: Lesson[] = [
  {
    id: "h1",
    code: "H1",
    title: "Visibility of system status",
    subtitle: "Keep people informed, right away",
    minutes: 5,
    skills: ["feedback"],
    body: [
      "People act with confidence when they can tell what the system is doing. Every action deserves a response, and every wait deserves an explanation. Silence makes people click again, refresh, or give up.",
      "Good status feedback answers three questions: did it work, what is happening now, and how long will it take. It also shows where the person is: the current page in the navigation, the current step in a flow, the unsaved state of a document.",
    ],
    practice: [
      "Respond to every click or tap within about a tenth of a second, even if only by changing the button state.",
      "For waits longer than about a second, show a loading indicator. For waits over about ten seconds, show how much is done and how long is left.",
      "Confirm completed actions in place (a “Saved” label, a short message that fades away) instead of leaving people to guess.",
      "Show location: highlight the current nav item and number the steps of a multi-step form.",
    ],
    fieldExercise:
      "Open any form in a product you work on and submit it on a throttled connection. Write down every moment where nothing visibly changes for more than a second.",
    sources: [nng, { title: "NN/g: Visibility of System Status", url: "https://www.nngroup.com/articles/visibility-system-status/" }],
    exercises: [
      {
        id: "h1-upload-progress",
        type: "compare",
        question: "A user just clicked Upload on a 40 MB file. Which screen serves them better?",
        a: `<div class="mk"><div class="mk-title">Upload report</div><div class="mk-muted">quarterly-report.pdf</div><div class="mk-row"><span class="mk-btn sec">Uploading…</span></div></div>`,
        b: `<div class="mk"><div class="mk-title">Upload report</div><div class="mk-muted">quarterly-report.pdf · 62% · about 8 sec left</div><div class="mk-bar"><i style="width:62%"></i></div><div class="mk-row"><span class="mk-btn sec">Cancel upload</span></div></div>`,
        describe: {
          a: "An Upload report screen showing quarterly-report.pdf and an outlined button that reads “Uploading…”.",
          b: "An Upload report screen showing quarterly-report.pdf, 62%, about 8 seconds left, a progress bar about two-thirds full, and a Cancel upload button.",
        },
        correct: "b",
        why: "B shows how far along the upload is and how long is left, and it offers a way to stop. A at least says something is happening, but for a 40 MB file that can take a while, people can't tell whether it's nearly done or stuck, and they have no way to cancel.",
      },
      {
        id: "h1-save-feedback",
        type: "choice",
        question: "Saving a timesheet takes about 4 seconds. What is the best feedback?",
        options: [
          "Nothing until it finishes, then reload the page",
          "Change the button to “Saving…” with a spinner, then show “Saved at 3:42 PM”",
          "A modal dialog that says “Your data has been saved successfully” with an OK button",
          "Disable the whole page until the save completes",
        ],
        correct: 1,
        why: "In-place feedback during the wait plus a quiet confirmation afterwards keeps people informed without interrupting them. A modal adds a click for no benefit, a frozen page with no message looks broken, and saying nothing for 4 seconds before reloading leaves people wondering whether it worked.",
      },
      {
        id: "h1-spot-silent-upload",
        type: "spot",
        question: "Someone is uploading three files. Which part leaves them guessing about what's happening?",
        title: "Uploads",
        parts: [
          {
            id: "done",
            label: "File row: budget-2026.xlsx, Uploaded, with a check mark",
            html: `<div class="mk-row"><span>budget-2026.xlsx</span><span class="mk-up">✓ Uploaded</span></div>`,
          },
          {
            id: "progress",
            label: "File row: photos.zip, 64%, about 12 seconds left, with a progress bar",
            html: `<div>photos.zip · 64% · about 12 seconds left</div><div class="mk-bar"><i style="width:64%"></i></div>`,
          },
          {
            id: "silent",
            label: "File row: contract.pdf. Nothing else is shown next to it.",
            html: `<div>contract.pdf</div>`,
          },
          {
            id: "add",
            label: "Button: Add files",
            html: `<span class="mk-btn sec">Add files</span>`,
          },
        ],
        correct: "silent",
        why: "contract.pdf shows no status at all, so people can't tell whether it's waiting, uploading, finished or failed, and many will upload it again. The other two rows say exactly where they stand: one is done, the other shows progress and time left.",
      },
      {
        id: "h1-sort-wait",
        type: "sort",
        question: "Which waits need a progress indicator that shows how far along things are, and which need only a quick cue?",
        groups: ["Show progress", "A quick cue is enough"],
        items: [
          { id: "video", text: "Uploading a 2 GB video", group: 0 },
          { id: "export", text: "Exporting a year of reports, which takes about two minutes", group: 0 },
          { id: "update", text: "Installing a software update, which takes several minutes", group: 0 },
          { id: "search", text: "Loading search results, which takes about two seconds", group: 1 },
          { id: "like", text: "Liking a post", group: 1 },
          { id: "note", text: "Saving a short note, which takes a fraction of a second", group: 1 },
        ],
        why: "When a wait runs to many seconds or minutes, people need to see how far along it is and roughly how long is left, or they assume it's stuck and give up. Quick actions only need a brief cue, like a button changing state or a “Saved” note; a full progress bar would flash past and add noise. A two-second search is the one people overdo: a small spinner is plenty, and anything faster than about a second needs no indicator at all.",
      },
    ],
  },
  {
    id: "h2",
    code: "H2",
    title: "Match between the system and the real world",
    subtitle: "Speak the user's language",
    minutes: 5,
    skills: ["language"],
    body: [
      "Interfaces should use the words, concepts and conventions people already know from their work and life, not the vocabulary of the database or the engineering team.",
      "This also covers order and metaphor. Information should appear in the order people expect, and icons or metaphors should map to real-world meaning the audience actually shares.",
    ],
    practice: [
      "Label things with the terms your users say out loud. Listen in interviews and support calls for their words.",
      "Hide internal IDs, codes and system states unless people genuinely use them.",
      "Follow the real-world sequence of a task: a shipping form asks for name, then street, then city.",
      "Test icons without labels. If people can't name them, add a label.",
    ],
    fieldExercise:
      "Pick one screen and list every label on it. Circle any word a new user wouldn't use when describing the task to a coworker.",
    sources: [nng],
    exercises: [
      {
        id: "h2-date-field",
        type: "compare",
        question: "An office manager in Denver is booking a meeting room. Which start time field is easier for them?",
        a: `<div class="mk"><div class="mk-label">Start (UTC)</div><div class="mk-in">2026-10-12T15:00Z</div></div>`,
        b: `<div class="mk"><div class="mk-label">Start date and time</div><div class="mk-row"><span class="mk-in">Mon, Oct 12, 2026</span><span class="mk-in">9:00 AM</span></div><div class="mk-muted">Mountain Time</div></div>`,
        describe: {
          a: "A field labeled “Start (UTC)” containing 2026-10-12T15:00Z.",
          b: "A field labeled “Start date and time” with two boxes, Mon, Oct 12, 2026 and 9:00 AM, and the note Mountain Time below.",
        },
        correct: "b",
        why: "B shows the date in a familiar format and the time in the manager's own time zone. A is precise, and it's how many systems store times, but the manager has to convert 15:00 UTC to Denver time in their head, which is easy to get wrong by an hour or even a day.",
      },
      {
        id: "h2-field-label",
        type: "choice",
        question: "A timesheet app for hourly staff labels a field “Billable unit allocation (decimal)”. What's the best fix?",
        options: [
          "Add a tooltip that explains what a billable unit is",
          "Rename it “Hours worked” with an example like “7.5”",
          "Keep the label but add a validation error for non-decimals",
          "Move the field to an Advanced section",
        ],
        correct: 1,
        why: "The problem is the vocabulary itself. Renaming the field to the words staff already use removes the need for an explanation. A tooltip treats the symptom and still makes everyone read it, a validation error only tells people they misread a confusing label, and moving it to an Advanced section hides a field everyone needs.",
      },
      {
        id: "h2-spot-system-units",
        type: "spot",
        question: "Hourly staff use this form to ask for time off. Which part uses the system's language instead of theirs?",
        title: "Request time off",
        parts: [
          {
            id: "start",
            label: "Field labeled Start date, containing Mon 12 Oct",
            html: `<div class="mk-label">Start date</div><div class="mk-in">Mon 12 Oct</div>`,
          },
          {
            id: "duration",
            label: "Field labeled Duration (in 15-minute units), containing 32",
            html: `<div class="mk-label">Duration (in 15-minute units)</div><div class="mk-in">32</div>`,
          },
          {
            id: "reason",
            label: "Dropdown labeled Reason, showing Vacation",
            html: `<div class="mk-label">Reason</div><div class="mk-in">Vacation ▾</div>`,
          },
          {
            id: "submit",
            label: "Button: Submit request",
            html: `<span class="mk-btn">Submit request</span>`,
          },
        ],
        correct: "duration",
        why: "People think about time off in days and hours, not 15-minute units, so they have to do arithmetic (32 units is 8 hours) and some will get it wrong. Asking for hours or days, in the words staff use, removes the translation. The date, reason and button already speak their language.",
      },
      {
        id: "h2-sort-words",
        type: "sort",
        question: "A travel booking app is reviewing its labels. Which use the system's words, and which use the traveler's?",
        groups: ["System's words", "Traveler's words"],
        items: [
          { id: "pnr", text: "PNR locator", group: 0 },
          { id: "booking", text: "Booking reference", group: 1 },
          { id: "pax", text: "Pax count", group: 0 },
          { id: "travelers", text: "Number of travelers", group: 1 },
          { id: "fare", text: "Fare basis code", group: 0 },
          { id: "checked", text: "Checked bags", group: 1 },
        ],
        why: "“PNR locator”, “pax count” and “fare basis code” are airline-industry terms that travelers rarely know, so they have to guess or look them up. “Booking reference”, “Number of travelers” and “Checked bags” say the same things in the words people already use when they talk about a trip.",
      },
    ],
  },
  {
    id: "h3",
    code: "H3",
    title: "User control and freedom",
    subtitle: "Clear exits and easy undo",
    minutes: 5,
    skills: ["control"],
    body: [
      "People make mistakes and change their minds. They need a clearly marked way out of anything they got into by accident, without having to go through a long process.",
      "Undo is the strongest form of control. It lets people explore with less fear, and for frequent, reversible actions it usually beats asking “Are you sure?” every time.",
    ],
    practice: [
      "Give every flow a visible Back and Cancel, and say what Cancel will discard.",
      "Prefer undo over confirmation dialogs for actions people do often and can safely reverse.",
      "Let people leave a long form and come back later with their work saved as a draft.",
      "Make it easy to exit modes, overlays and full-screen views with Esc or a close button.",
    ],
    fieldExercise:
      "Walk through your product's longest task. At each step, note whether you could back out without losing work.",
    sources: [nng],
    exercises: [
      {
        id: "h3-undo-vs-confirm",
        type: "compare",
        question: "People archive dozens of messages a day. Which pattern supports them better?",
        a: `<div class="mk"><div class="mk-muted">Inbox · 41 conversations</div><div class="mk-toast"><span>Conversation archived</span><u>Undo</u></div></div>`,
        b: `<div class="mk"><div class="mk-title">Archive this conversation?</div><div class="mk-muted">This action can be reversed later from the Archive folder.</div><div class="mk-row"><span class="mk-btn sec">Cancel</span><span class="mk-btn">Archive</span></div></div>`,
        describe: {
          a: "The inbox, 41 conversations, with a small message at the bottom saying “Conversation archived” and an Undo link.",
          b: "A dialog asking “Archive this conversation?”, noting it can be reversed later from the Archive folder, with Cancel and Archive buttons.",
        },
        correct: "a",
        why: "For a frequent, reversible action like archiving, A's undo keeps people moving and still rescues the occasional mistake. B's confirmation adds a click every time, and people soon click through it without reading.",
      },
      {
        id: "h3-wizard-back",
        type: "choice",
        question: "A five-step onboarding wizard has no Back button, and Cancel throws away everything. What's the best improvement?",
        options: [
          "Add a warning on step 1 explaining that Cancel discards everything entered so far",
          "Add Back on every step and save progress as a draft people can resume later",
          "Remove the Cancel button from every step so nobody can lose their work by accident",
          "Combine all five steps into one long page so nothing is lost between steps",
        ],
        correct: 1,
        why: "Back lets people correct earlier answers, and drafts make leaving safe. Removing Cancel traps people, which is the opposite of control. A warning on step 1 is easy to forget by step 4 and doesn't help anyone fix an earlier answer, and one long page makes the task feel heavier without making mistakes easier to correct.",
      },
      {
        id: "h3-spot-no-way-back",
        type: "spot",
        question: "Someone opened this by mistake while managing their subscription. Which part takes away their control?",
        title: "Before you go…",
        parts: [
          {
            id: "message",
            label: "Text: We'll miss you. Your plan ends on 31 October.",
            html: `<div>We'll miss you. Your plan ends on 31 October.</div>`,
          },
          {
            id: "cancel",
            label: "Button: Yes, cancel my plan",
            html: `<span class="mk-btn danger">Yes, cancel my plan</span>`,
          },
          {
            id: "keep",
            label: "Small text: To keep your plan, call support between 9 AM and 5 PM.",
            html: `<div class="mk-muted">To keep your plan, call support between 9 AM and 5 PM.</div>`,
          },
        ],
        correct: "keep",
        why: "The only way back out is a phone call during office hours, so someone who got here by accident is trapped. A clear “Keep my plan” button or a close option gives them an easy exit. The message and the cancel button are fine for people who really do want to cancel.",
      },
      {
        id: "h3-sort-exits",
        type: "sort",
        question: "Which designs give people an easy way out, and which trap them?",
        groups: ["Easy way out", "Traps people"],
        items: [
          { id: "cancel", text: "A Cancel link on every step of checkout", group: 0 },
          { id: "undo", text: "Undo right after deleting an email", group: 0 },
          { id: "tour", text: "An “Exit tour” button on a product walkthrough", group: 0 },
          { id: "modal", text: "A pop-up survey with no close button", group: 1 },
          { id: "submitonly", text: "A pop-up form whose only button is Submit", group: 1 },
          { id: "signup", text: "A free trial that can only be canceled by phoning support", group: 1 },
        ],
        why: "Clear exits and undo let people explore without fear of getting stuck or losing work. A survey that can't be closed, a form you can only submit and a cancellation that needs a phone call all punish people for changing their mind. The phone-only cancellation is the sneakiest: it has an exit, but one made deliberately hard to use.",
      },
    ],
  },
  {
    id: "h4",
    code: "H4",
    title: "Consistency and standards",
    subtitle: "Same thing, same look, same place",
    minutes: 5,
    skills: ["conventions"],
    body: [
      "If one screen says “Save” and the next says “Submit” for the same action, people stop to work out whether they do different things. Internal consistency means the same thing always looks, reads and behaves the same across your product.",
      "External consistency matters too. Your users arrive already trained by every other app on their device, so they expect yours to follow the platform's conventions. Breaking them makes people relearn something before they can get on with their task.",
    ],
    practice: [
      "Use one word for one concept across the product: not Delete here and Remove there.",
      "Keep primary and secondary buttons in the same order and style on every screen.",
      "Follow platform conventions: the logo links home, a magnifier means search, underlined text is a link.",
      "Capture patterns in a design system so consistency doesn't depend on memory.",
    ],
    fieldExercise:
      "Screenshot every dialog in one product and line them up. Compare button labels, order and styling.",
    sources: [nng, { title: "Laws of UX: Jakob's Law", url: "https://lawsofux.com/jakobs-law/" }],
    exercises: [
      {
        id: "h4-dialog-conventions",
        type: "compare",
        question: "Which dialog follows common conventions?",
        a: `<div class="mk"><div class="mk-title">Edit profile</div><div class="mk-in">Reece</div><div class="mk-row"><span class="mk-btn sec">Save</span><span class="mk-btn">Cancel</span></div></div>`,
        b: `<div class="mk"><div class="mk-title">Edit profile</div><div class="mk-in">Reece</div><div class="mk-row"><span class="mk-btn sec">Cancel</span><span class="mk-btn">Save</span></div></div>`,
        describe: {
          a: "An Edit profile dialog with a name field. Below it, an outlined Save button and a solid filled Cancel button.",
          b: "An Edit profile dialog with a name field. Below it, an outlined Cancel button and a solid filled Save button.",
        },
        correct: "b",
        why: "In B the main action, Save, has the main button style, so eyes and fingers go to it. A gives Cancel the filled style, so people acting on habit press the wrong button and lose their edit. It's a small swap that real products ship by accident.",
      },
      {
        id: "h4-logo-home",
        type: "choice",
        question: "Your app's logo in the top-left corner does nothing when clicked. What does this mainly break?",
        options: [
          "Internal consistency across the product's own pages",
          "External consistency with web conventions",
          "Visibility of system status in the header",
          "Match with the words people use every day",
        ],
        correct: 1,
        why: "Clicking the logo to go home is a convention people learned on other sites. Breaking it is an external consistency problem, even if your app is internally consistent. The header still shows where people are, and its words still make sense; what breaks is the behavior people learned elsewhere, so they can't get home the way they expect.",
      },
      {
        id: "h4-spot-odd-actions",
        type: "spot",
        question: "Which part breaks the pattern the rest of this screen sets?",
        title: "Team members",
        parts: [
          {
            id: "ana",
            label: "Row: Ana Silva, Admin, with links Edit and Remove",
            html: `<div class="mk-row"><span>Ana Silva · Admin</span><span class="mk-link">Edit</span><span class="mk-link">Remove</span></div>`,
          },
          {
            id: "ben",
            label: "Row: Ben Cho, Editor, with links Edit and Remove",
            html: `<div class="mk-row"><span>Ben Cho · Editor</span><span class="mk-link">Edit</span><span class="mk-link">Remove</span></div>`,
          },
          {
            id: "cara",
            label: "Row: Cara Díaz, Viewer, with links Modify and Delete user",
            html: `<div class="mk-row"><span>Cara Díaz · Viewer</span><span class="mk-link">Modify</span><span class="mk-link">Delete user</span></div>`,
          },
          {
            id: "invite",
            label: "Button: Invite member",
            html: `<span class="mk-btn">Invite member</span>`,
          },
        ],
        correct: "cara",
        why: "Cara's row uses different words for the same actions, so people stop to wonder whether “Delete user” does something different from “Remove”. Every row should use the same labels in the same places. The other rows and the invite button follow the pattern.",
      },
      {
        id: "h4-sort-conventions",
        type: "sort",
        question: "Which design choices follow common conventions, and which break them?",
        groups: ["Follows convention", "Breaks convention"],
        items: [
          { id: "logo", text: "The logo in the top-left corner links to the home page", group: 0 },
          { id: "links", text: "Links in text are underlined", group: 0 },
          { id: "search", text: "The search box has a magnifying-glass icon", group: 0 },
          { id: "save", text: "The Save button is red and the Delete button is green", group: 1 },
          { id: "cart", text: "The shopping cart is called “Satchel”", group: 1 },
          { id: "order", text: "OK is on the left in some dialogs and on the right in others", group: 1 },
        ],
        why: "People bring expectations from every other product they use, so conventions let them act without thinking. Swapping the meaning of red and green, renaming the cart, or moving buttons around between dialogs forces people to stop and check, and leads to slips. The OK button is the easy one to miss: it's an inconsistency within your own product, which breaks the habit people just built.",
      },
    ],
  },
  {
    id: "h5",
    code: "H5",
    title: "Error prevention",
    subtitle: "Design so mistakes are hard to make",
    minutes: 5,
    skills: ["errors"],
    body: [
      "Good error messages matter, but preventing the error in the first place is better. Look for conditions that set people up to fail and remove them.",
      "It helps to separate two kinds of error. Slips are wrong actions when the person knew the right one, such as a typo or a misclick. Mistakes come from a wrong understanding of how something works. Slips need constraints and forgiving input; mistakes need clearer design.",
    ],
    practice: [
      "Use constraints: disable impossible dates, offer choices instead of free text where the options are fixed.",
      "Accept input in any reasonable format and clean it up yourself (spaces in phone numbers, dashes in IDs).",
      "Set safe defaults and separate destructive actions from common ones.",
      "For serious, irreversible actions, ask for a deliberate confirmation such as typing the project name.",
    ],
    fieldExercise:
      "Find the most common validation error in your product's logs or support tickets. Ask whether the design could make it impossible.",
    sources: [nng, { title: "NN/g: Preventing User Errors (slips)", url: "https://www.nngroup.com/articles/slips/" }],
    exercises: [
      {
        id: "h5-danger-zone",
        type: "compare",
        question: "Which settings panel better prevents someone from deleting a project by accident?",
        a: `<div class="mk"><div class="mk-title">Project settings</div><div class="mk-row"><span class="mk-btn">Save</span></div><div class="mk-label">Danger zone</div><div class="mk-muted">Type <b>apollo-site</b> to permanently delete this project.</div><div class="mk-row"><span class="mk-in">apollo-si</span><span class="mk-btn danger dim">Delete</span></div></div>`,
        b: `<div class="mk"><div class="mk-title">Project settings</div><div class="mk-row"><span class="mk-btn">Save</span><span class="mk-btn">Delete project</span></div></div>`,
        describe: {
          a: "Project settings with a Save button. Below, a separate section headed Danger zone asks you to type apollo-site to delete. The field holds apollo-si, and the red Delete button next to it is grayed out.",
          b: "Project settings with two identical filled buttons side by side: Save and Delete project.",
        },
        correct: "a",
        why: "A separates the destructive action from the everyday one and requires a deliberate step before something permanent. In B, Delete sits next to Save in the same style, a setup for a costly slip.",
      },
      {
        id: "h5-forgiving-input",
        type: "choice",
        question: "A form rejects phone numbers typed with spaces or dashes. What's the best fix?",
        options: [
          "Add hint text below the field: “Digits only, no spaces or dashes”",
          "Show a clearer, more specific error message after the form is submitted",
          "Accept any format, and strip spaces and dashes before checking it",
          "Split the field into three boxes so people type each part separately",
        ],
        correct: 2,
        why: "The format rule exists for the system, not the person. Accepting what people naturally type removes the error entirely, which beats explaining the rule or reporting the error better. Three separate boxes add a new rule of their own and break pasting a number copied from elsewhere.",
      },
      {
        id: "h5-spot-delete",
        type: "spot",
        question: "People use this settings page every day to rename projects. Which part makes a costly mistake too easy?",
        title: "Project settings",
        parts: [
          {
            id: "name",
            label: "Field labeled Project name, containing Q4 launch plan",
            html: `<div class="mk-label">Project name</div><div class="mk-in">Q4 launch plan</div>`,
          },
          {
            id: "desc",
            label: "Field labeled Description, containing Timeline and owners for the October launch",
            html: `<div class="mk-label">Description</div><div class="mk-in">Timeline and owners for the October launch</div>`,
          },
          [
            {
              id: "save",
              label: "Button: Save changes",
              html: `<span class="mk-btn">Save changes</span>`,
            },
            {
              id: "delete",
              label: "Button right beside it, in the same style: Delete project",
              html: `<span class="mk-btn">Delete project</span>`,
            },
          ],
          {
            id: "note",
            label: "Small text: Last edited by Dana Kim, 2 hours ago",
            html: `<div class="mk-muted">Last edited by Dana Kim, 2 hours ago</div>`,
          },
        ],
        correct: "delete",
        why: "Delete project sits right beside Save changes and looks the same, so a quick click on the everyday action can wipe out a whole project. Destructive actions belong away from frequent ones, styled differently, with a confirmation or an undo. The fields and the edit note are fine.",
      },
      {
        id: "h5-sort-prevent",
        type: "sort",
        question: "Which designs prevent the mistake, and which only report it afterwards?",
        groups: ["Prevents the mistake", "Reports it afterwards"],
        items: [
          { id: "dates", text: "A return-date picker that won't let you pick a day before departure", group: 0 },
          { id: "phone", text: "A phone number field that accepts spaces and dashes", group: 0 },
          { id: "sizes", text: "Sizes that are out of stock are shown as unavailable before you add to cart", group: 0 },
          { id: "typename", text: "Typing the project name before Delete becomes available", group: 0 },
          { id: "invalid", text: "An “Invalid format” message after you submit the form", group: 1 },
          { id: "email", text: "An email saying the invoice went to the wrong customer", group: 1 },
        ],
        why: "Preventing errors means shaping the design so the slip can't happen or doesn't matter: blocking impossible dates, accepting the formats people naturally type, showing unavailable options and adding friction before something permanent. An error after submitting and an apology email both arrive once the damage is done. Accepting spaces in a phone number counts as prevention: there's no error to make.",
      },
    ],
  },
  {
    id: "h6",
    code: "H6",
    title: "Recognition rather than recall",
    subtitle: "Show options instead of testing memory",
    minutes: 5,
    skills: ["effort"],
    body: [
      "Recognizing something you can see is much easier than remembering it from scratch. Interfaces should make objects, actions and options visible so people don't have to hold information in their heads.",
      "This applies across screens too. If people need something from step 2 on step 4, show it again on step 4.",
    ],
    practice: [
      "Show recent items, recent searches and suggestions instead of blank inputs.",
      "Keep relevant information visible when it is needed, such as order details at payment.",
      "Use visible menus and labeled icons rather than hidden gestures or memorized commands.",
      "Offer previews and examples so people can recognize the right choice.",
    ],
    fieldExercise:
      "Look for any screen that asks people to type something the system already knows. Each one is a recall burden you can remove.",
    sources: [nng, { title: "NN/g: Memory Recognition and Recall", url: "https://www.nngroup.com/articles/recognition-and-recall/" }],
    exercises: [
      {
        id: "h6-recent-items",
        type: "compare",
        question: "A manager wants to reopen a review they worked on yesterday. Which screen helps more?",
        a: `<div class="mk"><div class="mk-label">Find a review</div><div class="mk-in">Search reviews</div><span class="mk-link">Advanced search</span></div>`,
        b: `<div class="mk"><div class="mk-label">Find a review</div><div class="mk-in">Search by name</div><div class="mk-label">Recently opened</div><div class="mk-muted">Jordan Lee · Q3 review · yesterday</div><div class="mk-muted">Priya Shah · Q3 review · Mon</div></div>`,
        describe: {
          a: "Find a review: a field with the placeholder Search reviews, and an Advanced search link.",
          b: "Find a review: a field with the placeholder Search by name, then a list headed Recently opened: Jordan Lee, Q3 review, yesterday; Priya Shah, Q3 review, Monday.",
        },
        correct: "b",
        why: "Both let the manager search, but B also lists recently opened reviews, so they can recognize yesterday's review and open it straight away. A makes them recall a name or details to search for, and advanced search only adds more to remember.",
      },
      {
        id: "h6-checkout-summary",
        type: "choice",
        question: "On a checkout's payment step, people keep asking which shipping option they chose. What's the best fix?",
        options: [
          "Add a Back link so people can return to the shipping step and check",
          "Show the shipping choice on the payment step, with a Change link",
          "Send a confirmation email that repeats the shipping choice after payment",
          "Make the shipping step more memorable with larger text and icons",
        ],
        correct: 1,
        why: "Showing the choice where it's needed removes the memory burden. A Back link makes people leave the task to check, an email arrives too late, and a more memorable shipping step still asks people to remember it.",
      },
      {
        id: "h6-spot-remember-code",
        type: "spot",
        question: "Which part makes people remember something instead of choosing it?",
        title: "Run a report",
        parts: [
          {
            id: "range",
            label: "Dropdown labeled Date range, showing Last 30 days",
            html: `<div class="mk-label">Date range</div><div class="mk-in">Last 30 days ▾</div>`,
          },
          {
            id: "dept",
            label: "Field labeled Department code, with the hint Enter the 4-digit code from the HR handbook. It's empty.",
            html: `<div class="mk-label">Department code</div><div class="mk-muted">Enter the 4-digit code from the HR handbook</div><div class="mk-in">&nbsp;</div>`,
          },
          {
            id: "format",
            label: "Dropdown labeled Format, showing PDF",
            html: `<div class="mk-label">Format</div><div class="mk-in">PDF ▾</div>`,
          },
          {
            id: "run",
            label: "Button: Run report",
            html: `<span class="mk-btn">Run report</span>`,
          },
        ],
        correct: "dept",
        why: "People have to recall or look up a 4-digit code in a separate handbook, when the system could simply list the departments by name to choose from. The other fields already let people recognize the option they want.",
      },
      {
        id: "h6-sort-recognition",
        type: "sort",
        question: "Which designs let people recognize what they need, and which make them recall it from memory?",
        groups: ["Recognize", "Recall"],
        items: [
          { id: "recent", text: "A list of recently opened files", group: 0 },
          { id: "addresses", text: "A dropdown of your saved delivery addresses", group: 0 },
          { id: "autocomplete", text: "City suggestions that appear as you type", group: 0 },
          { id: "command", text: "A blank command box where you type commands from memory", group: 1 },
          { id: "custid", text: "Typing a customer ID to look someone up", group: 1 },
        ],
        why: "Recognizing an option you can see is much easier than pulling it from memory, which is why recent lists, saved choices and suggestions speed people up. A blank command box and an ID-only lookup put the whole burden on memory. Autocomplete is the one people hesitate over: you start typing, but the list then lets you recognize the right city.",
      },
    ],
  },
  {
    id: "h7",
    code: "H7",
    title: "Flexibility and efficiency of use",
    subtitle: "Shortcuts for experts, simple paths for novices",
    minutes: 5,
    skills: ["control"],
    body: [
      "A product used daily should get faster as people get better at it. Accelerators such as keyboard shortcuts, bulk actions and templates help experienced users without getting in the way of new ones.",
      "Flexibility can also mean personalization: letting people set defaults, save views, or reorder what they see most.",
    ],
    practice: [
      "Add keyboard shortcuts for frequent actions and show them in menus and tooltips.",
      "Support bulk selection and bulk edit for repetitive work.",
      "Offer “copy from last time”, templates and saved filters.",
      "Keep the simple path visible so beginners never need the shortcuts.",
    ],
    fieldExercise:
      "Ask an expert user to do their most repeated task while you watch. Count the clicks. Any step repeated per row is a candidate for a bulk action.",
    sources: [nng],
    exercises: [
      {
        id: "h7-bulk-grid",
        type: "compare",
        question: "An accountant reviews 200 timesheet rows every Friday. Which grid suits them?",
        a: `<div class="mk"><div class="mk-row"><span class="mk-muted">☐ Select all</span><span class="mk-btn">Approve 12 selected</span></div><div class="mk-muted">Mon · 8.0 h · Site visit</div><div class="mk-muted">Tue · 7.5 h · Design review</div><div class="mk-row"><span class="mk-kbd">A</span><span class="mk-muted">approve</span><span class="mk-kbd">J</span><span class="mk-kbd">K</span><span class="mk-muted">next/prev</span></div></div>`,
        b: `<div class="mk"><div class="mk-muted">Mon · 8.0 h · Site visit <span class="mk-link">Open</span></div><div class="mk-muted">Tue · 7.5 h · Design review <span class="mk-link">Open</span></div><div class="mk-muted">Open each row to approve it.</div></div>`,
        describe: {
          a: "Timesheet rows (Monday, 8 hours, site visit; Tuesday, 7.5 hours, design review) under a Select all checkbox and an Approve 12 selected button, with keyboard shortcuts shown: A to approve, J and K for next and previous.",
          b: "Timesheet rows (Monday, 8 hours, site visit; Tuesday, 7.5 hours, design review), each with an Open link, and a note: Open each row to approve it.",
        },
        correct: "a",
        why: "A keeps the simple path (click Approve) while adding bulk selection and keyboard shortcuts for heavy use. B forces 200 open-approve-close cycles.",
      },
      {
        id: "h7-visible-shortcuts",
        type: "choice",
        question: "Which accelerator is least likely to confuse first-time users?",
        options: [
          "A shortcut that only works if you know it, with no hint anywhere",
          "Hidden swipe gestures that delete rows",
          "Keyboard shortcuts shown next to the matching menu items",
          "Replacing buttons with shortcuts to save space",
        ],
        correct: 2,
        why: "Showing shortcuts beside the normal controls teaches them gradually. Beginners still have the visible button, and experts learn the shortcut by seeing it. A shortcut with no hint, or a hidden swipe, only helps people who already know it, and a hidden swipe that deletes can also cause accidents. Replacing buttons with shortcuts leaves beginners nothing to click.",
      },
      {
        id: "h7-spot-one-at-a-time",
        type: "spot",
        question: "Staff update hundreds of products every week. Which part makes their frequent work slow?",
        title: "Products · 250 items",
        parts: [
          {
            id: "search",
            label: "Search field: Search products",
            html: `<div class="mk-in">Search products</div>`,
          },
          {
            id: "edit",
            label: "Button: Edit, with the note Select one product at a time",
            html: `<div class="mk-row"><span class="mk-btn sec">Edit</span><span class="mk-muted">Select one product at a time</span></div>`,
          },
          {
            id: "row",
            label: "Product row: Desk lamp, $39, In stock",
            html: `<div>Desk lamp · $39 · In stock</div>`,
          },
          {
            id: "add",
            label: "Button: Add product",
            html: `<span class="mk-btn">Add product</span>`,
          },
        ],
        correct: "edit",
        why: "Editing one product at a time is fine for beginners but painfully slow for people who change hundreds a week. Letting experts select many items and edit them together, or use shortcuts, speeds up the frequent case without getting in the way of novices. Search, the rows and Add product are fine.",
      },
      {
        id: "h7-sort-accelerators",
        type: "sort",
        question: "A project management tool. Which features are accelerators for frequent users, and which are the basic path for everyone?",
        groups: ["Accelerator", "Basic path"],
        items: [
          { id: "shortcut", text: "Pressing Ctrl+K to jump to any project", group: 0 },
          { id: "bulk", text: "Selecting 20 tasks and changing their due date at once", group: 0 },
          { id: "saved", text: "Saved filters for “My overdue tasks”", group: 0 },
          { id: "button", text: "A New task button in the toolbar", group: 1 },
          { id: "wizard", text: "A step-by-step setup guide for your first project", group: 1 },
        ],
        why: "Accelerators, like shortcuts, bulk actions and saved filters, speed up people who do the same work every day, without getting in the way of anyone else. The visible button and the setup guide are the simple path that every user, especially a newcomer, can find without learning anything. Good products offer both.",
      },
    ],
  },
  {
    id: "h8",
    code: "H8",
    title: "Aesthetic and minimalist design",
    subtitle: "Every element competes for attention",
    minutes: 5,
    skills: ["effort", "layout"],
    body: [
      "Every element on a screen competes for attention. Content that few people need, or that people need only now and then, still has a cost: it pushes the important parts down and makes them harder to spot.",
      "Minimalist doesn't mean flat or sparse for its own sake. It means the content and visual design support the person's main goals and nothing distracts from them.",
    ],
    practice: [
      "Decide what the one job of each screen is and give it the most visual weight.",
      "Move rarely used details behind a “More” link or an expanding section.",
      "Cut decorative color and badges that don't carry meaning.",
      "Write shorter copy: remove introductions and repeated explanations.",
    ],
    fieldExercise:
      "Take a busy dashboard and mark each element as “used weekly”, “used rarely” or “never”. Propose where the rarely and never items should go.",
    sources: [nng],
    exercises: [
      {
        id: "h8-focused-card",
        type: "compare",
        question: "A store manager opens this card to check whether sales are on track. Which works better?",
        a: `<div class="mk"><div class="mk-grid"><div class="mk-cell"><b>$48,210</b>Sales <span class="mk-pill">NEW</span></div><div class="mk-cell"><b>1,204</b>Orders</div><div class="mk-cell"><b>3.1%</b>Conv.</div><div class="mk-cell"><b>$40.04</b>AOV</div><div class="mk-cell"><b>212</b>Returns</div><div class="mk-cell"><b>18</b>SKUs <span class="mk-pill">HOT</span></div></div></div>`,
        b: `<div class="mk"><div class="mk-label">Sales this week</div><div class="mk-big">$48,210</div><div class="mk-up">▲ 6% vs last week</div><div class="mk-link">See breakdown</div></div>`,
        describe: {
          a: "A grid of six equal tiles: $48,210 Sales with a NEW badge, 1,204 Orders, 3.1% Conv., $40.04 AOV, 212 Returns, and 18 SKUs with a HOT badge.",
          b: "A card headed Sales this week, with $48,210 in large text, a green up arrow with 6% vs last week, and a See breakdown link.",
        },
        correct: "b",
        why: "B answers the manager's question at a glance and links to the detail. A gives every metric equal weight, so the one that matters has to be hunted for.",
      },
      {
        id: "h8-minimalist-meaning",
        type: "choice",
        question: "What does “minimalist” mean in this heuristic?",
        options: [
          "Using a flat visual style with no shadows, gradients or textures",
          "Showing as little on screen as possible, even things people need",
          "Leaving out anything that doesn't support the user's goal",
          "Limiting the palette to one or two colors across the product",
        ],
        correct: 2,
        why: "The heuristic is about relevance. A rich screen can be minimalist if everything on it serves the task, and a sparse one can fail if it hides what people need. A flat style or a small palette is a visual choice; a screen can have both and still be full of clutter.",
      },
      {
        id: "h8-spot-promo-clutter",
        type: "spot",
        question: "Which part competes with the one thing people came here to do?",
        title: "Sign in",
        parts: [
          {
            id: "email",
            label: "Field labeled Email",
            html: `<div class="mk-label">Email</div><div class="mk-in">&nbsp;</div>`,
          },
          {
            id: "password",
            label: "Field labeled Password",
            html: `<div class="mk-label">Password</div><div class="mk-in">&nbsp;</div>`,
          },
          {
            id: "promo",
            label: "Banner: NEW! Try our AI assistant. 50% off Pro this week. Learn more. Watch video.",
            html: `<div class="mk-row"><span class="mk-pill">NEW!</span><span>Try our AI assistant · 50% off Pro this week</span><span class="mk-link">Learn more</span><span class="mk-link">Watch video</span></div>`,
          },
          {
            id: "submit",
            label: "Button: Sign in",
            html: `<span class="mk-btn">Sign in</span>`,
          },
        ],
        correct: "promo",
        why: "People come to this screen to sign in, and the promotion pulls their attention away with two extra links. It belongs after sign-in, if anywhere. The fields and the button are exactly what the task needs.",
      },
      {
        id: "h8-sort-noise",
        type: "sort",
        question: "A store manager opens a sales card to check if this week is on track. Which elements earn their place, and which add noise?",
        groups: ["Earns its place", "Adds noise"],
        items: [
          { id: "total", text: "Total sales this week", group: 0 },
          { id: "change", text: "Change compared with last week", group: 0 },
          { id: "link", text: "A link to the full breakdown", group: 0 },
          { id: "photo", text: "A stock photo of people shaking hands", group: 1 },
          { id: "badge", text: "A “NEW” badge on a metric that launched a year ago", group: 1 },
          { id: "fact", text: "A fun fact about when the company was founded", group: 1 },
        ],
        why: "Everything on a screen competes for attention, so each element should help with the task. The total, the comparison and a way to dig deeper answer the manager's question. The photo, the stale badge and the fun fact don't help them judge sales, and they make the useful numbers slower to find. The badge is easy to overlook: it was useful once, but now it's just noise.",
      },
    ],
  },
  {
    id: "h9",
    code: "H9",
    title: "Help users recognize, diagnose, and recover from errors",
    subtitle: "Plain language, precise problem, a way forward",
    minutes: 5,
    skills: ["feedback"],
    body: [
      "When errors happen, the message should say in plain language what went wrong and suggest a fix. Error codes and blame don't help anyone recover.",
      "Placement and visibility matter as much as wording. Show the message where the problem is, make it noticeable, and keep the person's input so they only fix what's wrong.",
    ],
    practice: [
      "Name the specific problem and the specific fix.",
      "Show field errors next to the field, and highlight the field itself.",
      "Keep what people typed. Never clear a form because one field failed.",
      "Avoid blaming language and vague words like “invalid” or “illegal”.",
    ],
    fieldExercise:
      "Trigger five errors in your product on purpose. Rate each message: does it say what happened, why, and what to do next?",
    sources: [nng, { title: "NN/g: Error-Message Guidelines", url: "https://www.nngroup.com/articles/error-message-guidelines/" }],
    exercises: [
      {
        id: "h9-existing-account",
        type: "compare",
        question: "Someone signs up with an email that already has an account. Which message helps them recover?",
        a: `<div class="mk"><div class="mk-label">Email</div><div class="mk-in err">reece@example.com</div><div class="mk-err">This email already has an account.</div><div class="mk-row"><span class="mk-link">Sign in instead</span><span class="mk-link">Reset password</span></div></div>`,
        b: `<div class="mk"><div class="mk-label">Email</div><div class="mk-in err">reece@example.com</div><div class="mk-err">This email address is already registered.</div></div>`,
        describe: {
          a: "The Email field still holds reece@example.com, outlined in red, with the message “This email already has an account.” and two links: Sign in instead, and Reset password.",
          b: "The Email field still holds reece@example.com, outlined in red, with the message “This email address is already registered.” and nothing else.",
        },
        correct: "a",
        why: "Both say what went wrong in plain words and keep the email, but A also offers the two ways forward people most likely need: signing in or resetting their password. B leaves them to work out that they should go to the sign-in page, and many will try a different email instead. Some security teams prefer not to confirm which emails have accounts; a neutral “If you already have an account, sign in” still offers the same ways forward.",
      },
      {
        id: "h9-error-placement",
        type: "choice",
        question: "Where should a form field's validation error usually appear?",
        options: [
          "Only in a banner at the top of the page, listing every problem",
          "Next to the field it's about, with the field highlighted",
          "In a pop-up dialog that appears after the form is submitted",
          "In the browser console, where developers can see it",
        ],
        correct: 1,
        why: "Errors next to the field connect the problem to its location. A summary at the top can help on long forms, but it should link to the fields rather than replace inline messages. A pop-up hides the form while people read the problem, and the browser console is never seen by the people filling in the form.",
      },
      {
        id: "h9-spot-error-code",
        type: "spot",
        question: "Someone's sign-in just failed. Which part fails to help them recover?",
        title: "Sign in",
        parts: [
          {
            id: "email",
            label: "Field labeled Email, containing sam.lee@example.com",
            html: `<div class="mk-label">Email</div><div class="mk-in">sam.lee@example.com</div>`,
          },
          {
            id: "password",
            label: "Field labeled Password, containing hidden characters",
            html: `<div class="mk-label">Password</div><div class="mk-in">••••••••••</div>`,
          },
          {
            id: "error",
            label: "Red text: Error 0x80040154: AUTH_FAILED",
            html: `<div class="mk-err">Error 0x80040154: AUTH_FAILED</div>`,
          },
          [
            {
              id: "submit",
              label: "Button: Sign in",
              html: `<span class="mk-btn">Sign in</span>`,
            },
            {
              id: "forgot",
              label: "Link: Forgot your password?",
              html: `<span class="mk-link">Forgot your password?</span>`,
            },
          ],
        ],
        correct: "error",
        why: "The message is a code written for developers. It doesn't say in plain words what went wrong, such as a wrong password or a locked account, or what to do next. Something like “Email or password is incorrect. Try again or reset your password” would, without revealing which emails have accounts. The Forgot your password link is exactly the kind of way out people need.",
      },
      {
        id: "h9-sort-recover",
        type: "sort",
        question: "Which error messages help people recover, and which leave them stuck?",
        groups: ["Helps recover", "Leaves them stuck"],
        items: [
          { id: "card", text: "That card has expired. Use another card or update the expiry date.", group: 0 },
          { id: "signin", text: "If you already have an account, sign in instead.", group: 0 },
          { id: "offline", text: "We couldn't save because you're offline. Your draft is kept, so try again when you're back online.", group: 0 },
          { id: "code", text: "Error 0x80070057", group: 1 },
          { id: "wrong", text: "Something went wrong.", group: 1 },
          { id: "invalid", text: "Invalid input.", group: 1 },
        ],
        why: "A helpful error names the actual problem in plain words and gives a way forward, like another card, signing in, or trying again with the draft kept. A code, “Something went wrong” and “Invalid input” all confirm there's a problem without saying what it is or what to do, so people guess, retry blindly or give up.",
      },
    ],
  },
  {
    id: "h10",
    code: "H10",
    title: "Help and documentation",
    subtitle: "Help that is easy to find and act on",
    minutes: 5,
    skills: ["language"],
    body: [
      "Ideally a product needs no explanation, but some tasks are complex. When help is needed, it should be easy to search, focused on the task, and list concrete steps.",
      "The best help often appears in context, right where the question comes up, instead of in a separate manual people have to go looking for.",
    ],
    practice: [
      "Put short explanations next to complex fields and settings.",
      "Write help as task steps (“To export a report…”) rather than feature descriptions.",
      "Make documentation searchable and use the words people search with.",
      "Use onboarding sparingly and let people skip and revisit it.",
    ],
    fieldExercise:
      "Read your product's top five support tickets. For each, decide whether a one-line in-context hint would have prevented it.",
    sources: [nng],
    exercises: [
      {
        id: "h10-contextual-help",
        type: "compare",
        question: "A setting called “Accrual method” confuses new admins. Which help works better?",
        a: `<div class="mk"><div class="mk-label">Accrual method</div><div class="mk-in">Per pay period ▾</div><div class="mk-muted">How leave builds up. “Per pay period” adds hours each paycheck; “Annual” adds them all on Jan 1.</div></div>`,
        b: `<div class="mk"><div class="mk-label">Accrual method</div><div class="mk-in">Per pay period ▾</div><div class="mk-muted"><span class="mk-link">Learn more about accrual methods</span></div></div>`,
        describe: {
          a: "An Accrual method dropdown set to Per pay period, with a note underneath explaining both options: Per pay period adds hours each paycheck; Annual adds them all on January 1.",
          b: "An Accrual method dropdown set to Per pay period, with a link underneath: Learn more about accrual methods.",
        },
        correct: "a",
        why: "A answers the question right where it comes up, with what each option means. B's link is a reasonable start, but it takes people away from the setting to read an article, and many will guess rather than click through.",
      },
      {
        id: "h10-task-titles",
        type: "choice",
        question: "Which help article title is most useful?",
        options: [
          "Reports module overview",
          "How to export a report to Excel",
          "Advanced report configuration parameters",
          "Reports FAQ",
        ],
        correct: 1,
        why: "Task-based titles match what people are trying to do and what they search for. Feature-based titles like an overview or configuration parameters make people guess where their answer lives, and a FAQ page hides each answer among unrelated questions.",
      },
      {
        id: "h10-spot-manual-link",
        type: "spot",
        question: "Which part offers help that's hard to use when it's needed?",
        title: "Company details",
        parts: [
          {
            id: "name",
            label: "Field labeled Company name, with the hint As it appears on your invoices",
            html: `<div class="mk-label">Company name</div><div class="mk-muted">As it appears on your invoices</div><div class="mk-in">&nbsp;</div>`,
          },
          {
            id: "vat",
            label: "Field labeled VAT number, with a link: Read the tax guide (PDF, 120 pages)",
            html: `<div class="mk-label">VAT number</div><span class="mk-link">Read the tax guide (PDF, 120 pages)</span><div class="mk-in">&nbsp;</div>`,
          },
          {
            id: "country",
            label: "Dropdown labeled Country, showing Ireland",
            html: `<div class="mk-label">Country</div><div class="mk-in">Ireland ▾</div>`,
          },
          {
            id: "save",
            label: "Button: Save",
            html: `<span class="mk-btn">Save</span>`,
          },
        ],
        correct: "vat",
        why: "Someone stuck on one field shouldn't have to search a 120-page PDF. A one-line hint in place, such as where to find the number and what it looks like, answers the question right where it comes up. The company name field shows how that's done.",
      },
      {
        id: "h10-sort-help",
        type: "sort",
        question: "Which kinds of help appear where people need them, and which send them away from their task?",
        groups: ["In context", "Sends them away"],
        items: [
          { id: "hint", text: "A hint under a tricky field", group: 0 },
          { id: "tooltip", text: "A short explanation next to a confusing setting", group: 0 },
          { id: "expand", text: "A “What does this mean?” link that expands an explanation in place", group: 0 },
          { id: "pdf", text: "An 86-page PDF manual", group: 1 },
          { id: "footer", text: "A link to the help center home page in the footer", group: 1 },
          { id: "ticket", text: "Emailing support to ask what a field means", group: 1 },
        ],
        why: "The best help answers the question at the moment it comes up, without people leaving what they're doing. A hint, an explanation by the setting, or one that expands in place all do that. A long manual, a generic help center and a support ticket make people hunt for one answer, and many won't bother. The expanding explanation counts as in context because it opens right where the question comes up, without leaving the page.",
      },
    ],
  },
];

export const heuristicsPath: LearningPath = {
  id: "heuristics",
  title: "Nielsen's 10 usability heuristics",
  description: "Ten rules of thumb for spotting usability problems in any screen: clear feedback, familiar words, undo, consistency, preventing errors and more.",
  status: "live",
  lessons,
};
