import type { License, Lesson, LearningPath, Source } from "../types";

// Lesson text is original. GOV.UK content is Open Government Licence v3.0 and USWDS is public domain /
// CC0 (checked 2026-10-03); NN/g is summarized and linked.
const OGL: License = {
  name: "the Open Government Licence v3.0",
  url: "https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/",
};
const CC0: License = { name: "CC0 1.0 (public domain)", url: "https://creativecommons.org/publicdomain/zero/1.0/" };

const govuk = (path: string, title: string): Source => ({
  title: `GOV.UK Design System: ${title}`,
  url: `https://design-system.service.gov.uk/${path}/`,
  license: OGL,
});
const uswds = (path: string, title: string): Source => ({
  title: `USWDS: ${title}`,
  url: `https://designsystem.digital.gov/${path}/`,
  license: CC0,
});
const nng = (slug: string, title: string): Source => ({ title: `NN/g: ${title}`, url: `https://www.nngroup.com/articles/${slug}/` });

const btn = (text: string, cls = "") => `<span class="mk-btn${cls ? " " + cls : ""}">${text}</span>`;
const links = (items: string[]) => `<div class="mk-row">${items.map((t) => `<span class="mk-link">${t}</span>`).join("")}</div>`;

const lessons: Lesson[] = [
  {
    id: "ia1",
    code: "IA1",
    title: "What information architecture is",
    subtitle: "Structure that matches how people think",
    minutes: 5,
    skills: ["ia", "effort"],
    body: [
      "Information architecture (IA) is how content is organized, labeled and connected so people can find what they need and understand where they are. It sits underneath the screens: menus, search and page layouts are how people move through the structure, but the structure itself is the IA. A polished menu can't rescue groups that don't make sense to the people using them.",
      "The most common mistake is mirroring your own company: a section per department, named the way teams talk internally. Visitors don't know or care who owns what. They arrive with a task, like paying a bill or changing an address, and an idea of where it should live. Good IA starts from those tasks and expectations, which you learn through research rather than by guessing in a workshop.",
    ],
    practice: [
      "List the top tasks people come to do, and check each one has an obvious home.",
      "Group content by what people are trying to do, not by which team owns it.",
      "Collect the words customers use, from search logs, support tickets and interviews, before naming anything.",
      "Leave room to grow, so new content has a place without reshuffling everything.",
    ],
    fieldExercise:
      "Pick five common customer tasks and try to find each one in your product's navigation, starting from the home page. Note any task where you had to know which team owns it to know where to look.",
    sources: [
      nng("ia-vs-navigation", "The Difference Between Information Architecture (IA) and Navigation"),
      nng("top-10-ia-mistakes", "Top 10 Information Architecture (IA) Mistakes"),
      nng("mental-models", "Mental Models and User Experience Design"),
    ],
    exercises: [
      {
        id: "ia1-intranet-nav",
        type: "compare",
        question: "A company intranet's main menu. Which structure helps staff find what they need?",
        a: `<div class="mk"><div class="mk-title">Northwind intranet</div>${links(["Human Resources", "Finance", "Facilities", "IT Services", "Legal"])}<div class="mk-muted">Welcome back, Sam</div></div>`,
        b: `<div class="mk"><div class="mk-title">Northwind intranet</div>${links(["Pay and benefits", "Time off", "Travel and expenses", "Laptops and phones", "Policies"])}<div class="mk-muted">Welcome back, Sam</div></div>`,
        describe: {
          a: "An intranet's main menu with five links: Human Resources, Finance, Facilities, IT Services and Legal.",
          b: "An intranet's main menu with five links: Pay and benefits, Time off, Travel and expenses, Laptops and phones, and Policies.",
        },
        correct: "b",
        why: "B groups things by what staff come to do, so someone booking leave picks Time off straight away. A follows the company's departments, which looks orderly from the inside, but people first have to know who handles what: is a new laptop Facilities or IT? Are expenses Finance or HR? Every wrong guess costs a click and some trust.",
      },
      {
        id: "ia1-wrong-section",
        type: "choice",
        question: "Usability tests show people open the wrong section of the menu for most tasks. The team says, “The structure is fine; we just need a nicer menu.” What's most likely going on?",
        options: [
          "The groups and labels don't match how people think about the content",
          "The menu's visual style is too plain, so people overlook the right item",
          "The menu needs an icon beside each item so people can scan it faster",
          "There are too many sections, so the menu should be cut down to five",
        ],
        correct: 0,
        why: "People found the menu and chose a section, so they noticed it; they just chose wrong. That points to the structure underneath: groups and labels that don't match people's expectations. A new style or icons won't change where things live, and cutting sections to an arbitrary number usually makes the groups broader and vaguer.",
      },
      {
        id: "ia1-spot-team-name",
        type: "spot",
        question: "Which menu item is organized around the company rather than its customers?",
        title: "Bank website: main menu",
        parts: [
          { id: "current", label: "Link: Current accounts", html: `<span class="mk-link">Current accounts</span>` },
          { id: "savings", label: "Link: Savings", html: `<span class="mk-link">Savings</span>` },
          { id: "mortgages", label: "Link: Mortgages", html: `<span class="mk-link">Mortgages</span>` },
          { id: "lending", label: "Link: Consumer Lending Operations", html: `<span class="mk-link">Consumer Lending Operations</span>` },
        ],
        correct: "lending",
        why: "“Consumer Lending Operations” is the name of the team that runs loans. A customer looking for a personal or car loan won't guess it lives there; a label like “Loans” would work. The other items are named after the products people come for.",
      },
      {
        id: "ia1-sort-basis",
        type: "sort",
        question: "Which of these are a sound basis for grouping your navigation, and which aren't?",
        groups: ["Sound basis", "Poor basis"],
        items: [
          { id: "tasks", text: "The tasks customers come to do", group: 0 },
          { id: "cardsort", text: "How customers grouped your topics when asked to sort them", group: 0 },
          { id: "interviews", text: "How customers describe their needs in interviews", group: 0 },
          { id: "owner", text: "Which department owns each page", group: 1 },
          { id: "built", text: "The order the features were built in", group: 1 },
          { id: "codenames", text: "Internal project code names", group: 1 },
        ],
        why: "Structure should come from the people using it: their tasks, the groups they make and how they describe what they need. Ownership, build order and code names are useful inside the team, but visitors don't know them, so they can't use them to find anything. The department one is the trap: it feels tidy from the inside.",
      },
    ],
  },
  {
    id: "ia2",
    code: "IA2",
    title: "Organization schemes",
    subtitle: "Choose how to group things",
    minutes: 5,
    skills: ["ia", "effort"],
    body: [
      "Schemes come in two families. Exact schemes, such as alphabetical, by date or by location, give every item one right place, so they work when people already know the name, date or place: a staff directory, a list of invoices, store branches. Ambiguous schemes, such as by topic, task or audience, take judgement about where things belong, but they help people who know what they need without knowing its exact name.",
      "Most products use both, which is fine as long as each level of a menu sticks to one scheme. A menu that mixes an audience (“For business”), a topic (“Security”) and a task (“Get a quote”) in one list makes people wonder whether an item could be in two places. Take extra care with audience groups: people often don't know which group they're in, or they're in several.",
    ],
    practice: [
      "Use an exact scheme when people know the name, date or place they want.",
      "Use topic or task groups when people know their goal but not the item's name.",
      "Keep each level of a menu or list to one scheme.",
      "Only split by audience when the groups don't overlap and people can tell which one is theirs.",
    ],
    fieldExercise:
      "Mark each item in your product's main menu as topic, task, audience or exact. If one level mixes several, sketch a version that uses one.",
    sources: [nng("audience-based-navigation", "Audience-Based Navigation: 5 Reasons to Avoid It"), nng("category-names-suck", "5 Tips for Avoiding Confusing Category Names")],
    exercises: [
      {
        id: "ia2-directory",
        type: "compare",
        question: "A staff directory of 3,000 people. Someone knows a colleague's name and needs their phone number. Which layout helps?",
        a: `<div class="mk"><div class="mk-title">People</div><div class="mk-label">Name</div><div class="mk-in">&nbsp;</div><div class="mk-muted">A B C D E F G H I J K L M N O P Q R S T U V W X Y Z</div><div>Abbott, Grace</div><div>Adeyemi, Tunde</div><div>Ahmed, Sara</div></div>`,
        b: `<div class="mk"><div class="mk-title">People</div><div class="mk-cell">Engineering (412) ›</div><div class="mk-cell">Finance (96) ›</div><div class="mk-cell">Marketing (140) ›</div><div class="mk-cell">Operations (233) ›</div></div>`,
        describe: {
          a: "A People page with a Name search field, a row of letters A to Z, and a list starting Abbott, Grace; Adeyemi, Tunde; Ahmed, Sara.",
          b: "A People page listing departments with head counts: Engineering (412), Finance (96), Marketing (140) and Operations (233), each opening a list of its people.",
        },
        correct: "a",
        why: "When people know the exact name, an exact scheme gives it one obvious place: type it, or jump to the letter. Grouping by department makes them work out which team the person is in first, which they often don't know in a large company. Departments still make a useful filter, but not the only way in.",
      },
      {
        id: "ia2-recipes",
        type: "choice",
        question: "A recipe site has 4,000 recipes. Most visitors know roughly what they want, like “a quick vegetarian dinner”, but not a recipe's name. How should browsing work?",
        options: [
          "By meal, diet and cooking time, which people can combine",
          "Alphabetically by recipe name, with a letter index at the top",
          "By the date each recipe was published, with the newest first",
          "By the chef who wrote each recipe, with a photo of each chef",
        ],
        correct: 0,
        why: "Visitors know their goal, not the name, so they need groups that match how they think about cooking: which meal, which diet, how much time. An A–Z index only helps people who already know the name, newest first suits regular readers rather than someone with a specific need, and browsing by chef assumes visitors know whose recipes they want.",
      },
      {
        id: "ia2-spot-mixed",
        type: "spot",
        question: "Which item breaks the way the rest of this menu is grouped?",
        title: "Help center: browse by topic",
        parts: [
          { id: "billing", label: "Link: Billing and payments", html: `<span class="mk-link">Billing and payments</span>` },
          { id: "account", label: "Link: Account and sign-in", html: `<span class="mk-link">Account and sign-in</span>` },
          { id: "shipping", label: "Link: Shipping and returns", html: `<span class="mk-link">Shipping and returns</span>` },
          { id: "business", label: "Link: For small businesses", html: `<span class="mk-link">For small businesses</span>` },
          { id: "privacy", label: "Link: Privacy and security", html: `<span class="mk-link">Privacy and security</span>` },
        ],
        correct: "business",
        why: "Every other item is a topic, but “For small businesses” is an audience. A small business owner with a billing question can't tell whether to choose Billing or their own section, and everyone else wonders what's hidden there. Business-specific answers can sit inside the topics, marked as such.",
      },
      {
        id: "ia2-sort-scheme",
        type: "sort",
        question: "Which lists suit an exact scheme (A to Z, by date or by place), and which suit grouping by topic or task?",
        groups: ["Exact scheme", "Topic or task"],
        items: [
          { id: "invoices", text: "Invoices, for people looking up a specific month", group: 0 },
          { id: "glossary", text: "A glossary of finance terms", group: 0 },
          { id: "branches", text: "Store branches, for people choosing one near them", group: 0 },
          { id: "help", text: "Help articles, for people with a problem to solve", group: 1 },
          { id: "services", text: "Public services, for people who don't know the official name", group: 1 },
        ],
        why: "Exact schemes work when people know the precise thing they want: the month, the term, the town. When people only know their goal, like fixing a problem or finding a service whose official name they don't know, topic and task groups meet them where they are. The glossary is the one people misplace: it's full of topics, but people look up a term they already know, so A to Z works best.",
      },
    ],
  },
  {
    id: "ia3",
    code: "IA3",
    title: "Labels people understand",
    subtitle: "Name things in your users' words",
    minutes: 5,
    skills: ["ia", "language"],
    body: [
      "A navigation label is a promise about what's behind it. People choose where to go by scanning labels and following the one that seems closest to their goal, which researchers call information scent. Vague labels like “Resources”, “Solutions” or “More” give off almost no scent, and internal jargon or clever brand names send people the wrong way.",
      "Good labels use your audience's words, are specific enough to tell sections apart, and stay the same everywhere: the menu item, the page heading and the breadcrumb should match. Find the words in search logs, support tickets and research sessions, then test them, because the team's favorite term is rarely the one customers use.",
    ],
    practice: [
      "Use the words people type into search and support tickets.",
      "Replace vague labels like Resources, Solutions or More with what's actually there.",
      "Keep a link's label and the heading of the page it opens the same.",
      "Avoid pairs of labels that could mean the same thing, like Help and Support.",
    ],
    fieldExercise:
      "Read your top-level menu aloud to someone outside your team and ask what they'd expect to find under each label. Note any label where their guess doesn't match.",
    sources: [nng("information-scent", "Information Scent: How Users Decide Where to Go Next"), nng("better-link-labels", "Better Link Labels: 4Ss for Encouraging Clicks")],
    exercises: [
      {
        id: "ia3-vague-labels",
        type: "compare",
        question: "A software company's main menu. Which labels help visitors find pricing and setup guides?",
        a: `<div class="mk"><div class="mk-row"><b>Tallyo</b>${links(["Platform", "Solutions", "Resources", "Company"])}</div><div class="mk-big" style="font-size:18px">Invoicing for small teams</div></div>`,
        b: `<div class="mk"><div class="mk-row"><b>Tallyo</b>${links(["Features", "Pricing", "Guides", "About us"])}</div><div class="mk-big" style="font-size:18px">Invoicing for small teams</div></div>`,
        describe: {
          a: "A website header: the Tallyo logo and four links, Platform, Solutions, Resources and Company, above the headline Invoicing for small teams.",
          b: "A website header: the Tallyo logo and four links, Features, Pricing, Guides and About us, above the headline Invoicing for small teams.",
        },
        correct: "b",
        why: "B's labels say what's behind them, so someone after the price or a setup guide clicks straight there. A's labels are common on software sites, but each is broad enough to hold almost anything: pricing could be under Platform or Solutions, and guides under Resources or Company, so people open every menu to check.",
      },
      {
        id: "ia3-heading-match",
        type: "choice",
        question: "A menu link reads “Manage subscription”, but the page it opens is headed “Billing preferences”. What's the main risk?",
        options: [
          "People doubt they're on the right page and may go back to look",
          "Search engines will rank the page lower because the words differ",
          "Screen readers will announce the heading twice, which is tiring",
          "None, because both names describe roughly the same thing",
        ],
        correct: 0,
        why: "The heading is how people check that a link took them where they expected. When it uses different words, they hesitate, reread or go back to try another link. Ranking isn't the main concern, screen readers don't repeat the heading, and names that mean the same to the team don't to someone scanning for the words they just clicked.",
      },
      {
        id: "ia3-spot-jargon",
        type: "spot",
        question: "Which label would leave customers guessing?",
        title: "Online banking: menu",
        parts: [
          { id: "accounts", label: "Link: Accounts", html: `<span class="mk-link">Accounts</span>` },
          { id: "payments", label: "Link: Payments and transfers", html: `<span class="mk-link">Payments and transfers</span>` },
          { id: "mandates", label: "Link: Mandate management", html: `<span class="mk-link">Mandate management</span>` },
          { id: "statements", label: "Link: Statements", html: `<span class="mk-link">Statements</span>` },
        ],
        correct: "mandates",
        why: "“Mandate management” is the bank's term for direct debits and standing orders. Someone who wants to cancel a gym membership's direct debit will scan for those words, not this one. The other labels use everyday banking words.",
      },
      {
        id: "ia3-sort-labels",
        type: "sort",
        question: "Which menu labels say what's behind them, and which are too vague?",
        groups: ["Says what's there", "Too vague"],
        items: [
          { id: "pricing", text: "Pricing", group: 0 },
          { id: "orders", text: "Order history", group: 0 },
          { id: "return", text: "Return an item", group: 0 },
          { id: "resources", text: "Resources", group: 1 },
          { id: "solutions", text: "Solutions", group: 1 },
          { id: "discover", text: "Discover", group: 1 },
        ],
        why: "Pricing, Order history and Return an item each name what people will find, so they can rule a section in or out at a glance. Resources, Solutions and Discover could hold almost anything, so people have to open them to find out. Resources is the one people often accept because it's so common; it usually works better split into what it holds, like Guides or Webinars.",
      },
    ],
  },
  {
    id: "ia4",
    code: "IA4",
    title: "Breadth and depth",
    subtitle: "Shape the hierarchy",
    minutes: 5,
    skills: ["ia", "effort"],
    body: [
      "A hierarchy can be broad and shallow, with many choices at each level and few levels, or narrow and deep, with few choices and many levels. Deep hierarchies hide content behind a chain of clicks, and each click is another chance to guess wrong. Broad, shallow ones show more at once, which people handle well when the choices are clearly labeled and grouped.",
      "For most products, a fairly broad structure of two or three levels works best. The idea that menus need seven items or fewer doesn't apply to navigation people can see and scan, though a long, unsorted list still slows them down. What matters more is strong scent at every level, so people can tell which choice leads to their goal. Avoid categories with a single item, and catch-alls like “Other”.",
    ],
    practice: [
      "Aim for two or three levels, and go deeper only when the groups are very clear.",
      "Organize a long menu into labeled sections rather than adding levels.",
      "Merge categories with a single item, and avoid catch-alls like Other or Miscellaneous.",
      "Walk the click path to each top task: every step should have an obvious choice.",
    ],
    fieldExercise:
      "Pick your product's three most common tasks and count the clicks from the home page to each. For any path longer than three, note whether each step had an obvious choice.",
    sources: [nng("flat-vs-deep-hierarchy", "Flat vs. Deep Website Hierarchies"), nng("mega-menus-work-well", "Mega Menus Work Well for Site Navigation")],
    exercises: [
      {
        id: "ia4-returns-policy",
        type: "compare",
        question: "Someone wants a store's returns policy. Which help structure gets them there with fewer wrong turns?",
        a: `<div class="mk"><div class="mk-title">Help</div><div class="mk-grid"><div class="mk-cell"><b>Orders</b>Track an order<br>Change an order</div><div class="mk-cell"><b>Returns</b>Returns policy<br>Start a return</div><div class="mk-cell"><b>Payments</b>Payment methods<br>Refunds</div></div></div>`,
        b: `<div class="mk"><div class="mk-title">Help</div><div class="mk-cell">Customer service ›</div><div class="mk-cell">Your account ›</div><div class="mk-cell">About the shop ›</div><div class="mk-muted">Customer service › Policies › Orders › Returns policy</div></div>`,
        describe: {
          a: "A Help page with three labeled groups shown at once: Orders (Track an order, Change an order), Returns (Returns policy, Start a return) and Payments (Payment methods, Refunds).",
          b: "A Help page with three links: Customer service, Your account and About the shop. A note shows the returns policy's path: Customer service, then Policies, then Orders, then Returns policy.",
        },
        correct: "a",
        why: "A shows the topics and their articles on one page, so people scan for Returns and see the policy. B hides it four levels down, and every level is a guess: is a returns policy under Customer service or About the shop, Policies or Orders? Each wrong guess means backing out and starting again.",
      },
      {
        id: "ia4-long-menu",
        type: "choice",
        question: "An admin app's Settings menu has grown to 26 items in one unsorted list. What's the best fix?",
        options: [
          "Group the items under a few clear headings on the same page",
          "Nest them four levels deep so each level shows only a few",
          "Keep the seven most used and move the rest under “Other”",
          "Sort all 26 items by how often each one has been opened",
        ],
        correct: 0,
        why: "Headings break the list into chunks people can scan, and every item stays one click away. Nesting turns one long scan into a chain of guesses, a catch-all “Other” hides items behind a label that says nothing, and sorting by use keeps moving items around, so people can't learn where things are.",
      },
      {
        id: "ia4-spot-catchall",
        type: "spot",
        question: "Which menu item makes features harder to find?",
        title: "Project tool: main menu",
        parts: [
          { id: "projects", label: "Link: Projects", html: `<span class="mk-link">Projects</span>` },
          { id: "tasks", label: "Link: Tasks", html: `<span class="mk-link">Tasks</span>` },
          { id: "reports", label: "Link: Reports", html: `<span class="mk-link">Reports</span>` },
          { id: "other", label: "Link: Other, which holds Time tracking, Invoices and Integrations", html: `<span class="mk-link">Other</span><div class="mk-muted">Time tracking · Invoices · Integrations</div>` },
          { id: "team", label: "Link: Team", html: `<span class="mk-link">Team</span>` },
        ],
        correct: "other",
        why: "“Other” says nothing about what's inside, so nobody looking for time tracking or invoices will think to open it, and over time it collects everything nobody placed. Those features need homes under clear labels. Projects, Tasks, Reports and Team each say what they hold.",
      },
      {
        id: "ia4-sort-shape",
        type: "sort",
        question: "Which changes make a hierarchy easier to use, and which make it harder?",
        groups: ["Easier to use", "Harder to use"],
        items: [
          { id: "headings", text: "Grouping a long menu under clear headings", group: 0 },
          { id: "merge", text: "Merging categories that held a single item", group: 0 },
          { id: "landing", text: "Listing a section's pages on its overview page", group: 0 },
          { id: "level", text: "Adding a level so each menu shows only three items", group: 1 },
          { id: "other", text: "Moving rarely used pages into an Other menu", group: 1 },
        ],
        why: "Headings, merged single-item categories and overview pages that list their pages all let people see more and click less. Adding a level to keep menus tiny turns one scan into several guesses, and an Other menu hides pages behind a label that says nothing. The extra level is the one people misplace: short menus feel simpler, but the content just moves further away.",
      },
    ],
  },
  {
    id: "ia5",
    code: "IA5",
    title: "Wayfinding",
    subtitle: "Show people where they are",
    minutes: 5,
    skills: ["ia", "conventions"],
    body: [
      "Many people never see your home page: they land deep inside from a search engine, a shared link or an email. Wherever they arrive, they should be able to answer three questions: where am I, what's nearby, and where can I go next? A page heading that matches the link, the current section marked in the navigation, and breadcrumbs answer them without anyone having to think.",
      "Breadcrumbs show the page's place in the hierarchy, from the top level down, not the pages someone happened to visit; going back is the Back button's job. Mark the current menu item with more than color, such as a bar or bold text, and in code with aria-current so screen readers announce it too. Local navigation, a list of the other pages in the section, lets people move sideways without starting again from the top.",
    ],
    practice: [
      "Give every page a heading that matches the link that leads to it.",
      "Mark the current section in the navigation, visually and with aria-current.",
      "Use breadcrumbs that show location, not history, when the hierarchy is more than two levels deep.",
      "Show the other pages in a section, so people can move sideways.",
    ],
    fieldExercise:
      "Open a page deep inside your product from a search result or a direct link, as if you'd never seen the product. Without scrolling, can you tell which section you're in and how to reach its overview?",
    sources: [
      nng("breadcrumbs", "Breadcrumbs: 11 Design Guidelines for Desktop and Mobile"),
      nng("local-navigation", "Local Navigation Is a Valuable Orientation and Wayfinding Aid"),
      govuk("components/breadcrumbs", "Breadcrumbs"),
      uswds("components/breadcrumb", "Breadcrumb"),
    ],
    exercises: [
      {
        id: "ia5-landing",
        type: "compare",
        question: "Someone lands on this help article from a search engine. Which page tells them where they are?",
        a: `<div class="mk"><div class="mk-muted">Help › Billing › Refunds</div><div class="mk-title">How long refunds take</div><div class="mk-muted">Refunds reach your card within 5 working days.</div><div class="mk-cell">In Billing: Payment methods · Invoices · <b style="display:inline">Refunds</b></div></div>`,
        b: `<div class="mk"><span class="mk-link">‹ Back</span><div class="mk-title">How long refunds take</div><div class="mk-muted">Refunds reach your card within 5 working days.</div><div class="mk-muted">Was this article helpful? Yes · No</div></div>`,
        describe: {
          a: "A help article titled How long refunds take, with Help › Billing › Refunds above the title and a box below reading In Billing: Payment methods, Invoices, Refunds, with Refunds in bold.",
          b: "A help article titled How long refunds take, with a ‹ Back link above the title and “Was this article helpful? Yes, No” below the text. There's no other navigation.",
        },
        correct: "a",
        why: "A shows where the article sits and what's nearby, so people can move up to Billing or across to Invoices. In B, someone arriving from a search engine has nowhere useful to go: Back takes them out of your site, and nothing shows what else the help center covers.",
      },
      {
        id: "ia5-breadcrumbs",
        type: "choice",
        question: "What should a page's breadcrumbs show?",
        options: [
          "Where the page sits in the hierarchy, from the top level down",
          "The pages this person visited, in order, to retrace their steps",
          "The steps of the current task, such as cart, delivery and payment",
          "The most popular pages in this section of the site this week",
        ],
        correct: 0,
        why: "Breadcrumbs show location, so they're the same however someone arrived, and each level links to a broader page. A visit history differs for everyone and repeats the Back button. Steps in a task belong in a step indicator, and popular pages are a separate list that doesn't say where this page lives.",
      },
      {
        id: "ia5-spot-history",
        type: "spot",
        question: "Which part doesn't help people tell where this page lives?",
        title: "Arlo desk lamp",
        parts: [
          { id: "trail", label: "Breadcrumbs: Search results › Oak shelf › Search results › Arlo desk lamp", html: `<div class="mk-muted">Search results › Oak shelf › Search results › Arlo desk lamp</div>` },
          { id: "menu", label: "Menu: Furniture, Lighting and Storage, with Lighting marked as the current section", html: `<div class="mk-row"><span class="mk-link">Furniture</span><span class="mk-link"><b>Lighting</b></span><span class="mk-link">Storage</span></div>` },
          { id: "price", label: "Text: $59.00, in stock", html: `<div>$59.00 · In stock</div>` },
          { id: "cart", label: "Button: Add to cart", html: btn("Add to cart") },
        ],
        correct: "trail",
        why: "Those breadcrumbs replay the pages this person visited, so they change with every visit and never show that the lamp belongs under Lighting, then Desk lamps. Breadcrumbs should show location, like Home › Lighting › Desk lamps. The marked menu item, the price and the button all fit the page.",
      },
      {
        id: "ia5-sort-wayfinding",
        type: "sort",
        question: "Which of these help people tell where they are, and which don't?",
        groups: ["Shows where", "Doesn't show where"],
        items: [
          { id: "marked", text: "The current menu item in bold with a bar beside it", group: 0 },
          { id: "heading", text: "A page heading that matches the link people clicked", group: 0 },
          { id: "crumbs", text: "Breadcrumbs from the top level down to this page", group: 0 },
          { id: "title", text: "The same title, “Portal”, at the top of every page", group: 1 },
          { id: "history", text: "A trail of the pages visited in this session", group: 1 },
          { id: "unmarked", text: "A menu that looks the same on every page", group: 1 },
        ],
        why: "A marked menu item, a matching heading and location breadcrumbs each answer “where am I?” at a glance. A title that never changes and a menu with nothing marked leave people working it out from the content. The history trail is the tricky one: it looks like breadcrumbs, but it shows where someone has been, not where the page lives.",
      },
    ],
  },
  {
    id: "ia6",
    code: "IA6",
    title: "Search and filters",
    subtitle: "Help people narrow things down",
    minutes: 5,
    skills: ["ia", "effort"],
    body: [
      "Navigation and search work together. Browsing suits people who are exploring or don't know the right words; search suits people who can name what they want. Most people use both, so search can't make up for a structure that doesn't make sense, and good navigation doesn't make search unnecessary in a large product. Search logs are also a gift: frequent searches show what people can't find by browsing.",
      "Search should forgive typos and synonyms, keep the query in the box on the results page, and turn “no results” into a way forward. On large collections, add filters based on real attributes of the content, like size, price, date or status, that people can combine. Show which filters are on and how many results are left, with an easy way to clear them.",
    ],
    practice: [
      "Review your top searches: they show missing labels and gaps in the navigation.",
      "Handle typos, plurals and synonyms, and keep the query in the box on the results page.",
      "Build filters from attributes people care about, and let them combine several.",
      "Show the active filters and the result count, with a one-click way to clear them.",
    ],
    fieldExercise:
      "Search your product for a common task using a typo and then a synonym. Then apply two filters to a long list and check you can see what's applied and undo it easily.",
    sources: [
      nng("filters-vs-facets", "Filters vs. Facets: Definitions"),
      nng("search-no-results-serp", "3 Guidelines for Search Engine “No Results” Pages"),
      uswds("components/search", "Search"),
    ],
    exercises: [
      {
        id: "ia6-active-filters",
        type: "compare",
        question: "A support tool has 1,200 tickets. An agent has filtered the list down. Which design shows what they're looking at?",
        a: `<div class="mk"><div class="mk-row">${btn("Filters (3)", "sec")}<span class="mk-muted">Showing 14 tickets</span></div><div class="mk-cell">#4821 · Can't export invoices</div><div class="mk-cell">#4817 · Sign-in code not arriving</div></div>`,
        b: `<div class="mk"><div class="mk-row"><span class="mk-pill">Status: Open ✕</span><span class="mk-pill">Priority: Urgent ✕</span><span class="mk-pill">Assigned to: Me ✕</span></div><div class="mk-row"><span class="mk-muted">Showing 14 tickets</span><span class="mk-link">Clear all</span></div><div class="mk-cell">#4821 · Can't export invoices</div><div class="mk-cell">#4817 · Sign-in code not arriving</div></div>`,
        describe: {
          a: "A ticket list with a Filters (3) button and the text Showing 14 tickets. Which three filters are on is listed only inside the Filters panel, which is closed.",
          b: "A ticket list with three removable chips, Status: Open, Priority: Urgent and Assigned to: Me, then Showing 14 tickets and a Clear all link.",
        },
        correct: "b",
        why: "B shows exactly which filters shape the list and lets agents remove one with a click. A shows that three filters are on but not which ones, so when a ticket they expect is missing, they have to open the panel to find out why, and some will assume it was deleted.",
      },
      {
        id: "ia6-search-log",
        type: "choice",
        question: "The top search on your site is “cancel subscription”, even though there's a Cancel link under Account › Billing. What does this most likely tell you?",
        options: [
          "People can't find it by browsing, so check where it sits and how it's labeled",
          "Search is the quickest route to it, so the navigation doesn't need to change",
          "People are too impatient to browse, so the search box should be made bigger",
          "The menu link isn't needed, since nearly everyone searches for it anyway",
        ],
        correct: 0,
        why: "A top search for something already in the menu usually means people looked and didn't find it, so check its label and where it sits. Treating search as the fix leaves browsing broken for everyone who doesn't search, a bigger box doesn't explain why they needed it, and removing the menu link makes browsing fail every time.",
      },
      {
        id: "ia6-spot-no-results",
        type: "spot",
        question: "Which part leaves people stuck?",
        title: "Search results",
        parts: [
          { id: "box", label: "Search box containing: reciept", html: `<div class="mk-in">reciept</div>` },
          { id: "count", label: "Text: 0 results for “reciept”", html: `<div class="mk-title">0 results for “reciept”</div>` },
          { id: "filters", label: "Active filters: Status: Archived, Last 7 days", html: `<div class="mk-row"><span class="mk-pill">Status: Archived ✕</span><span class="mk-pill">Last 7 days ✕</span></div>` },
          { id: "advice", label: "Text: Try different keywords.", html: `<div class="mk-muted">Try different keywords.</div>` },
        ],
        correct: "advice",
        why: "“Try different keywords” leaves all the work to people: it doesn't suggest “receipt”, point out that two filters are narrowing the search, or offer to clear them. The search box keeps the query, the count is clear, and the filters are shown with a way to remove each.",
      },
      {
        id: "ia6-sort-browse-search",
        type: "sort",
        question: "In each situation, are people more likely to browse or to search?",
        groups: ["Browse", "Search"],
        items: [
          { id: "exploring", text: "Exploring what a new tool can do", group: 0 },
          { id: "noname", text: "Looking for a feature without knowing what it's called", group: 0 },
          { id: "comparing", text: "Comparing several options in one category", group: 0 },
          { id: "invoice", text: "Looking for invoice INV-2041", group: 1 },
          { id: "colleague", text: "Looking up a colleague by name", group: 1 },
          { id: "setting", text: "Finding a setting whose exact name they know", group: 1 },
        ],
        why: "People search when they can name what they want: an invoice number, a person, a setting. They browse when they're exploring, comparing, or don't know the right words, which is when navigation labels do the work. Not knowing a feature's name is the one people misplace: search needs words, so without them people browse.",
      },
    ],
  },
  {
    id: "ia7",
    code: "IA7",
    title: "Card sorting",
    subtitle: "Learn how people group things",
    minutes: 5,
    skills: ["ia", "research"],
    body: [
      "In a card sort, participants put topics written on cards into groups that make sense to them. In an open sort they create and name the groups themselves, which shows how they think about the content and what words they use. In a closed sort they place cards into groups you've defined, which checks whether your categories work. A hybrid sort lets them add groups of their own.",
      "Write cards in plain words that represent real content, and avoid repeating a word that matches a likely group name, or people will sort by matching words instead of meaning. Recruit people from your real audience, at least 15 for an open sort, because you're looking for patterns across people rather than individual problems. Treat the results as evidence, not a vote: look at which cards often go together, where people disagree, and the names they chose, then design a structure and test it.",
    ],
    practice: [
      "Use an open sort to discover groups and words, and a closed sort to check categories you've drafted.",
      "Write cards in plain words, without shared keywords that give the grouping away.",
      "Recruit at least 15 people from your real audience for an open sort.",
      "Look at cards that are often grouped together and cards people disagree on, not just the most common groups.",
    ],
    fieldExercise:
      "Write 20 of your product's pages or features on cards and ask two colleagues from other teams to group and name them, separately. Compare their groups with your navigation.",
    sources: [
      nng("card-sorting-definition", "Card Sorting: Uncover Users' Mental Models"),
      nng("card-sorting-how-many-users-to-test", "Card Sorting: How Many Users to Test"),
    ],
    exercises: [
      {
        id: "ia7-card-wording",
        type: "compare",
        question: "Two sets of cards for an open card sort of a bank's website. Which set will tell you more about how customers think?",
        a: `<div class="mk"><div class="mk-grid"><div class="mk-cell">Savings accounts</div><div class="mk-cell">Savings calculator</div><div class="mk-cell">Savings tips</div><div class="mk-cell">Loan accounts</div><div class="mk-cell">Loan calculator</div></div></div>`,
        b: `<div class="mk"><div class="mk-grid"><div class="mk-cell">Instant access account</div><div class="mk-cell">Interest calculator</div><div class="mk-cell">Building an emergency fund</div><div class="mk-cell">Personal loan</div><div class="mk-cell">Monthly repayment calculator</div></div></div>`,
        describe: {
          a: "Five cards: Savings accounts, Savings calculator, Savings tips, Loan accounts and Loan calculator.",
          b: "Five cards: Instant access account, Interest calculator, Building an emergency fund, Personal loan and Monthly repayment calculator.",
        },
        correct: "b",
        why: "In A, every card starts with Savings or Loan, so participants can group them by matching the first word without thinking about what each one is, and you learn little. B describes each item without a shared keyword, so people group by meaning, and you see whether they put calculators together or with the products they belong to.",
      },
      {
        id: "ia7-closed",
        type: "choice",
        question: "Your team has drafted five categories for a new help center and wants to check whether people can place articles in them. Which method fits?",
        options: [
          "A closed card sort, with your five categories as the groups",
          "An open card sort, where people create and name their own groups",
          "A survey asking people to rate each category name from 1 to 5",
          "An A/B test of two menu designs once the help center is live",
        ],
        correct: 0,
        why: "A closed sort tests exactly this: whether people put articles where you expect, in the categories you've drafted. An open sort is for discovering groups before you have any, ratings tell you whether names sound good rather than whether people can place things, and an A/B test after launch finds problems once real customers have already met them.",
      },
      {
        id: "ia7-spot-plan",
        type: "spot",
        question: "Which part of this card sort plan would skew the results?",
        title: "Card sort plan: help center",
        parts: [
          { id: "people", label: "Participants: 18 members of our support team", html: `<div><b>Participants:</b> 18 members of our support team</div>` },
          { id: "cards", label: "Cards: 45 help articles, each named in plain words", html: `<div><b>Cards:</b> 45 help articles, each named in plain words</div>` },
          { id: "type", label: "Type: open sort, where people create and name their own groups", html: `<div><b>Type:</b> open sort, where people create and name their own groups</div>` },
          { id: "analysis", label: "Analysis: cards often grouped together, and cards people disagree on", html: `<div><b>Analysis:</b> cards often grouped together, and cards people disagree on</div>` },
        ],
        correct: "people",
        why: "Support staff know the product and its internal terms far better than customers, so they'll group articles the way the company thinks, which is exactly what the sort should get past. Recruit customers who use the help center. The plain-word cards, the open sort and the analysis plan are all sound.",
      },
      {
        id: "ia7-sort-type",
        type: "sort",
        question: "Which questions does an open card sort answer, and which does a closed sort answer?",
        groups: ["Open sort", "Closed sort"],
        items: [
          { id: "groups", text: "What groups would people make on their own?", group: 0 },
          { id: "words", text: "What would people call those groups?", group: 0 },
          { id: "related", text: "Which topics do people see as related?", group: 0 },
          { id: "draft", text: "Do our five draft categories make sense?", group: 1 },
          { id: "newfeature", text: "Which of our existing sections would people put a new feature in?", group: 1 },
        ],
        why: "An open sort shows how people think: the groups they'd make, the names they'd use and which topics feel related. A closed sort starts from your categories and shows whether people place things where you expect. Placing a new feature is a closed-sort question: the sections already exist, and you're checking where it fits.",
      },
    ],
  },
  {
    id: "ia8",
    code: "IA8",
    title: "Tree testing",
    subtitle: "Test the structure before the screens",
    minutes: 5,
    skills: ["ia", "research"],
    body: [
      "A tree test checks whether people can find things in your hierarchy with no visual design at all. Participants see only a clickable text version of your menu, the tree, and get tasks like “Where would you go to change your delivery address?”. With no layout, images or search to help, you see how well the structure and labels work on their own.",
      "Write tasks from real top tasks, in the customer's words, and don't use the label people should pick, or you're only testing word matching. For each task, look at how many people succeeded, how many went straight there without backtracking, and where they clicked first, since a wrong first click often leads to failure. Tree tests pair well with card sorts: sort to explore, build a structure, then test it, fix it and test again.",
    ],
    practice: [
      "Test the tree as plain text, at least the top three levels.",
      "Write tasks from top tasks without using the labels people should click.",
      "Check success, directness and first clicks for every task.",
      "Fix the labels and groups that fail, then test the revised tree again.",
    ],
    fieldExercise:
      "Write one of your product's menus as an indented text list. Ask a colleague from another team to find three things in it, thinking aloud, and note where they click first.",
    sources: [
      nng("tree-testing", "Tree Testing: Evaluate Menu Labels and Categories"),
      nng("card-sorting-tree-testing-differences", "Card Sorting vs. Tree Testing"),
    ],
    exercises: [
      {
        id: "ia8-task-wording",
        type: "compare",
        question: "Two ways to write the same tree test task. Which will tell you more about the structure?",
        a: `<div class="mk"><div class="mk-label">Task 4 of 8</div><div>You've just moved to 14 Elm Road. Where would you go so your next order arrives there?</div></div>`,
        b: `<div class="mk"><div class="mk-label">Task 4 of 8</div><div>Where would you go to change your Delivery address in your Account settings?</div></div>`,
        describe: {
          a: "A task card, Task 4 of 8: “You've just moved to 14 Elm Road. Where would you go so your next order arrives there?”",
          b: "A task card, Task 4 of 8: “Where would you go to change your Delivery address in your Account settings?” The tree has sections called Account settings and Delivery address.",
        },
        correct: "a",
        why: "A describes a real situation in everyday words, so people have to decide which section fits, which is what the test measures. B uses the exact labels people should click, Account settings and Delivery address, so they just match words, and the task passes even if the structure has problems.",
      },
      {
        id: "ia8-directness",
        type: "choice",
        question: "In a tree test, 70% of people found the right page for a task, but most of them first went into the wrong section and backed out. What does that tell you?",
        options: [
          "People get there only after a detour, so check the top-level labels",
          "The task passed overall, so its part of the structure is working fine",
          "The participants weren't paying attention, so recruit a new group",
          "Tree tests are unreliable, so A/B test the live site's menu instead",
        ],
        correct: 0,
        why: "Success alone hides the detour: people found it, but only after guessing wrong, which on a real site means extra clicks and some people giving up. Low directness points to a top-level label or group that pulls people the wrong way. Calling it a pass ignores that, blaming participants ignores a pattern across most of them, and a live A/B test is a slower, costlier way to learn the same thing.",
      },
      {
        id: "ia8-spot-plan",
        type: "spot",
        question: "Which part of this tree test plan undermines the results?",
        title: "Tree test plan: online store",
        parts: [
          { id: "tree", label: "Tree: the store's menu as plain text, including Help, then Returns policy", html: `<div><b>Tree:</b> the store's menu as plain text, including Help › Returns policy</div>` },
          { id: "people", label: "Participants: 50 people who shopped online in the last month", html: `<div><b>Participants:</b> 50 people who shopped online in the last month</div>` },
          { id: "task", label: "Task 3: Find the returns policy", html: `<div><b>Task 3:</b> Find the returns policy</div>` },
          { id: "measures", label: "Results: success, directness and first click for each task", html: `<div><b>Results:</b> success, directness and first click for each task</div>` },
        ],
        correct: "task",
        why: "Task 3 uses the exact label people should click, so they can find it by matching words rather than by understanding the structure. Something like “The jacket you bought doesn't fit. Where would you check whether you can send it back?” tests the tree. The plain-text tree, the participants and the measures are all sound.",
      },
      {
        id: "ia8-sort-method",
        type: "sort",
        question: "Which method answers each question: card sorting or tree testing?",
        groups: ["Card sort", "Tree test"],
        items: [
          { id: "group", text: "How do customers group our products?", group: 0 },
          { id: "call", text: "What would customers call this section?", group: 0 },
          { id: "together", text: "Which topics do people expect to find together?", group: 0 },
          { id: "warranty", text: "Can people find the warranty page in our new menu?", group: 1 },
          { id: "wrongway", text: "Which top-level label leads people the wrong way?", group: 1 },
          { id: "fixed", text: "Did our label changes fix last round's problems?", group: 1 },
        ],
        why: "Card sorting explores: it shows how people group things and what they call them, before you commit to a structure. Tree testing evaluates a structure you already have, measuring whether people can find specific items and where they go wrong. Checking whether label changes worked is a tree test question, because you're measuring finding, not grouping.",
      },
    ],
  },
];

export const informationArchitecturePath: LearningPath = {
  id: "information-architecture",
  title: "Information architecture",
  description: "Organizing and labeling content, breadth and depth, wayfinding, search and filters, and testing structures with card sorts and tree tests.",
  status: "live",
  lessons,
};
