import type { License, Lesson, LearningPath, Source } from "../types";

// Lesson text is original. GOV.UK content is Open Government Licence v3.0 and USWDS is public domain /
// CC0 (checked 2026-10-02); NN/g, Material Design and W3C are summarized and linked.
const OGL: License = {
  name: "the Open Government Licence v3.0",
  url: "https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/",
};
const CC0: License = { name: "CC0 1.0 (public domain)", url: "https://creativecommons.org/publicdomain/zero/1.0/" };

const govuk = (path: string, title: string): Source => ({
  title: `GOV.UK Design System: ${title}`,
  url: `https://design-system.service.gov.uk/${path}/`,
  license: OGL,
});
const uswds = (path: string, title: string): Source => ({
  title: `USWDS: ${title}`,
  url: `https://designsystem.digital.gov/${path}/`,
  license: CC0,
});
const nng = (slug: string, title: string): Source => ({ title: `NN/g: ${title}`, url: `https://www.nngroup.com/articles/${slug}/` });
const understanding = (slug: string, title: string): Source => ({
  title: `WCAG 2.2 Understanding: ${title}`,
  url: `https://www.w3.org/WAI/WCAG22/Understanding/${slug}.html`,
});

const btn = (text: string, cls = "") => `<span class="mk-btn${cls ? " " + cls : ""}">${text}</span>`;

const lessons: Lesson[] = [
  {
    id: "i1",
    code: "I1",
    title: "Affordances and signifiers",
    subtitle: "Show what can be done",
    minutes: 5,
    skills: ["conventions", "layout"],
    body: [
      "An affordance is what you can do with something; a signifier is the cue that tells you so. On a screen everything is flat pixels, so people rely on signifiers: a button's shape and fill, the underline on a link, the border and cursor of a text field, the grip on something you can drag. When those cues are missing, people miss actions or click on things that do nothing.",
      "Use signifiers people already know, and use them consistently: if a solid blue shape means “press me” in one place, don't use it for a static label somewhere else. Watch for false signifiers too, like underlined text that isn't a link or a card that looks clickable but isn't. A flat, minimal style is fine, as long as interactive things still look interactive.",
    ],
    practice: [
      "Give every interactive element at least one strong cue: a button shape, an underline, a border, an arrow or an icon with a label.",
      "Keep cues consistent, so the same style always means the same kind of action.",
      "Remove false signifiers: don't underline or color plain text like links.",
      "Add hover and focus states, but don't rely on them: on touch screens there's no hover to reveal anything.",
    ],
    fieldExercise:
      "Take a screenshot of one screen in your product and circle everything that's interactive. Show it to a colleague without the circles and ask them to point at what they could click.",
    sources: [
      nng("clickable-elements", "Beyond Blue Links: Making Clickable Elements Recognizable"),
      nng("flat-ui-less-attention-cause-uncertainty", "Flat UI Elements Attract Less Attention and Cause Uncertainty"),
    ],
    exercises: [
      {
        id: "i1-open-report",
        type: "compare",
        question: "A list of saved reports. Which design makes it clear that you can open each one?",
        a: `<div class="mk"><div class="mk-title">Saved reports</div><div>Q3 revenue</div><div>Churn by region</div><div>Support volume</div></div>`,
        b: `<div class="mk"><div class="mk-title">Saved reports</div><div class="mk-cell">Q3 revenue ›</div><div class="mk-cell">Churn by region ›</div><div class="mk-cell">Support volume ›</div></div>`,
        describe: {
          a: "A Saved reports list: Q3 revenue, Churn by region, Support volume, shown as plain lines of text with no borders or icons.",
          b: "A Saved reports list: Q3 revenue, Churn by region, Support volume, each in its own bordered box with an arrow at the end.",
        },
        correct: "b",
        why: "In B each report sits in a box with an arrow, a familiar cue that the row opens something. In A the reports look like plain text, so many people won't try clicking them and will look for a separate Open button that isn't there.",
      },
      {
        id: "i1-false-signifier",
        type: "choice",
        question: "On a settings page, every section title is blue and underlined, but clicking one does nothing. What's the problem?",
        options: [
          "They look like links, so people click and assume the page is broken",
          "Blue text is harder to read than black text, especially for long titles",
          "Underlines make the page look dated, which hurts trust in the product",
          "Nothing, because blue underlined titles stand out well on the page",
        ],
        correct: 0,
        why: "Blue underlined text is one of the strongest signals on the web that something is a link. Using it for static titles promises an action that doesn't exist, and it also makes the real links on the page less trustworthy. The color itself isn't the issue, and standing out isn't worth breaking that expectation.",
      },
      {
        id: "i1-spot-false-link",
        type: "spot",
        question: "Which part promises an action it doesn't have?",
        title: "Report: Q3 revenue",
        parts: [
          { id: "total", label: "Text: Revenue $482,000", html: `<div class="mk-big" style="font-size:20px">$482,000</div>` },
          { id: "updated", label: "Text: Last updated 2 October, blue and underlined like the links on the page, but not a link", html: `<div style="color:var(--accent);text-decoration:underline">Last updated 2 October</div>` },
          { id: "full", label: "Link: View full report", html: `<span class="mk-link">View full report</span>` },
          { id: "export", label: "Button: Export", html: btn("Export") },
        ],
        correct: "updated",
        why: "The date is styled exactly like a link, so people will click it expecting a change history, and nothing will happen. It should be plain text. The link, the button and the revenue figure all look like what they are.",
      },
      {
        id: "i1-sort-signifiers",
        type: "sort",
        question: "Which of these signal that something is interactive, and which don't?",
        groups: ["Signals interactive", "Doesn't signal it"],
        items: [
          { id: "underline", text: "Underlined text in the link color", group: 0 },
          { id: "button", text: "A button with a solid fill and a label", group: 0 },
          { id: "field", text: "A text field with a border and a blinking cursor", group: 0 },
          { id: "gray", text: "Plain gray text with no underline", group: 1 },
          { id: "icon", text: "A small icon with no border, label or hover change", group: 1 },
          { id: "card", text: "A card with no arrow, border or hover change", group: 1 },
        ],
        why: "Underlines, button shapes and field borders are learned cues that say “you can act here”. Plain text, a bare icon and a flat card give people nothing to go on, so even when they're clickable, many people won't realize it. If something is interactive, give it at least one clear cue.",
      },
    ],
  },
  {
    id: "i2",
    code: "I2",
    title: "Component states",
    subtitle: "Design every state, not just the default",
    minutes: 5,
    skills: ["feedback", "accessibility"],
    body: [
      "Interactive elements move through states: default, hover (on devices with a pointer), keyboard focus, pressed, disabled and loading, and sometimes selected, error or success. Each state answers a question people have in that moment: can I use this, am I on it, did it register, is it working?",
      "Design every state, not just the default. Make keyboard focus clearly visible, show a pressed or loading state so people don't press twice, and when something is disabled, say why or how to enable it rather than leaving people guessing. Don't show a state with color alone: pair it with a label, an icon or a change in shape.",
    ],
    practice: [
      "List every state for each component, and design each one before building it.",
      "Show a loading state right after a press, and block repeat presses while it's working.",
      "Make focus visible with a clear outline that contrasts with the background.",
      "Pair color with text or an icon for selected, error and on or off states.",
    ],
    fieldExercise:
      "Tab through one form in your product without a mouse, then press its main button twice quickly. Note any state that's missing, invisible or confusing.",
    sources: [
      nng("button-states-communicate-interaction", "Button States: Communicate Interaction"),
      { title: "Material Design 3: Interaction states", url: "https://m3.material.io/foundations/interaction/states/overview" },
      understanding("focus-visible", "Focus Visible"),
      govuk("components/button", "Button"),
    ],
    exercises: [
      {
        id: "i2-double-pay",
        type: "compare",
        question: "Someone presses Pay. Which button state stops them from paying twice?",
        a: `<div class="mk"><div class="mk-title">Electricity bill</div><div class="mk-muted">October · $86.40</div><div class="mk-row">${btn("◌ Processing payment…", "sec")}</div></div>`,
        b: `<div class="mk"><div class="mk-title">Electricity bill</div><div class="mk-muted">October · $86.40</div><div class="mk-row">${btn("Pay $86.40")}</div></div>`,
        describe: {
          a: "Right after it's pressed, the button changes to an outlined style with a spinner and reads “Processing payment…”, and it can't be pressed again.",
          b: "Right after it's pressed, the button still reads “Pay $86.40” and looks exactly as it did before.",
        },
        correct: "a",
        why: "A confirms the press registered and blocks a second one while the payment goes through. In B nothing changes, so people wonder if their tap worked and press again, which can mean a double payment or a confusing error.",
      },
      {
        id: "i2-disabled",
        type: "choice",
        question: "A Submit button stays disabled until the form is valid, with no explanation. What's the main problem?",
        options: [
          "People can't tell what's missing, so they're stuck guessing",
          "Disabled buttons are never allowed under accessibility guidelines",
          "The button should be hidden completely until the form is valid",
          "Gray buttons look unprofessional and make the form feel broken",
        ],
        correct: 0,
        why: "A disabled button says “not yet” without saying why, so people scan the form looking for what they missed. Either keep the button enabled and show clear errors when it's pressed, or explain what's still needed. Hiding the button is worse, since people can't even see where they're heading.",
      },
      {
        id: "i2-spot-color-only",
        type: "spot",
        question: "Which control shows its state in a way some people can't read?",
        title: "Notification settings",
        parts: [
          { id: "email", label: "Toggle: Email updates, with the word On next to it", html: `<div class="mk-row"><span>Email updates</span><span class="mk-pill">On</span></div>` },
          { id: "sms", label: "Toggle: SMS alerts, showing its state only by switching from gray to green, with no On or Off text", html: `<div class="mk-row"><span>SMS alerts</span><span class="mk-dot good"></span></div>` },
          { id: "note", label: "Text: Changes apply to all your devices", html: `<div class="mk-muted">Changes apply to all your devices</div>` },
          { id: "save", label: "Button: Save changes", html: btn("Save changes") },
        ],
        correct: "sms",
        why: "Showing on and off only as gray versus green fails people who can't tell those colors apart, and gives screen reader users nothing unless it's coded properly. Adding the words On and Off, like the email toggle, fixes it. The note and the Save button are fine.",
      },
      {
        id: "i2-sort-states",
        type: "sort",
        question: "Which button states appear before someone presses it, and which appear after?",
        groups: ["Before pressing", "After pressing"],
        items: [
          { id: "hover", text: "Hover", group: 0 },
          { id: "focus", text: "Keyboard focus", group: 0 },
          { id: "disabled", text: "Disabled", group: 0 },
          { id: "loading", text: "Loading", group: 1 },
          { id: "success", text: "Success", group: 1 },
          { id: "error", text: "Error", group: 1 },
        ],
        why: "Hover, focus and disabled tell people about a control before they use it: that they're on it, or that it isn't available yet. Loading, success and error report what happened after the press. A component needs both kinds, and missing after-states are the ones that lead to double presses and confusion.",
      },
    ],
  },
  {
    id: "i3",
    code: "I3",
    title: "Response time and loading",
    subtitle: "What to show while people wait",
    minutes: 5,
    skills: ["feedback"],
    body: [
      "How long something takes changes what people need to see. Under about a tenth of a second, a response feels instant. Up to about a second, people notice the delay but keep their train of thought, so the response to the action itself is enough. Longer than that, show that something is working, such as a spinner, and for anything over about ten seconds, show how far along it is and let people do something else or cancel.",
      "When content takes a moment to appear, a skeleton screen, gray shapes where the content will go, shows the layout is coming and feels quicker than a blank page. Use a spinner for short waits you can't measure and a progress bar when you can. Better still, make the wait shorter: show what's ready first, or update the screen straight away and save in the background.",
    ],
    practice: [
      "Respond to every action within a tenth of a second, even if it's only a pressed state.",
      "For waits over a second, show a spinner or a skeleton screen.",
      "For long tasks, show progress and time left, and let people leave and come back.",
      "Load what's on screen first, and save in the background where it's safe to.",
    ],
    fieldExercise:
      "Time the five slowest actions in your product on a phone connection. For each, write down what the screen shows during the wait, and whether it matches how long it takes.",
    sources: [
      nng("response-times-3-important-limits", "Response Time Limits"),
      nng("progress-indicators", "Progress Indicators Make a Slow System Less Insufferable"),
      nng("skeleton-screens", "Skeleton Screens 101"),
    ],
    exercises: [
      {
        id: "i3-skeleton",
        type: "compare",
        question: "A dashboard takes two seconds to load. Which loading screen helps more?",
        a: `<div class="mk"><div class="mk-title">Dashboard</div><div class="mk-grid"><div class="mk-cell">&nbsp;</div><div class="mk-cell">&nbsp;</div><div class="mk-cell">&nbsp;</div><div class="mk-cell">&nbsp;</div></div></div>`,
        b: `<div class="mk" style="min-height:120px"><div class="mk-title">Dashboard</div><div class="mk-muted" style="text-align:center;margin-top:24px">◌ Loading…</div></div>`,
        describe: {
          a: "The Dashboard title above four empty gray card outlines, in the layout the dashboard's cards will appear in.",
          b: "The Dashboard title above an empty area with a spinner and the word “Loading…” in the middle.",
        },
        correct: "a",
        why: "Both show that something is happening. A also shows where the cards will appear, so the wait feels shorter and the page doesn't jump when the data arrives. B's spinner is fine for a short wait, but the layout appears all at once at the end, which feels slower and can make people lose their place.",
      },
      {
        id: "i3-long-task",
        type: "choice",
        question: "Generating a yearly tax report takes about 40 seconds. What should the screen do?",
        options: [
          "Show progress and time left, and let people leave and get notified",
          "Show a spinner in the middle of the screen until the report is ready",
          "Freeze the screen until it's done, so people can't click anything by mistake",
          "Show nothing, so the wait isn't distracting while the report generates",
        ],
        correct: 0,
        why: "Forty seconds is long enough for people to wonder if it's stuck, so they need to see progress and how long is left, and ideally get on with something else. A spinner alone gives no sense of time, freezing the screen traps people, and showing nothing makes them assume it failed.",
      },
      {
        id: "i3-spot-silent",
        type: "spot",
        question: "Which part leaves people unsure whether anything is happening?",
        title: "Import contacts",
        parts: [
          { id: "file", label: "Text: contacts.csv, 2,400 rows", html: `<div>contacts.csv · 2,400 rows</div>` },
          { id: "import", label: "Button: Import. It was pressed 20 seconds ago, and nothing on the screen has changed since.", html: btn("Import") },
          { id: "template", label: "Link: Download a template", html: `<span class="mk-link">Download a template</span>` },
          { id: "dupes", label: "Text: We'll skip duplicates automatically", html: `<div class="mk-muted">We'll skip duplicates automatically</div>` },
        ],
        correct: "import",
        why: "Twenty seconds with no visible change makes people think the import failed, so they press again or give up. The button should switch to a progress state, like “Importing 1,200 of 2,400…”. The file details, the template link and the note about duplicates are fine.",
      },
      {
        id: "i3-sort-indicator",
        type: "sort",
        question: "Which waits need only a spinner, and which need a progress bar?",
        groups: ["A spinner is enough", "Show a progress bar"],
        items: [
          { id: "search", text: "Loading search results, which takes about two seconds", group: 0 },
          { id: "signin", text: "Signing in", group: 0 },
          { id: "refresh", text: "Refreshing a news feed", group: 0 },
          { id: "upload", text: "Uploading a 500 MB video", group: 1 },
          { id: "export", text: "Exporting 10,000 rows to a spreadsheet", group: 1 },
          { id: "install", text: "Installing a software update", group: 1 },
        ],
        why: "Short waits of a few seconds just need a sign that something is happening, so a spinner is enough. Long tasks need a progress bar, because people want to know how far along it is and whether to wait or come back later. The rule of thumb: if it can take longer than about ten seconds, show progress.",
      },
    ],
  },
  {
    id: "i4",
    code: "I4",
    title: "Navigation patterns",
    subtitle: "Tabs, menus, breadcrumbs and when to use each",
    minutes: 5,
    skills: ["conventions", "layout"],
    body: [
      "Each navigation pattern fits a different job. Tabs switch between a few views of the same thing, like Details, Activity and Settings for one project. A sidebar or top bar moves between the main areas of a product. Breadcrumbs show where a page sits in a hierarchy and let people step back up. A menu behind an icon saves space but hides the options, so people use them less.",
      "Pick the pattern that matches the structure, then keep it predictable: the current location clearly marked, the same items in the same order on every page, and labels in plain words. On small screens, keep the most important destinations visible, such as a bottom bar of four or five, rather than hiding everything in one menu.",
    ],
    practice: [
      "Use tabs only for views of the same thing that people can visit in any order.",
      "Mark the current page or tab in more than one way, like bold text plus an underline.",
      "Keep navigation items in the same place and order across the product.",
      "On phones, show the top destinations in a bottom bar instead of hiding them all.",
    ],
    fieldExercise:
      "Open five pages in your product and check the navigation on each. Is the current location marked, and are the items in the same place and order every time?",
    sources: [
      nng("tabs-used-right", "Tabs, Used Right"),
      nng("breadcrumbs", "Breadcrumbs: 11 Design Guidelines for Desktop and Mobile"),
      nng("hamburger-menus", "Hamburger Menus and Hidden Navigation Hurt UX Metrics"),
      govuk("components/tabs", "Tabs"),
    ],
    exercises: [
      {
        id: "i4-current-location",
        type: "compare",
        question: "A project's navigation, while viewing its tasks. Which version shows where you are?",
        a: `<div class="mk"><div class="mk-row"><span>Overview</span><span>Tasks</span><span>Files</span><span>Settings</span></div><div class="mk-muted">12 open tasks</div></div>`,
        b: `<div class="mk"><div class="mk-row"><span>Overview</span><span style="font-weight:700;border-bottom:3px solid var(--accent)">Tasks</span><span>Files</span><span>Settings</span></div><div class="mk-muted">12 open tasks</div></div>`,
        describe: {
          a: "A row of navigation items, Overview, Tasks, Files and Settings, all in the same plain style, above the text “12 open tasks”.",
          b: "A row of navigation items, Overview, Tasks, Files and Settings, with Tasks in bold and underlined by a thick colored bar, above the text “12 open tasks”.",
        },
        correct: "b",
        why: "B marks the current section with weight and an underline, so people can see at a glance where they are and what else is nearby. In A every item looks the same, so people have to work out their location from the content below, which is slower and easy to get wrong.",
      },
      {
        id: "i4-tabs-for-steps",
        type: "choice",
        question: "A team uses tabs for the steps of a sign-up process: Account, Company, Billing. What's the problem?",
        options: [
          "Tabs suggest views in any order, but these steps have a set order",
          "There should be more tabs, so each step has fewer fields on it",
          "Tabs only work on desktop screens and break on phones",
          "The tab labels should be icons instead of words to save space",
        ],
        correct: 0,
        why: "Tabs say “these are parallel views; jump between them freely”. Sign-up steps depend on each other and need to be done in order, so a step-by-step flow with Continue and Back fits better. More tabs or icons wouldn't fix the mismatch, and tabs work fine on phones when they're used for the right thing.",
      },
      {
        id: "i4-spot-hidden-nav",
        type: "spot",
        question: "Which part makes this app's main areas hard to discover?",
        title: "Today",
        parts: [
          { id: "list", label: "List: 3 tasks due today", html: `<div>3 tasks due today</div>` },
          { id: "add", label: "Button: Add task", html: btn("Add task") },
          { id: "menu", label: "Navigation: Inbox, Calendar, Projects and Tasks, all hidden behind a menu icon with no label", html: `<div class="mk-row"><span aria-hidden="true">☰</span></div>` },
          { id: "summary", label: "Text: You finished 4 tasks yesterday", html: `<div class="mk-muted">You finished 4 tasks yesterday</div>` },
        ],
        correct: "menu",
        why: "Hiding every main area behind one unlabeled icon means people don't see what the app offers, so they use those areas less. On a phone, a bottom bar with four or five labeled destinations keeps them in view. The task list, the Add task button and the summary are fine.",
      },
      {
        id: "i4-sort-pattern",
        type: "sort",
        question: "Which of these suit tabs, and which suit the product's main navigation?",
        groups: ["Tabs", "Main navigation"],
        items: [
          { id: "project", text: "Details, Activity and Settings for one project", group: 0 },
          { id: "report", text: "Monthly and yearly views of one report", group: 0 },
          { id: "product", text: "Description, Reviews and Specs on one product page", group: 0 },
          { id: "areas", text: "Home, Projects, Reports and Billing across the product", group: 1 },
          { id: "email", text: "Inbox, Calendar and Contacts in an email app", group: 1 },
        ],
        why: "Tabs switch between views of the same thing, so they belong inside a page about one project, report or product. Main navigation moves between different areas of the product, so it belongs in a persistent sidebar, top bar or bottom bar. Mixing them up makes people unsure whether they've left the page.",
      },
    ],
  },
  {
    id: "i5",
    code: "I5",
    title: "Progressive disclosure",
    subtitle: "Show the basics, reveal the rest",
    minutes: 5,
    skills: ["effort", "layout"],
    body: [
      "Progressive disclosure means showing the options most people need first, and revealing the rest only when someone asks. A search box with an Advanced search link, a form that asks follow-up questions only after a relevant answer, and an expandable details section are all examples. It keeps screens simple for newcomers without taking power away from experts.",
      "It works only if the right things are up front and the rest is easy to find. If people often need a hidden option, it shouldn't be hidden. Label the reveal clearly (“Show 9 more filters”, not “More”), keep to one level where you can, and never hide things people must see to decide, like costs or required steps.",
    ],
    practice: [
      "Use real usage data to decide what goes up front and what can wait.",
      "Give the reveal a specific label that says what's behind it.",
      "Keep hidden options one click away, not buried several levels deep.",
      "Never hide prices, fees, risks or required steps.",
    ],
    fieldExercise:
      "Pick your product's busiest settings page. Using analytics or a quick poll, sort its options into used often and used rarely, and sketch a version that shows only the first group up front.",
    sources: [
      nng("progressive-disclosure", "Progressive Disclosure"),
      govuk("components/details", "Details"),
      uswds("components/accordion", "Accordion"),
    ],
    exercises: [
      {
        id: "i5-filters",
        type: "compare",
        question: "A clothing store's search results. Which filter panel suits most shoppers?",
        a: `<div class="mk"><div class="mk-title">Filters</div><div class="mk-muted">Price · Size · Brand · Color · Material · Fit · Sleeve length · Neckline · Pattern · Occasion · Care · Rating</div></div>`,
        b: `<div class="mk"><div class="mk-title">Filters</div><div class="mk-muted">Price · Size · Brand</div><span class="mk-link">Show 9 more filters</span></div>`,
        describe: {
          a: "A Filters panel listing all twelve filters at once: Price, Size, Brand, Color, Material, Fit, Sleeve length, Neckline, Pattern, Occasion, Care and Rating.",
          b: "A Filters panel showing Price, Size and Brand, with a link underneath: Show 9 more filters.",
        },
        correct: "b",
        why: "B shows the three filters most shoppers use and keeps the other nine one click away, so the panel is quick to scan without losing anything. A puts all twelve in front of everyone, which makes the common ones slower to find, especially on a phone.",
      },
      {
        id: "i5-hidden-fee",
        type: "choice",
        question: "A checkout hides the delivery fee in a collapsed “Order details” section until the last step. What's wrong with that?",
        options: [
          "People need the costs to decide, so they shouldn't be tucked away",
          "Collapsed sections are always bad and should never be used in checkout",
          "The section should be renamed “More”, so it takes up less space",
          "Nothing, because it keeps the checkout tidy until the final step",
        ],
        correct: 0,
        why: "Progressive disclosure is for detail people can safely ignore. A cost changes the decision, so hiding it feels like a trick and leads to abandoned carts at the final step. Collapsed sections are fine for optional detail, and calling it “More” would make it even harder to find.",
      },
      {
        id: "i5-spot-vague-reveal",
        type: "spot",
        question: "Which part doesn't tell people what it will reveal?",
        title: "Search orders",
        parts: [
          { id: "field", label: "Field labeled Search orders", html: `<div class="mk-label">Search orders</div><div class="mk-in">&nbsp;</div>` },
          { id: "search", label: "Button: Search", html: btn("Search") },
          { id: "more", label: "Link: More", html: `<span class="mk-link">More</span>` },
          { id: "range", label: "Text: Showing orders from the last 30 days", html: `<div class="mk-muted">Showing orders from the last 30 days</div>` },
        ],
        correct: "more",
        why: "“More” could mean more results, more actions or more settings, so people who need date or status filters may never open it. A label like “Filter by date, status or customer” says what's behind it. The search field, the button and the date range note are all clear.",
      },
      {
        id: "i5-sort-compose",
        type: "sort",
        question: "In an email compose screen, which options should show up front, and which can be revealed on request?",
        groups: ["Show up front", "Reveal on request"],
        items: [
          { id: "to", text: "To", group: 0 },
          { id: "subject", text: "Subject", group: 0 },
          { id: "send", text: "Send button", group: 0 },
          { id: "bcc", text: "Cc and Bcc", group: 1 },
          { id: "schedule", text: "Schedule send", group: 1 },
          { id: "from", text: "Change the sender address", group: 1 },
        ],
        why: "Every email needs a recipient, a subject and a way to send it, so those stay visible. Cc and Bcc, scheduling and changing the sender are used far less often, so tucking them behind a clear control keeps the screen simple without taking anything away.",
      },
    ],
  },
  {
    id: "i6",
    code: "I6",
    title: "Modals, panels and inline",
    subtitle: "Interrupt only when you must",
    minutes: 5,
    skills: ["control", "effort"],
    body: [
      "A modal dialog blocks the rest of the page until it's dealt with. That suits moments that truly need a decision before anything else can happen, like confirming a permanent deletion or a session that's about to expire. For everything else it's an interruption: it hides the context people need, and it's easy to get wrong for keyboard and screen reader users.",
      "Prefer inline editing and messages for small tasks, and a side panel for longer ones where people still need to see the page behind. When you do use a modal, keep it short and clearly titled, move focus into it and back to where people were when it closes, let Escape and a Close button dismiss it, and never open one people didn't ask for, like a newsletter pop-up on arrival.",
    ],
    practice: [
      "Edit small things in place, like a name or a status.",
      "Use a side panel when people need to see the page while they work.",
      "Save modals for decisions that must happen before anything else.",
      "Make every modal closable with Escape and a visible Close button, and return focus afterwards.",
    ],
    fieldExercise:
      "List every modal in your product. For each, decide whether it could be inline or a panel instead, and check it closes with Escape.",
    sources: [nng("modal-nonmodal-dialog", "Modal & Nonmodal Dialogs: When (& When Not) to Use Them"), uswds("components/modal", "Modal")],
    exercises: [
      {
        id: "i6-rename",
        type: "compare",
        question: "Someone wants to rename a project from the project list. Which approach interrupts them less?",
        a: `<div class="mk"><div class="mk-row"><span class="mk-in">Website redesign</span>${btn("Save")}${btn("Cancel", "sec")}</div><div class="mk-muted">Mobile app · 14 tasks</div><div class="mk-muted">Brand refresh · 6 tasks</div></div>`,
        b: `<div class="mk"><div class="mk-title">Rename project</div><div class="mk-in">Website redesign</div><div class="mk-row">${btn("Cancel", "sec")}${btn("Save")}</div><div class="mk-muted">Shown in a dialog that covers the project list</div></div>`,
        describe: {
          a: "The project name turns into a field in place in the list, with Save and Cancel next to it, while the other projects stay visible below.",
          b: "A Rename project dialog that covers the project list, with a field containing Website redesign and Cancel and Save buttons.",
        },
        correct: "a",
        why: "Renaming is a small, low-risk edit, so doing it in place, as A does, keeps people in context and takes fewer steps. B's dialog covers the list for no real benefit and adds focus handling that's easy to get wrong.",
      },
      {
        id: "i6-when-modal",
        type: "choice",
        question: "Which situation most justifies a modal dialog?",
        options: [
          "The session is about to expire, with unsaved work at risk",
          "Showing a tip about a new feature as soon as the page loads",
          "Asking people to subscribe to the newsletter on their first visit",
          "Showing the full terms when someone clicks the Terms link",
        ],
        correct: 0,
        why: "An expiring session needs an answer before anything else, or people lose their work, which is exactly what a modal is for. Feature tips and newsletter sign-ups interrupt people for your benefit rather than theirs, and terms can open in a page or panel people read at their own pace.",
      },
      {
        id: "i6-spot-trap",
        type: "spot",
        question: "Which part makes this dialog a trap?",
        title: "Edit team",
        parts: [
          { id: "name", label: "Field labeled Team name, containing Design", html: `<div class="mk-label">Team name</div><div class="mk-in">Design</div>` },
          { id: "members", label: "Text: 8 members", html: `<div class="mk-muted">8 members</div>` },
          { id: "save", label: "Button: Save", html: btn("Save") },
          { id: "exit", label: "Note: the dialog has no Close button and ignores Escape, so the only way out is to save", html: `<div class="mk-muted">No Close button · Escape does nothing</div>` },
        ],
        correct: "exit",
        why: "If the only way out is Save, people who opened the dialog by mistake, or changed their mind, are forced to commit a change. Every dialog needs a Close or Cancel button and should close with Escape. The field, the member count and the Save button are fine.",
      },
      {
        id: "i6-sort-pattern",
        type: "sort",
        question: "Which tasks warrant a modal dialog, and which work better inline or in a side panel?",
        groups: ["Modal dialog", "Inline or panel"],
        items: [
          { id: "delete", text: "Confirming that you want to delete a workspace permanently", group: 0 },
          { id: "session", text: "A session about to expire with unsaved changes", group: 0 },
          { id: "rename", text: "Renaming a file", group: 1 },
          { id: "address", text: "Editing a customer's address while viewing their orders", group: 1 },
          { id: "error", text: "Showing an error for one form field", group: 1 },
        ],
        why: "Modals fit decisions that must happen before anything else, especially permanent or time-critical ones. Small edits work best in place, longer edits that need the page for context suit a side panel, and field errors belong next to the field. Using a modal for those would hide what people need to see.",
      },
    ],
  },
  {
    id: "i7",
    code: "I7",
    title: "Motion with a purpose",
    subtitle: "Animation that explains, not decorates",
    minutes: 5,
    skills: ["feedback", "accessibility"],
    body: [
      "Motion helps when it explains something: where a panel came from, that an item moved to another list, that something changed. Good interface animation is quick, usually between about 100 and 400 milliseconds and rarely over 500, eases in and out rather than moving at a constant speed, and never makes people wait before they can do the next thing.",
      "Motion for decoration quickly becomes noise, and large movements like parallax and zooming can make some people dizzy or nauseous. Respect the reduced-motion setting on people's devices by toning down or removing animation that isn't essential, never make motion the only way information is shown, and let people pause anything that moves for more than a few seconds.",
    ],
    practice: [
      "Give every animation a job: showing where something came from, what changed, or what to do next.",
      "Keep most interface animations between about 100 and 400 milliseconds.",
      "Follow the reduced-motion setting: remove or soften non-essential movement.",
      "Avoid motion that loops forever, or add a way to pause it.",
    ],
    fieldExercise:
      "Turn on Reduce motion on your phone and use your product for five minutes. Note any animation that still plays and isn't essential.",
    sources: [
      nng("animation-purpose-ux", "The Role of Animation and Motion in UX"),
      nng("animation-duration", "Executing UX Animations: Duration and Motion Characteristics"),
      understanding("animation-from-interactions", "Animation from Interactions"),
      { title: "Material Design 3: Motion", url: "https://m3.material.io/styles/motion/overview" },
    ],
    exercises: [
      {
        id: "i7-panel-speed",
        type: "compare",
        question: "A filter panel opens from the side of the screen. Which animation is better?",
        a: `<div class="mk"><div class="mk-label">Animation</div><div>The panel slides in over 600 milliseconds at a constant speed.</div></div>`,
        b: `<div class="mk"><div class="mk-label">Animation</div><div>The panel slides in over 250 milliseconds, easing to a stop.</div></div>`,
        describe: {
          a: "Animation description: the panel slides in over 600 milliseconds at a constant speed.",
          b: "Animation description: the panel slides in over 250 milliseconds, easing to a stop.",
        },
        correct: "b",
        why: "B is quick and eases to a stop, so it shows where the panel came from and gets out of the way. A isn't wildly slow, but 600 milliseconds at a constant speed feels sluggish and mechanical, and people wait for it every time they open filters.",
      },
      {
        id: "i7-reduce-motion",
        type: "choice",
        question: "Someone has turned on Reduce motion on their phone. What should your app do?",
        options: [
          "Remove or soften non-essential animation, like parallax and zooming",
          "Ignore it, because the animations are an important part of the brand",
          "Turn off all hover and focus states, since they count as motion",
          "Show a pop-up asking if they're sure they want less animation",
        ],
        correct: 0,
        why: "People turn on Reduce motion because movement can make them ill or is hard to follow, so your app should honor it by dropping decorative motion. Brand doesn't outweigh someone feeling sick, focus states aren't motion and must stay, and asking them to confirm a system setting is just an extra hurdle.",
      },
      {
        id: "i7-spot-endless",
        type: "spot",
        question: "Which part could make some people feel unwell?",
        title: "Welcome to Ledger",
        parts: [
          { id: "tagline", label: "Text: Track every invoice in one place", html: `<div>Track every invoice in one place</div>` },
          { id: "background", label: "Animation: a background that zooms and spins continuously, with no way to pause it", html: `<div class="mk-media">Background zooms and spins nonstop</div>` },
          { id: "start", label: "Button: Get started", html: btn("Get started") },
          { id: "signin", label: "Link: I already have an account", html: `<span class="mk-link">I already have an account</span>` },
        ],
        correct: "background",
        why: "Large, endless zooming and spinning can cause dizziness and nausea for people with vestibular disorders, and it pulls attention from the content. It should stop after a few seconds, be pausable, and be removed when Reduce motion is on. The text, the button and the link are fine.",
      },
      {
        id: "i7-sort-purpose",
        type: "sort",
        question: "Which animations explain something, and which are just decoration?",
        groups: ["Explains something", "Just decoration"],
        items: [
          { id: "delete", text: "A deleted item shrinks away and the list closes the gap", group: 0 },
          { id: "panel", text: "A side panel slides in from the edge it lives on", group: 0 },
          { id: "cart", text: "The cart icon briefly pulses when an item is added", group: 0 },
          { id: "letters", text: "Headings that bounce in one letter at a time", group: 1 },
          { id: "zoom", text: "A background that slowly zooms forever", group: 1 },
          { id: "wobble", text: "Buttons that wobble every few seconds", group: 1 },
        ],
        why: "Useful motion answers a question: where did that go, where did this come from, did my action work? Bouncing letters, endless zooms and wobbling buttons answer nothing, so they only add delay and distraction, and some can make people feel unwell.",
      },
    ],
  },
  {
    id: "i8",
    code: "I8",
    title: "Touch, pointer and keyboard",
    subtitle: "Design for fingers, mice and keyboards",
    minutes: 5,
    skills: ["control", "accessibility"],
    body: [
      "People use your product with fingers, mice, trackpads, keyboards, styluses and assistive technology, and many switch between them. Touch screens have no hover, so anything that only appears on hover is invisible on a phone. Fingers are less precise than a pointer, so targets need to be big enough, at least 24 by 24 pixels and ideally around 44, with space between them.",
      "Gestures like swiping, pinching and dragging are handy shortcuts, but they're hard to discover and some people can't do them. Always offer a simple alternative, like a visible button for what a swipe does, or Move up and Move down for drag and drop. And make every action work with a keyboard, with visible focus, so people who can't use a mouse aren't locked out.",
    ],
    practice: [
      "Never put an action only behind hover; make it visible or reachable another way.",
      "Make targets at least 24 by 24 pixels, aim for about 44, and space them apart.",
      "Pair every gesture with a visible control that does the same thing.",
      "Check that every action works with the keyboard alone.",
    ],
    fieldExercise:
      "Use your product on a phone with one thumb, then on a computer with only the keyboard. Write down every action you couldn't find or couldn't do.",
    sources: [
      understanding("pointer-gestures", "Pointer Gestures"),
      understanding("dragging-movements", "Dragging Movements"),
      understanding("target-size-minimum", "Target Size (Minimum)"),
      understanding("content-on-hover-or-focus", "Content on Hover or Focus"),
      nng("drag-drop", "Drag–and–Drop: How to Design for Ease of Use"),
    ],
    exercises: [
      {
        id: "i8-swipe-delete",
        type: "compare",
        question: "A to-do app. Which design lets everyone delete a task?",
        a: `<div class="mk"><div class="mk-row"><span>Book dentist</span><span class="mk-link">Delete</span></div><div class="mk-row"><span>Renew passport</span><span class="mk-link">Delete</span></div><div class="mk-muted">You can also swipe left to delete</div></div>`,
        b: `<div class="mk"><div class="mk-row"><span>Book dentist</span></div><div class="mk-row"><span>Renew passport</span></div><div class="mk-muted">Swipe left on a task to delete it</div></div>`,
        describe: {
          a: "Two tasks, Book dentist and Renew passport, each with a visible Delete link, and the note “You can also swipe left to delete”.",
          b: "Two tasks, Book dentist and Renew passport, with the note “Swipe left on a task to delete it” and no other way to delete.",
        },
        correct: "a",
        why: "A gives everyone a visible Delete control and keeps the swipe as a shortcut. In B, swiping is the only way, which people may not discover and which some can't do at all, including keyboard and switch users and anyone with limited hand movement.",
      },
      {
        id: "i8-hover-actions",
        type: "choice",
        question: "A table shows Edit and Delete for a row only when you hover over it. What's the problem?",
        options: [
          "Touch screens have no hover, and keyboard users may miss them",
          "Hover actions take longer to build and test than visible buttons",
          "Edit and Delete should be red, so people know they change data",
          "Tables shouldn't contain actions at all, only data",
        ],
        correct: 0,
        why: "Hover-only actions are invisible on phones and tablets and easy to miss with a keyboard, so people can't find how to edit or delete. Show the actions, or put them in a visible menu button on each row. Build effort and color aren't the issue, and actions in tables are common and fine.",
      },
      {
        id: "i8-spot-tiny",
        type: "spot",
        question: "Which part would be hard to use on a phone?",
        title: "Photo gallery",
        parts: [
          { id: "upload", label: "Button: Upload photos, full size", html: btn("Upload photos") },
          { id: "album", label: "Button: Create album, full size", html: btn("Create album", "sec") },
          { id: "icons", label: "Icons: Share, Download and Delete, each 12 pixels wide with no space between them", html: `<div class="mk-row" style="gap:0;font-size:10px"><span>⇪</span><span>↓</span><span>✕</span></div>` },
          { id: "search", label: "Field labeled Search photos", html: `<div class="mk-label">Search photos</div><div class="mk-in">&nbsp;</div>` },
        ],
        correct: "icons",
        why: "Twelve-pixel icons packed together are far below the 24-pixel minimum, so people tap the wrong one, which is risky when one of them is Delete. They need bigger targets with space between them, ideally with labels. The two buttons and the search field are a comfortable size.",
      },
      {
        id: "i8-sort-input",
        type: "sort",
        question: "Which interactions work for everyone as they are, and which need an alternative?",
        groups: ["Works for everyone", "Needs an alternative"],
        items: [
          { id: "delete", text: "A visible Delete button on each item", group: 0 },
          { id: "move", text: "Move up and Move down buttons for reordering", group: 0 },
          { id: "labeled", text: "Tapping a large, clearly labeled button", group: 0 },
          { id: "pinch", text: "Pinching as the only way to zoom a map", group: 1 },
          { id: "drag", text: "Dragging as the only way to reorder a list", group: 1 },
          { id: "longpress", text: "Long-pressing as the only way to open options", group: 1 },
        ],
        why: "Visible buttons work with fingers, mice, keyboards and assistive technology. Pinching, dragging and long-pressing are fine as shortcuts, but as the only way they shut out people who can't perform the gesture or don't know it exists. Add zoom buttons, Move controls and a visible Options button.",
      },
    ],
  },
];

export const interactionDesignPath: LearningPath = {
  id: "interaction-design",
  title: "Interaction design",
  description: "Signifiers, component states, response times, navigation, progressive disclosure, modals, motion, and touch and keyboard input.",
  status: "live",
  lessons,
};
