import type { Lesson, LearningPath, Source } from "../types";

// Laws of UX and NN/g are summarize-and-link only: all text and examples here are original.
const lawsOfUx = (slug: string, title: string): Source => ({ title: `Laws of UX: ${title}`, url: `https://lawsofux.com/${slug}/` });
const nng = (path: string, title: string): Source => ({ title: `NN/g: ${title}`, url: `https://www.nngroup.com/${path}/` });

const lessons: Lesson[] = [
  {
    id: "l1",
    code: "L1",
    title: "Jakob's Law",
    subtitle: "People expect your product to work like the ones they already use",
    minutes: 4,
    skills: ["conventions"],
    body: [
      "Your users learn how software works from all the other products they use every day, and yours is only a small part of that. Every site and app they use teaches them where the cart lives, what a magnifying glass means and how a date field behaves. When your product follows those habits, people can use what they already know. When it breaks them, they have to learn something new just to get started.",
      "This doesn't mean copying competitors pixel for pixel. Follow conventions for the basics people rely on, such as navigation, search, forms and checkout, and save your originality for places where it really helps the task. If you must change a familiar pattern, make the new one easy to discover, and give people time to adjust.",
    ],
    practice: [
      "Put common elements where people look for them, such as search at the top and the account menu in the top corner.",
      "Use standard icons for their standard meanings, and don't give a familiar icon a new job.",
      "Before replacing a familiar pattern, test the new one with people who know the old one.",
      "When a redesign changes something people use daily, let them try the new version before it becomes the only one.",
    ],
    fieldExercise:
      "Compare your product's header, search and account menu with three tools your users use every day. Note every place where yours puts a common element somewhere unexpected.",
    sources: [lawsOfUx("jakobs-law", "Jakob's Law"), nng("videos/jakobs-law-internet-ux", "Jakob's Law of Internet User Experience (video)")],
    exercises: [
      {
        id: "l1-cart-location",
        type: "compare",
        question: "An online office supplies store. In which design will shoppers find their cart faster?",
        a: `<div class="mk"><div class="mk-row"><b>Deskly</b><span class="mk-in">Search products</span><span class="mk-link">Account</span><span class="mk-link">Cart (3)</span></div><div class="mk-muted">Paper · Ink and toner · Desk accessories</div></div>`,
        b: `<div class="mk"><div class="mk-row"><b>Deskly</b><span class="mk-in">Search products</span><span class="mk-link">Account</span></div><div class="mk-muted">Paper · Ink and toner · Desk accessories</div><div class="mk-muted">My order list (3 items) is in the left sidebar under Categories</div></div>`,
        describe: {
          a: "A store header: the Deskly logo, a search box, then Account and Cart (3) links at the right. Category links below.",
          b: "A store header: the Deskly logo, a search box and an Account link. Category links below, and a note: My order list (3 items) is in the left sidebar under Categories.",
        },
        correct: "a",
        why: "A puts the cart in the header and calls it a cart, like almost every online store. B renames it and moves it into a sidebar, so shoppers who learned the convention elsewhere have to hunt for it, and some will think their items are gone.",
      },
      {
        id: "l1-new-pattern",
        type: "choice",
        question: "Your team wants to replace the standard checkbox filters in your app with a new drag-to-sort control because it looks more modern. What does Jakob's Law suggest?",
        options: [
          "Ship it, because a fresh pattern makes the product more memorable",
          "Keep the familiar pattern unless the new one solves a real problem",
          "Ship it with a tutorial overlay the first time people see the new filters",
          "Let each team choose the filter pattern that suits its own pages",
        ],
        correct: 1,
        why: "People already know how checkbox filters work from other products, so a replacement has to be worth the learning it demands. A tutorial overlay admits the new control isn't self-explanatory and is often dismissed unread, and letting each team choose breaks consistency inside your own product.",
      },
      {
        id: "l1-spot-hidden-cart",
        type: "spot",
        question: "Which part of this online store breaks what shoppers expect from every other store?",
        title: "Deskly",
        parts: [
          {
            id: "logo",
            label: "Logo at the top left: Deskly",
            html: `<span class="mk-title">Deskly</span>`,
          },
          {
            id: "search",
            label: "Search field at the top: Search products",
            html: `<div class="mk-in">Search products</div>`,
          },
          {
            id: "account",
            label: "Links at the top right: Account and Help",
            html: `<div class="mk-row"><span class="mk-link">Account</span><span class="mk-link">Help</span></div>`,
          },
          {
            id: "cart",
            label: "Link at the bottom of the page, in the footer: Purchases (3)",
            html: `<div class="mk-muted">Footer · <span class="mk-link">Purchases (3)</span></div>`,
          },
        ],
        correct: "cart",
        why: "Shoppers expect the cart at the top right, called a cart or basket, because nearly every store puts it there. Hiding it in the footer under another name makes them hunt for it, and some will think their items are gone. The logo, search and account links are where people look for them.",
      },
      {
        id: "l1-sort-placement",
        type: "sort",
        question: "Following Jakob's Law, which placements match what people expect from other websites, and which don't?",
        groups: ["Where people expect it", "Unexpected"],
        items: [
          { id: "cart", text: "The shopping cart in the top-right corner of a store", group: 0 },
          { id: "search", text: "Search near the top of the page", group: 0 },
          { id: "privacy", text: "The privacy policy linked in the footer", group: 0 },
          { id: "logout", text: "Sign out tucked inside the Help menu", group: 1 },
          { id: "checkout", text: "The checkout button hidden under a “More” menu", group: 1 },
          { id: "settings", text: "Settings opened only by long-pressing the logo", group: 1 },
        ],
        why: "People spend most of their time on other sites, so they look for things where those sites put them. Matching that saves them from learning your layout. Signing out from a Help menu, a hidden checkout and a long-press shortcut all make people hunt for things they'd normally find without thinking.",
      },
    ],
  },
  {
    id: "l2",
    code: "L2",
    title: "Fitts's Law",
    subtitle: "Big and close is easy to hit",
    minutes: 4,
    skills: ["control", "errors"],
    body: [
      "The time it takes to point at something depends on how far away it is and how big it is. A large button near where your pointer or thumb already is takes a moment to hit. A small link across the screen takes longer and is easier to miss.",
      "This shapes where actions go and how big they are. Put the main action close to the content it acts on, make frequent targets large, and give small controls a clickable area bigger than their visible size. The same law works in reverse: a destructive action that's harder to hit by accident is often a good thing.",
    ],
    practice: [
      "Make primary and frequent actions large. Where it makes sense, make the whole row or card clickable.",
      "Place actions next to what they act on, such as the submit button right after the last field.",
      "Keep destructive actions away from frequent ones, so speed doesn't turn into mistakes.",
      "On phones, put frequent actions where a thumb can reach them easily.",
    ],
    fieldExercise:
      "Pick the most frequent action in your product. Measure its target size and how far it is from where people are looking just before they use it.",
    sources: [lawsOfUx("fittss-law", "Fitts's Law"), nng("articles/fitts-law", "Fitts's Law and Its Applications in UX")],
    exercises: [
      {
        id: "l2-row-target",
        type: "compare",
        question: "In an expense list, people open a row to see its details dozens of times a day. Which design makes that easier?",
        a: `<div class="mk"><div class="mk-row"><span>Taxi to airport · $46.20</span><span class="mk-link">View</span></div><div class="mk-row"><span>Team lunch · $128.00</span><span class="mk-link">View</span></div><div class="mk-row"><span>Hotel, 2 nights · $389.00</span><span class="mk-link">View</span></div></div>`,
        b: `<div class="mk"><div class="mk-cell">Taxi to airport · $46.20 ›</div><div class="mk-cell">Team lunch · $128.00 ›</div><div class="mk-cell">Hotel, 2 nights · $389.00 ›</div><div class="mk-muted">The whole row opens the expense</div></div>`,
        describe: {
          a: "Three expense rows (Taxi to airport, $46.20; Team lunch, $128.00; Hotel, 2 nights, $389.00), each with a small View link at the far right.",
          b: "Three expense rows (Taxi to airport, $46.20; Team lunch, $128.00; Hotel, 2 nights, $389.00), each a full-width bordered box with an arrow, and a note: The whole row opens the expense.",
        },
        correct: "b",
        why: "In B the whole row is the target, so it's large and already under the pointer wherever people are reading. A makes them move to a small View link for every row, which is slower and easier to miss.",
      },
      {
        id: "l2-destructive",
        type: "choice",
        question: "A dialog has “Delete project” and “Cancel” buttons. People rarely mean to delete a project. How should Fitts's Law shape the design?",
        options: [
          "Make Delete the biggest, most prominent button so people can find it fast",
          "Make Cancel the easy target, and Delete clearly labeled but smaller",
          "Make both buttons tiny so nobody clicks either one by accident",
          "Put Delete in a screen corner, where it's fastest to reach with a mouse",
        ],
        correct: 1,
        why: "Fitts's Law tells you how to make a target easy to hit, so it also tells you how to make one a little harder. The safe, common choice should be the easy target, and the destructive one should be findable but not where a quick click lands. Tiny buttons slow everyone down, and a corner makes Delete faster to hit by accident.",
      },
      {
        id: "l2-spot-tiny-continue",
        type: "spot",
        question: "Almost everyone on this checkout step wants to continue. Which part works against them?",
        title: "Review your order",
        parts: [
          {
            id: "summary",
            label: "Order summary: 2 items, $84.00, delivery Thursday 8 October",
            html: `<div>2 items · $84.00</div><div class="mk-muted">Delivery Thursday 8 October</div>`,
          },
          [
            {
              id: "cancel",
              label: "Large filled button: Cancel order",
              html: `<span class="mk-btn">Cancel order</span>`,
            },
            {
              id: "continue",
              label: "Small text link: continue to payment",
              html: `<span class="mk-link" style="font-size:11px">continue to payment</span>`,
            },
          ],
          {
            id: "note",
            label: "Small text: Your card won't be charged until you confirm.",
            html: `<div class="mk-muted">Your card won't be charged until you confirm.</div>`,
          },
        ],
        correct: "continue",
        why: "The action nearly everyone wants is a small link, while Cancel order gets the big, easy target. Fitts's Law points the other way: make the main action large and easy to hit, and keep the destructive one smaller and set apart.",
      },
      {
        id: "l2-sort-targets",
        type: "sort",
        question: "Following Fitts's Law, which targets are easier to hit, and which are harder?",
        groups: ["Easier to hit", "Harder to hit"],
        items: [
          { id: "row", text: "A whole table row that opens the item", group: 0 },
          { id: "thumb", text: "A large main button at the bottom of a phone screen, near the thumb", group: 0 },
          { id: "submit", text: "A Submit button right below the last field", group: 0 },
          { id: "close", text: "A tiny × in the corner to close a banner", group: 1 },
          { id: "link", text: "A small text link to continue, buried in a paragraph", group: 1 },
          { id: "far", text: "The main button placed at the top of a long form, far from the last field", group: 1 },
        ],
        why: "Targets are quicker and more accurate to hit when they're big and close to where the pointer or thumb already is. Whole rows, large buttons in reach and buttons right after the last field all qualify. Tiny close icons, small inline links and a button far away from where people finish all take more time and cause more misses.",
      },
    ],
  },
  {
    id: "l3",
    code: "L3",
    title: "Hick's Law",
    subtitle: "More choices, slower decisions",
    minutes: 4,
    skills: ["effort"],
    body: [
      "The more options people have, and the harder they are to tell apart, the longer it takes to choose. Each extra option adds a little time, and a screen full of similar choices can stall people completely, or lead them to choose nothing at all.",
      "Hick's Law applies most to simple choices among options people understand, such as picking from a menu. The fix is not always fewer options; often it's fewer options at once. Recommend a choice, group options into categories, and show advanced settings only when people ask for them.",
    ],
    practice: [
      "Remove options people rarely choose, or move them behind a “More options” step.",
      "Recommend a default or the most popular choice when one fits most people.",
      "Split long lists into categories people recognize.",
      "Don't oversimplify: hiding an option people need costs them more time than showing it.",
    ],
    fieldExercise:
      "Count the choices on your product's main screen that compete for the first click. Mark which ones most people actually use.",
    sources: [
      lawsOfUx("hicks-law", "Hick's Law"),
      lawsOfUx("choice-overload", "Choice Overload"),
      nng("articles/simplicity-vs-choice", "Simplicity Wins over Abundance of Choice"),
    ],
    exercises: [
      {
        id: "l3-plan-picker",
        type: "compare",
        question: "A team chat app shows its pricing plans. Which helps people choose faster?",
        a: `<div class="mk"><div class="mk-grid"><div class="mk-cell"><b>Starter</b>$4</div><div class="mk-cell"><b>Basic</b>$6</div><div class="mk-cell"><b>Plus</b>$8</div><div class="mk-cell"><b>Pro</b>$10</div><div class="mk-cell"><b>Business</b>$13</div><div class="mk-cell"><b>Business+</b>$15</div></div><div class="mk-muted">Per person per month</div></div>`,
        b: `<div class="mk"><div class="mk-grid"><div class="mk-cell"><b>Free</b>Up to 10 people</div><div class="mk-cell"><b>Team</b>$8 per person <span class="mk-pill">Most popular</span></div><div class="mk-cell"><b>Enterprise</b>Talk to sales</div></div></div>`,
        describe: {
          a: "Six plan tiles, priced per person per month: Starter $4, Basic $6, Plus $8, Pro $10, Business $13, Business+ $15.",
          b: "Three plan tiles: Free, up to 10 people; Team, $8 per person, marked Most popular; Enterprise, talk to sales.",
        },
        correct: "b",
        why: "B offers three clearly different plans and marks the one most teams pick, so people can decide quickly. A's six plans differ in small ways that are hard to compare, so people take longer, second-guess themselves or leave to think about it.",
      },
      {
        id: "l3-export-settings",
        type: "choice",
        question: "A photo editor's export dialog shows 25 settings at once. Most people only ever change the file format. What's the best fix?",
        options: [
          "Remove every setting except the file format, to keep the dialog short",
          "Show the format with a default, and the rest under “More options”",
          "Sort all 25 settings alphabetically so they're easier to scan",
          "Split the settings across five tabs of five settings each",
        ],
        correct: 1,
        why: "Showing only the setting most people change makes the common case quick, and the rest stay one click away for people who need them. Removing them hurts experts, sorting doesn't reduce the number of decisions, and tabs spread the same 25 choices out and add navigation on top.",
      },
      {
        id: "l3-spot-too-many-options",
        type: "spot",
        question: "Most people export with the default settings. Which part slows them down?",
        title: "Export report",
        parts: [
          {
            id: "format",
            label: "Dropdown labeled Format, showing PDF",
            html: `<div class="mk-label">Format</div><div class="mk-in">PDF ▾</div>`,
          },
          {
            id: "options",
            label: "Section: Options, with 18 checkboxes all shown at once",
            html: `<div class="mk-label">Options</div><div class="mk-muted">☐ Header ☐ Footer ☐ Page numbers ☐ Logo ☐ Gridlines ☐ Notes … 18 checkboxes</div>`,
          },
          {
            id: "export",
            label: "Button: Export",
            html: `<span class="mk-btn">Export</span>`,
          },
        ],
        correct: "options",
        why: "Eighteen equal checkboxes make everyone read and weigh options that most people never change, which slows the decision. Sensible defaults with the rest behind “More options” keep the common case quick. The format choice and the button are what most people need.",
      },
      {
        id: "l3-sort-choices",
        type: "sort",
        question: "Following Hick's Law, which designs make decisions faster, and which slow them down?",
        groups: ["Faster decisions", "Slower decisions"],
        items: [
          { id: "recommended", text: "Highlighting the plan most teams choose", group: 0 },
          { id: "sections", text: "Grouping 40 settings into 5 clear sections", group: 0 },
          { id: "defaults", text: "Showing three common options, with “More options” for the rest", group: 0 },
          { id: "plans", text: "Twelve pricing plans with small differences", group: 1 },
          { id: "upfront", text: "Asking everyone to set 20 preferences before they can start", group: 1 },
        ],
        why: "The more options people must weigh at once, the longer they take to decide. A recommendation, sensible groups and a short list of common choices all cut what people have to compare. A dozen near-identical plans and a wall of upfront preferences force them to weigh everything, so they slow down or give up.",
      },
    ],
  },
  {
    id: "l4",
    code: "L4",
    title: "Miller's Law and chunking",
    subtitle: "Memory is small, so group things",
    minutes: 5,
    skills: ["effort"],
    body: [
      "In 1956, the psychologist George Miller observed that people can hold about seven items, give or take two, in short-term memory. Later research suggests the real limit is nearer four meaningful chunks. Either way, working memory is small, and everything people must remember while using your product takes up some of it.",
      "The number is often misused to claim menus should have at most seven items. Menus stay on screen, so people don't need to remember them. The useful lesson is chunking: grouping information into meaningful units. A phone number split into groups, or a long form split into sections, is far easier to read, check and remember than one long unbroken run.",
    ],
    practice: [
      "Show long numbers and codes in groups: 4111 1111 1111 1111, not 4111111111111111.",
      "Don't make people carry information from one screen to the next. Show it where they need it.",
      "Break long content into short sections with clear headings.",
      "Don't cut a useful menu to seven items just because of the number.",
    ],
    fieldExercise:
      "Find a place in your product where people must copy or remember a code, number or setting from one screen to use on another. Sketch how you could show it where it's needed instead.",
    sources: [
      lawsOfUx("millers-law", "Miller's Law"),
      lawsOfUx("chunking", "Chunking"),
      nng("articles/short-term-memory-and-web-usability", "Short-Term Memory and Web Usability"),
      nng("articles/chunking", "How Chunking Helps Content Processing"),
    ],
    exercises: [
      {
        id: "l4-reference-code",
        type: "compare",
        question: "A customer has to read their booking reference to a support agent over the phone. Which version is easier?",
        a: `<div class="mk"><div class="mk-label">Your booking reference</div><div class="mk-big">QX7 K2M 9PL</div></div>`,
        b: `<div class="mk"><div class="mk-label">Your booking reference</div><div class="mk-big">QX7K2M9PL</div></div>`,
        describe: {
          a: "Your booking reference in large text, shown as three groups of three characters with spaces between them: QX7 K2M 9PL.",
          b: "Your booking reference in large text, shown as one unbroken string of nine characters: QX7K2M9PL.",
        },
        correct: "a",
        why: "In A the reference is split into three chunks of three, so it's easy to read aloud, hold in mind and check. In B the same nine characters run together, so people lose their place and mix characters up.",
      },
      {
        id: "l4-menu-myth",
        type: "choice",
        question: "A reviewer says your app's 11-item side navigation breaks Miller's Law and must be cut to 7. What's the best response?",
        options: [
          "Agree, and remove the four least-used items to get down to seven",
          "Explain that people see a menu rather than remember it, and check its labels",
          "Split it into two menus, one of five items and one of six",
          "Hide the navigation behind a menu icon so the limit doesn't apply",
        ],
        correct: 1,
        why: "People recognize items in a visible menu rather than remembering them, so Miller's number doesn't set a limit. What matters is whether the menu is easy to scan: clear names and sensible groups. Cutting useful items, splitting the menu arbitrarily or hiding it all make navigation harder.",
      },
      {
        id: "l4-spot-long-code",
        type: "spot",
        question: "People have to type this code on another device. Which part makes that harder than it needs to be?",
        title: "Your sign-in code",
        parts: [
          {
            id: "code",
            label: "Code shown as one block of ten digits: 4827193650",
            html: `<div class="mk-big">4827193650</div>`,
          },
          {
            id: "expiry",
            label: "Text: Expires in 10 minutes",
            html: `<div class="mk-muted">Expires in 10 minutes</div>`,
          },
          {
            id: "where",
            label: "Text: Enter it on the sign-in screen",
            html: `<div>Enter it on the sign-in screen</div>`,
          },
          {
            id: "copy",
            label: "Button: Copy code",
            html: `<span class="mk-btn sec">Copy code</span>`,
          },
        ],
        correct: "code",
        why: "Ten digits in one block are hard to hold in mind while switching devices, so people lose their place and mistype. Showing the code in chunks, such as 482 719 3650, makes it far easier to read and copy. The expiry, instructions and copy button all help.",
      },
      {
        id: "l4-sort-chunks",
        type: "sort",
        question: "Which of these are broken into chunks that are easy to read and remember, and which aren't?",
        groups: ["Chunked", "Not chunked"],
        items: [
          { id: "phone", text: "A phone number shown as +353 87 123 4567", group: 0 },
          { id: "iban", text: "A bank account number shown in groups of four characters", group: 0 },
          { id: "sections", text: "A long settings page split into sections with headings", group: 0 },
          { id: "card", text: "A card number shown as 4111111111111111", group: 1 },
          { id: "ref", text: "A booking reference shown as QX7K2M9PLR4T", group: 1 },
          { id: "list", text: "Thirty checkboxes in one unbroken list", group: 1 },
        ],
        why: "Short-term memory holds only a few things at once, so grouping helps people read, compare and copy information. Spacing numbers into groups and splitting long pages into sections do that. Long unbroken strings and lists make people lose their place, and that leads to typos and misreads.",
      },
    ],
  },
  {
    id: "l5",
    code: "L5",
    title: "Proximity and common region",
    subtitle: "Grouping without words",
    minutes: 4,
    skills: ["layout"],
    body: [
      "People see things that sit close together as related, and things inside the same boundary as a group. These two principles from Gestalt psychology, proximity and common region, are among the strongest tools in layout: they tell people what belongs with what before they read a word.",
      "They also cause many layout bugs. A label sitting halfway between two fields is ambiguous, and a button placed nearer the wrong section seems to belong to it. Spacing is information, not decoration, so make the space between groups clearly larger than the space within them.",
    ],
    practice: [
      "Keep each label closer to its own field than to the field above it.",
      "Use more space between groups than inside them, so the grouping is obvious.",
      "Use cards or background panels to group related content, but don't box every element.",
      "Place actions next to the content they affect.",
    ],
    fieldExercise:
      "Blur a screenshot of one of your product's screens, or squint at it. Write down the groups you see, then check that they match what actually belongs together.",
    sources: [
      lawsOfUx("law-of-proximity", "Law of Proximity"),
      lawsOfUx("law-of-common-region", "Law of Common Region"),
      nng("articles/gestalt-proximity", "Proximity Principle in Visual Design"),
      nng("articles/common-region", "The Principle of Common Region"),
    ],
    exercises: [
      {
        id: "l5-label-spacing",
        type: "compare",
        question: "Which form makes it clearer which label belongs to which field?",
        a: `<div class="mk" style="gap:14px"><div class="mk-label">Street address</div><div class="mk-in">&nbsp;</div><div class="mk-label">City</div><div class="mk-in">&nbsp;</div><div class="mk-label">Postal code</div><div class="mk-in">&nbsp;</div></div>`,
        b: `<div class="mk" style="gap:16px"><div style="display:grid;gap:3px"><div class="mk-label">Street address</div><div class="mk-in">&nbsp;</div></div><div style="display:grid;gap:3px"><div class="mk-label">City</div><div class="mk-in">&nbsp;</div></div><div style="display:grid;gap:3px"><div class="mk-label">Postal code</div><div class="mk-in">&nbsp;</div></div></div>`,
        describe: {
          a: "Street address, City and Postal code labels and fields. Every gap is the same size, so each label is as close to the field above it as to its own field below.",
          b: "Street address, City and Postal code labels and fields. Each label sits tight above its own field, with a larger gap before the next label.",
        },
        correct: "b",
        why: "In B each label sits tight against its own field, with more space before the next pair, so each pair reads as one unit. In A every gap is the same, so each label floats halfway between two fields and people have to work out which one it describes.",
      },
      {
        id: "l5-save-placement",
        type: "choice",
        question: "A settings page has two sections, Profile and Notifications, each with its own fields. One Save button sits in the space between them. What's the problem?",
        options: [
          "The button should be a different color from the rest of the page",
          "It's unclear which section it saves; give each section its own Save",
          "Save buttons should always be at the top of the page, not between sections",
          "There's no problem, as long as the button saves both sections at once",
        ],
        correct: 1,
        why: "Because the button sits between the two groups, people can't tell which one it belongs to, and some will leave changes unsaved. Putting it inside the section it acts on, or clearly at the end of everything, makes the relationship obvious. A new color doesn't fix an unclear relationship, and saving both only helps if people can tell that it does.",
      },
      {
        id: "l5-spot-floating-save",
        type: "spot",
        question: "Which part's position makes it unclear what it belongs to?",
        title: "Settings",
        parts: [
          {
            id: "profile",
            label: "Section: Profile, with Name and Email fields",
            html: `<div class="mk-title">Profile</div><div class="mk-label">Name</div><div class="mk-in">&nbsp;</div><div class="mk-label">Email</div><div class="mk-in">&nbsp;</div>`,
          },
          {
            id: "save",
            label: "Button: Save, sitting alone in the gap between the Profile and Notifications sections",
            html: `<span class="mk-btn">Save</span>`,
          },
          {
            id: "notifications",
            label: "Section: Notifications, with two checkboxes",
            html: `<div class="mk-title">Notifications</div><div>☐ Email me weekly</div><div>☐ Email me when mentioned</div>`,
          },
        ],
        correct: "save",
        why: "Sitting halfway between two sections, the Save button could belong to either, so people can't tell what it saves and some leave changes unsaved. Putting it inside the section it acts on, or clearly at the end of everything, makes the grouping obvious. The two sections are clearly grouped themselves.",
      },
      {
        id: "l5-sort-grouping",
        type: "sort",
        question: "Which layouts make it clear what belongs together, and which leave it unclear?",
        groups: ["Clearly grouped", "Grouping unclear"],
        items: [
          { id: "label", text: "Each label sits tight above its field, with a bigger gap before the next one", group: 0 },
          { id: "cards", text: "Billing and shipping addresses in two separate cards", group: 0 },
          { id: "save", text: "A Save button directly under the settings it saves", group: 0 },
          { id: "equal", text: "Equal spacing between every label and every field", group: 1 },
          { id: "floating", text: "A Delete button halfway between two cards", group: 1 },
          { id: "caption", text: "A caption the same distance from two photos", group: 1 },
        ],
        why: "People read things that are close together, or inside the same box, as belonging together. Tight label-field pairs, separate cards and a button right under its settings use that. Equal spacing, a button between two cards and a caption between two photos all leave people guessing what goes with what.",
      },
    ],
  },
  {
    id: "l6",
    code: "L6",
    title: "The Von Restorff effect",
    subtitle: "What stands out gets noticed",
    minutes: 4,
    skills: ["layout"],
    body: [
      "When one item looks different from everything around it, people notice it and remember it. That's why a single highlighted plan on a pricing page, or one bold button at the end of a form, draws the eye.",
      "The effect only works when the difference is rare. If everything is bold, colorful or moving, nothing stands out and the page just feels noisy. The difference also shouldn't rely on color alone: people who can't see the color need another cue, such as a label, size or position.",
    ],
    practice: [
      "Give each screen one primary action that looks different from everything else.",
      "Highlight sparingly. If more than one or two things are emphasized, nothing is.",
      "Pair color with another cue, such as a label, an icon or heavier text.",
      "Avoid motion for emphasis unless it's essential, and respect people's reduced-motion settings.",
    ],
    fieldExercise:
      "Show a colleague a screenshot of one screen for five seconds and ask what they noticed first. Check whether that's what you want people to do first.",
    sources: [
      lawsOfUx("von-restorff-effect", "Von Restorff Effect"),
      { title: "WCAG 2.2 Understanding: Use of Color", url: "https://www.w3.org/WAI/WCAG22/Understanding/use-of-color.html" },
    ],
    exercises: [
      {
        id: "l6-primary-action",
        type: "compare",
        question: "An article editor has three actions. Which version makes the main next step clearest?",
        a: `<div class="mk"><div class="mk-title">Quarterly update: new office opening</div><div class="mk-muted">Last saved 2 minutes ago</div><div class="mk-row"><span class="mk-btn sec">Save draft</span><span class="mk-btn sec">Preview</span><span class="mk-btn">Publish</span></div></div>`,
        b: `<div class="mk"><div class="mk-title">Quarterly update: new office opening</div><div class="mk-muted">Last saved 2 minutes ago</div><div class="mk-row"><span class="mk-btn">Save draft</span><span class="mk-btn">Preview</span><span class="mk-btn">Publish</span></div></div>`,
        describe: {
          a: "An article editor with three buttons: Save draft and Preview are outlined, and Publish is solid filled.",
          b: "An article editor with three buttons, Save draft, Preview and Publish, all solid filled in the same style.",
        },
        correct: "a",
        why: "In A one button stands out, so people see the main action at a glance while the others stay available. In B all three compete equally, so people have to read and weigh each one, and the most important action gets no help.",
      },
      {
        id: "l6-too-many-highlights",
        type: "choice",
        question: "A dashboard shows 12 cards, and the team made 8 of them red with “!” badges to get attention. What's most likely to happen?",
        options: [
          "People will pay close attention to all 8 cards, so nothing gets missed",
          "The highlights cancel each other out, and the one urgent card gets lost",
          "People will feel well informed because every card looks important",
          "Nothing, except for people with color blindness, who can't see the colors",
        ],
        correct: 1,
        why: "Emphasis works by contrast with what's around it. When most cards shout, none of them stands out, and people learn to ignore the red. Keep the strong treatment for the few items that need action now.",
      },
      {
        id: "l6-spot-everything-bold",
        type: "spot",
        question: "Which part makes the main action impossible to pick out?",
        title: "Edit article",
        parts: [
          {
            id: "title",
            label: "Field labeled Title, containing New office opening",
            html: `<div class="mk-label">Title</div><div class="mk-in">New office opening</div>`,
          },
          {
            id: "body",
            label: "Text area with the article text",
            html: `<div class="mk-in" style="height:40px">Our new Dublin office opens on…</div>`,
          },
          {
            id: "toolbar",
            label: "Toolbar: Save draft, Preview, Share, Duplicate and Publish, all in the same bold blue button style",
            html: `<div class="mk-row"><span class="mk-btn">Save draft</span><span class="mk-btn">Preview</span><span class="mk-btn">Share</span><span class="mk-btn">Duplicate</span><span class="mk-btn">Publish</span></div>`,
          },
        ],
        correct: "toolbar",
        why: "When every button has the same bold treatment, nothing stands out, so people have to read all five to find Publish. Giving the main action the strong style and the others a quieter one makes the next step obvious at a glance. The fields are fine.",
      },
      {
        id: "l6-sort-standout",
        type: "sort",
        question: "Which elements stand out for a good reason, and which stand out for no reason?",
        groups: ["For a good reason", "For no reason"],
        items: [
          { id: "primary", text: "The one main button on a form", group: 0 },
          { id: "error", text: "A field with an error, shown in red", group: 0 },
          { id: "popular", text: "The plan most customers pick, marked “Most popular”", group: 0 },
          { id: "badges", text: "A flashing “NEW” badge on every menu item", group: 1 },
          { id: "orange", text: "One random word in bright orange in the middle of a paragraph", group: 1 },
          { id: "banner", text: "A decorative banner brighter than the Pay button", group: 1 },
        ],
        why: "The thing that differs from its surroundings gets noticed, so save that for what matters most: the main action, a problem to fix, a helpful recommendation. Badges on everything cancel each other out, a random highlight pulls attention for nothing, and a bright decoration steals it from the action people came to take.",
      },
    ],
  },
  {
    id: "l7",
    code: "L7",
    title: "The peak-end rule",
    subtitle: "People remember the high points and the ending",
    minutes: 4,
    skills: ["feedback"],
    body: [
      "People don't judge an experience by averaging every moment. They remember it mostly by its most intense point, good or bad, and by how it ended. A smooth checkout with a confusing error on the last step can be remembered as a bad experience, even though most of it went well.",
      "For design, this means finding the moments that matter most and making them great, and fixing the worst moments first, because bad peaks stay with people longest. Endings deserve special care: a clear confirmation, a sense of having finished, and an obvious next step.",
    ],
    practice: [
      "Map the journey and mark its high and low points, using research or support tickets.",
      "Fix the most frustrating moment before polishing the average ones.",
      "End every flow with a confirmation that says what happened and what comes next.",
      "Add moments of delight only where they don't slow people down.",
    ],
    fieldExercise:
      "Read the last screen of three key flows in your product. For each one, note whether it confirms what happened and offers a clear next step.",
    sources: [lawsOfUx("peak-end-rule", "Peak-End Rule"), nng("articles/peak-end-rule", "The Peak–End Rule: How Impressions Become Memories")],
    exercises: [
      {
        id: "l7-confirmation",
        type: "compare",
        question: "The last screen after someone books a car service. Which ending leaves a better impression?",
        a: `<div class="mk"><div class="mk-title">Request submitted.</div><div class="mk-row"><span class="mk-btn">OK</span></div></div>`,
        b: `<div class="mk"><div class="mk-title">You're booked for Tuesday 14 October at 9:00 AM</div><div>Northside Auto, 21 Mill Road</div><div class="mk-muted">We've emailed your confirmation. You can change or cancel up to 24 hours before.</div><div class="mk-row"><span class="mk-btn">Add to calendar</span><span class="mk-btn sec">View booking</span></div></div>`,
        describe: {
          a: "A screen saying “Request submitted.” with an OK button.",
          b: "A screen saying “You're booked for Tuesday 14 October at 9:00 AM” at Northside Auto, 21 Mill Road, noting that the confirmation was emailed and you can change or cancel up to 24 hours before. Buttons: Add to calendar, View booking.",
        },
        correct: "b",
        why: "B confirms exactly what was booked, says what happens next and offers useful next steps, so the experience ends on a confident note. A leaves people unsure whether the booking worked and what to do now, and that doubt colors their memory of the whole flow.",
      },
      {
        id: "l7-fix-the-low",
        type: "choice",
        question: "Research shows most of your onboarding goes well, but connecting a bank account fails for 1 in 5 people and is very frustrating. You have time for one improvement. Which should it be?",
        options: [
          "Add a celebration animation at the end of onboarding",
          "Fix the bank connection step that 1 in 5 people fail",
          "Polish the illustrations on the welcome screen",
          "Shorten the terms and conditions",
        ],
        correct: 1,
        why: "The failing bank connection is the low point people will remember and judge the whole product by. A nicer ending or prettier welcome screen can't make up for a moment where one in five people gets stuck.",
      },
      {
        id: "l7-spot-flat-ending",
        type: "spot",
        question: "Which part will color how people remember this whole purchase?",
        title: "Checkout",
        parts: [
          {
            id: "cart",
            label: "Step 1, Cart: product photos and a clear total",
            html: `<div class="mk-muted">Step 1 · Cart</div><div>2 items · $84.00</div>`,
          },
          {
            id: "delivery",
            label: "Step 2, Delivery: address filled in with one tap",
            html: `<div class="mk-muted">Step 2 · Delivery</div><div>Address filled in for you ✓</div>`,
          },
          {
            id: "payment",
            label: "Step 3, Payment: a one-tap pay button",
            html: `<div class="mk-muted">Step 3 · Payment</div><span class="mk-btn">Pay with one tap</span>`,
          },
          {
            id: "end",
            label: "Last screen: the words Request processed., with no order number, delivery date or next step",
            html: `<div class="mk-muted">Last screen</div><div>Request processed.</div>`,
          },
        ],
        correct: "end",
        why: "People judge an experience largely by how it ends, and this ending leaves them unsure whether the order went through or when it will arrive. A confirmation with the order number, delivery date and a next step ends on a confident note. The earlier steps are smooth.",
      },
      {
        id: "l7-sort-endings",
        type: "sort",
        question: "Following the peak-end rule, which endings leave people with a good memory of the experience, and which a bad one?",
        groups: ["Ends well", "Ends badly"],
        items: [
          { id: "booking", text: "A booking confirmation with the date, the place and Add to calendar", group: 0 },
          { id: "course", text: "Finishing a course and getting a certificate", group: 0 },
          { id: "delivery", text: "An order confirmation saying when it will arrive", group: 0 },
          { id: "survey", text: "A 15-question survey pop-up straight after paying", group: 1 },
          { id: "ticket", text: "A support chat that ends with “Ticket closed” and no answer", group: 1 },
          { id: "guilt", text: "A cancellation flow that ends with “We're sad you're leaving us behind”", group: 1 },
        ],
        why: "People judge an experience mostly by its best or worst moment and by how it ends. Clear confirmations and a sense of achievement end on a high. A long survey, an unresolved ticket or a guilt trip makes the last moment sour, and that colors how people remember everything before it.",
      },
    ],
  },
  {
    id: "l8",
    code: "L8",
    title: "Tesler's Law",
    subtitle: "Complexity has to live somewhere",
    minutes: 4,
    skills: ["effort"],
    body: [
      "Every task has some complexity that can't be removed: a payment needs an amount and a recipient, a flight search needs a destination and a date. Larry Tesler argued that the real question is who deals with that complexity: the people using the product, or the people building it.",
      "Good design moves as much of it as possible onto the system, with sensible defaults, automatic formatting and information the product already knows. But it doesn't pretend complexity away. Oversimplifying can hide what people need to make a decision, which just moves the complexity somewhere worse.",
    ],
    practice: [
      "Fill in what the system already knows, such as location, currency or recent choices.",
      "Accept input in any reasonable format and clean it up yourself.",
      "Choose defaults that suit most people, and make them easy to change.",
      "Don't hide essential details, such as fees or terms, to make a screen look simpler.",
    ],
    fieldExercise:
      "Pick one form and mark every field the system could fill in or work out itself. Estimate how much typing that would save the people who use it.",
    sources: [lawsOfUx("teslers-law", "Tesler's Law"), nng("videos/teslers-law", "Tesler's Law: Shift Complexity to Simplify UX (video)")],
    exercises: [
      {
        id: "l8-currency",
        type: "compare",
        question: "A travel expense form for a company based in Ireland. An employee paid for a taxi in London. Which design handles the complexity better?",
        a: `<div class="mk"><div class="mk-row"><span><span class="mk-label">Amount</span><span class="mk-in" style="display:block;width:6em">84.50</span></span><span><span class="mk-label">Currency</span><span class="mk-in" style="display:block">GBP ▾</span></span></div><div class="mk-muted">€99.12 at the rate on 3 October 2026. Converted for you.</div></div>`,
        b: `<div class="mk"><div class="mk-row"><span><span class="mk-label">Amount</span><span class="mk-in" style="display:block;width:6em">84.50</span></span><span><span class="mk-label">Currency</span><span class="mk-in" style="display:block">GBP ▾</span></span></div><div class="mk-label">Exchange rate to EUR</div><div class="mk-in">&nbsp;</div><div class="mk-muted">Look up the rate on the date of purchase.</div></div>`,
        describe: {
          a: "Amount 84.50 and Currency GBP. Below: €99.12 at the rate on 3 October 2026. Converted for you.",
          b: "Amount 84.50 and Currency GBP, then an empty field labeled Exchange rate to EUR, with the note: Look up the rate on the date of purchase.",
        },
        correct: "a",
        why: "In A the system does the currency conversion, which it can do reliably, and shows the result so people can check it. B pushes the same unavoidable work onto every employee, who must find the right rate and type it in, with plenty of room for mistakes.",
      },
      {
        id: "l8-hidden-fees",
        type: "choice",
        question: "To make checkout look simpler, a team wants to hide shipping costs until the final confirmation step. What does Tesler's Law suggest?",
        options: [
          "Good idea, because fewer numbers on the screen mean less complexity",
          "Shipping is part of the decision, so show it and simplify elsewhere",
          "Hide it, but add a tooltip next to the total saying shipping is extra",
          "Show it only to people who click a link asking about delivery costs",
        ],
        correct: 1,
        why: "Hiding the cost doesn't remove the complexity; it moves it to the last step, where it surprises people and makes them abandon their carts. Simplify what can be simplified, but keep essential information visible. A tooltip or an on-request answer still hides it from most people.",
      },
      {
        id: "l8-spot-utc-offset",
        type: "spot",
        question: "Which part pushes work onto people that the system could do itself?",
        title: "Schedule a meeting",
        parts: [
          {
            id: "title",
            label: "Field labeled Meeting title, containing Weekly design review",
            html: `<div class="mk-label">Meeting title</div><div class="mk-in">Weekly design review</div>`,
          },
          {
            id: "when",
            label: "Field labeled Date and time, containing Tue 13 Oct, 10:00 AM",
            html: `<div class="mk-label">Date and time</div><div class="mk-in">Tue 13 Oct · 10:00 AM</div>`,
          },
          {
            id: "tz",
            label: "Field labeled Your time zone, with the hint Enter your UTC offset, for example -05:00. It's empty.",
            html: `<div class="mk-label">Your time zone</div><div class="mk-muted">Enter your UTC offset, for example -05:00</div><div class="mk-in">&nbsp;</div>`,
          },
          {
            id: "submit",
            label: "Button: Send invite",
            html: `<span class="mk-btn">Send invite</span>`,
          },
        ],
        correct: "tz",
        why: "The browser already knows the person's time zone, so the system can fill it in and let them change it if they need to. Asking for a UTC offset also makes people work out daylight saving time themselves, which is how meetings end up at the wrong hour.",
      },
      {
        id: "l8-sort-complexity",
        type: "sort",
        question: "An expense form for a company in Ireland. Which details should the system work out, and which only the employee can give?",
        groups: ["System works it out", "Employee provides it"],
        items: [
          { id: "rate", text: "The exchange rate on the day of purchase", group: 0 },
          { id: "today", text: "Today's date, for the claim", group: 0 },
          { id: "total", text: "The total of all the receipts", group: 0 },
          { id: "reason", text: "Why the expense was needed", group: 1 },
          { id: "project", text: "Which client project it belongs to", group: 1 },
        ],
        why: "Exchange rates, today's date and adding up receipts are things software can do reliably, so asking people for them just adds work and mistakes. The reason for an expense and the project it belongs to live only in the employee's head, so those are the questions worth their time.",
      },
    ],
  },
];

export const lawsOfUxPath: LearningPath = {
  id: "laws-of-ux",
  title: "Laws of UX",
  description: "Jakob's, Fitts's, Hick's and Miller's laws, Gestalt grouping and other psychology principles.",
  status: "live",
  lessons,
};
